Repository OCA/delivery-carrier, pull requests merged in 2018-11, with the labels that each got.

#168 [10.0][ADD] delivery_price_rule_untaxed
  delivery_price_rule_untaxed/README.rst
  delivery_price_rule_untaxed/__init__.py
  delivery_price_rule_untaxed/__manifest__.py
  delivery_price_rule_untaxed/data/delivery_price_rule_untaxed_demo.xml
  delivery_price_rule_untaxed/i18n/it.po
  delivery_price_rule_untaxed/models/__init__.py
  delivery_price_rule_untaxed/models/delivery_carrier.py
  delivery_price_rule_untaxed/models/delivery_price_rule.py
  delivery_price_rule_untaxed/readme/CONTRIBUTORS.rst
  delivery_price_rule_untaxed/readme/DESCRIPTION.rst
  delivery_price_rule_untaxed/static/description/index.html
  delivery_price_rule_untaxed/tests/__init__.py
  delivery_price_rule_untaxed/tests/test_delivery_price_rule_untaxed.py
Labels: question

#164 [11.0][NEW] partner_delivery_schedule: New module for set a delivery schedule for partners
  partner_delivery_schedule/README.rst
  partner_delivery_schedule/__init__.py
  partner_delivery_schedule/__manifest__.py
  partner_delivery_schedule/i18n/es.po
  partner_delivery_schedule/models/__init__.py
  partner_delivery_schedule/models/partner_delivery_schedule.py
  partner_delivery_schedule/models/res_partner.py
  partner_delivery_schedule/readme/CONTRIBUTORS.rst
  partner_delivery_schedule/readme/DESCRIPTION.rst
  partner_delivery_schedule/readme/USAGE.rst
  partner_delivery_schedule/security/ir.model.access.csv
  partner_delivery_schedule/static/description/icon.png
  partner_delivery_schedule/tests/__init__.py
  partner_delivery_schedule/tests/test_partner_delivery_schedule.py
  partner_delivery_schedule/views/partner_delivery_schedule_view.xml
  partner_delivery_schedule/views/report_shipping.xml
  partner_delivery_schedule/views/res_partner_view.xml
Labels: approved, needs review, ready to merge

#169 [11.0][MIG] delivery_carrier_label_default
  delivery_carrier_label_default/README.rst
  delivery_carrier_label_default/__init__.py
  delivery_carrier_label_default/__manifest__.py
  delivery_carrier_label_default/models/__init__.py
  delivery_carrier_label_default/models/stock.py
  delivery_carrier_label_default/readme/CONTRIBUTORS.rst
  delivery_carrier_label_default/readme/CREDITS.rst
  delivery_carrier_label_default/readme/DESCRIPTION.rst
  delivery_carrier_label_default/readme/ROADMAP.rst
  delivery_carrier_label_default/static/description/icon.svg
  delivery_carrier_label_default/static/description/index.html
  delivery_carrier_label_default/tests/__init__.py
  delivery_carrier_label_default/tests/common.py
  delivery_carrier_label_default/tests/test_print_label.py
  delivery_carrier_label_default/views/report_default_label.xml
  delivery_carrier_label_default/views/reports.xml
Labels: approved, needs review
