Repository OCA/delivery-carrier, pull requests merged in 2019-03, with the labels that each got.

#177 [ADD] delivery_free_fee_removal: avoid create delivery line if price is zero
  delivery_free_fee_removal/README.rst
  delivery_free_fee_removal/__init__.py
  delivery_free_fee_removal/__manifest__.py
  delivery_free_fee_removal/i18n/delivery_free_fee_removal.pot
  delivery_free_fee_removal/i18n/es.po
  delivery_free_fee_removal/models/__init__.py
  delivery_free_fee_removal/models/sale_order.py
  delivery_free_fee_removal/readme/CONTRIBUTORS.rst
  delivery_free_fee_removal/readme/DESCRIPTION.rst
  delivery_free_fee_removal/static/description/index.html
  delivery_free_fee_removal/tests/__init__.py
  delivery_free_fee_removal/tests/test_delivery_free_fee_removal.py
Labels: approved, needs review

#174 [11.0][MIG] delivery_multi_destination: Migration to 11.0
  delivery_multi_destination/README.rst
  delivery_multi_destination/__init__.py
  delivery_multi_destination/__manifest__.py
  delivery_multi_destination/demo/delivery_carrier_demo.xml
  delivery_multi_destination/i18n/cs_CZ.po
  delivery_multi_destination/i18n/de.po
  delivery_multi_destination/i18n/delivery_multi_destination.pot
  delivery_multi_destination/i18n/es.po
  delivery_multi_destination/i18n/fr.po
  delivery_multi_destination/i18n/it.po
  delivery_multi_destination/i18n/nl.po
  delivery_multi_destination/i18n/nl_NL.po
  delivery_multi_destination/i18n/pt_BR.po
  delivery_multi_destination/i18n/sl.po
  delivery_multi_destination/models/__init__.py
  delivery_multi_destination/models/delivery_carrier.py
  delivery_multi_destination/readme/CONFIGURE.rst
  delivery_multi_destination/readme/CONTRIBUTORS.rst
  delivery_multi_destination/readme/DESCRIPTION.rst
  delivery_multi_destination/readme/ROADMAP.rst
  delivery_multi_destination/readme/USAGE.rst
  delivery_multi_destination/static/description/icon.png
  delivery_multi_destination/static/description/index.html
  delivery_multi_destination/tests/__init__.py
  delivery_multi_destination/tests/test_delivery_multi_destination.py
  delivery_multi_destination/views/delivery_carrier_view.xml
Labels: approved, needs review

#179 [11.0][FIX] partner_delivery_zone: Get delivery zone from partner when a picking is created and no sale line is linked (pick-pack...)
  partner_delivery_zone/__manifest__.py
  partner_delivery_zone/models/stock_move.py
  partner_delivery_zone/tests/test_partner_delivery_zone.py
Labels: approved, enhancement

#180 better carrier partner form
  delivery_carrier_partner/views/delivery_carrier_views.xml
Labels: enhancement
