Repository OCA/delivery-carrier, pull requests merged in 2019-04, with the labels that each got.

#173 [11.0][MIG] delivery_price_rule_untaxed
  delivery_price_rule_untaxed/README.rst
  delivery_price_rule_untaxed/__init__.py
  delivery_price_rule_untaxed/__manifest__.py
  delivery_price_rule_untaxed/data/delivery_price_rule_untaxed_demo.xml
  delivery_price_rule_untaxed/i18n/delivery_price_rule_untaxed.pot
  delivery_price_rule_untaxed/i18n/it.po
  delivery_price_rule_untaxed/models/__init__.py
  delivery_price_rule_untaxed/models/delivery_carrier.py
  delivery_price_rule_untaxed/models/delivery_price_rule.py
  delivery_price_rule_untaxed/readme/CONTRIBUTORS.rst
  delivery_price_rule_untaxed/readme/DESCRIPTION.rst
  delivery_price_rule_untaxed/static/description/index.html
  delivery_price_rule_untaxed/tests/__init__.py
  delivery_price_rule_untaxed/tests/test_delivery_price_rule_untaxed.py
Labels: approved, needs review, ready to merge

#181 [10.0][IMP] delivery_carrier_label_postlogistics: Consider parent partner name
  delivery_carrier_label_postlogistics/__manifest__.py
  delivery_carrier_label_postlogistics/postlogistics/web_service.py
Labels: approved, enhancement

#182 [MIG] delivery_auto_refresh: Migration to 12.0
  delivery_auto_refresh/README.rst
  delivery_auto_refresh/__init__.py
  delivery_auto_refresh/__manifest__.py
  delivery_auto_refresh/data/ir_config_parameter.xml
  delivery_auto_refresh/i18n/ca.po
  delivery_auto_refresh/i18n/cs_CZ.po
  delivery_auto_refresh/i18n/de.po
  delivery_auto_refresh/i18n/delivery_auto_refresh.pot
  delivery_auto_refresh/i18n/el_GR.po
  delivery_auto_refresh/i18n/es.po
  delivery_auto_refresh/i18n/es_ES.po
  delivery_auto_refresh/i18n/es_VE.po
  delivery_auto_refresh/i18n/fi.po
  delivery_auto_refresh/i18n/fr.po
  delivery_auto_refresh/i18n/gl.po
  delivery_auto_refresh/i18n/hr.po
  delivery_auto_refresh/i18n/hr_HR.po
  delivery_auto_refresh/i18n/hu.po
  delivery_auto_refresh/i18n/it.po
  delivery_auto_refresh/i18n/nl.po
  delivery_auto_refresh/i18n/nl_NL.po
  delivery_auto_refresh/i18n/pt.po
  delivery_auto_refresh/i18n/pt_BR.po
  delivery_auto_refresh/i18n/ro.po
  delivery_auto_refresh/i18n/sl.po
  delivery_auto_refresh/i18n/tr.po
  delivery_auto_refresh/i18n/tr_TR.po
  delivery_auto_refresh/i18n/vi_VN.po
  delivery_auto_refresh/i18n/zh_CN.po
  delivery_auto_refresh/models/__init__.py
  delivery_auto_refresh/models/sale_order.py
  delivery_auto_refresh/models/stock_picking.py
  delivery_auto_refresh/readme/CONFIGURE.rst
  delivery_auto_refresh/readme/CONTRIBUTORS.rst
  delivery_auto_refresh/readme/DESCRIPTION.rst
  delivery_auto_refresh/readme/ROADMAP.rst
  delivery_auto_refresh/static/description/index.html
  delivery_auto_refresh/tests/__init__.py
  delivery_auto_refresh/tests/test_delivery_auto_refresh.py
Labels: approved, needs review

#145 [IMP] sale_delivery_rate: Isolate record data
  sale_delivery_rate/__manifest__.py
  sale_delivery_rate/models/delivery_carrier_rate.py
Labels: approved, enhancement, needs review, ready to merge

#165 [ADD] delivery_price_by_category
  .travis.yml
  delivery_price_by_category/README.rst
  delivery_price_by_category/__init__.py
  delivery_price_by_category/__manifest__.py
  delivery_price_by_category/i18n/it.po
  delivery_price_by_category/models/__init__.py
  delivery_price_by_category/models/delivery_carrier.py
  delivery_price_by_category/models/delivery_price_rule.py
  delivery_price_by_category/readme/CONFIGURE.rst
  delivery_price_by_category/readme/CONTRIBUTORS.rst
  delivery_price_by_category/readme/DESCRIPTION.rst
  delivery_price_by_category/readme/USAGE.rst
  delivery_price_by_category/tests/__init__.py
  delivery_price_by_category/tests/test_price_by_category.py
  delivery_price_by_category/views/delivery_price_rule.xml
Labels: approved, needs review, ready to merge
