Repository OCA/delivery-carrier, pull requests merged in 2019-09, with the labels that each got.

#219 [FIX] Update travis template
  .travis.yml
Labels: approved

#218 [IMP] partner_delivery_zone: Add active field to allow to archive delivery zones
  partner_delivery_zone/models/partner_delivery_zone.py
  partner_delivery_zone/views/partner_delivery_zone_view.xml
Labels: approved

#220 [12.0][base_delivery_carrier_label] Wait data encoded in base64 / write tracking number on package
  base_delivery_carrier_label/models/shipping_label.py
  base_delivery_carrier_label/models/stock_picking.py
Labels: approved

#216 IMP add view to carrier.account
  base_delivery_carrier_label/__manifest__.py
  base_delivery_carrier_label/models/carrier_account.py
  base_delivery_carrier_label/security/carrier_security.xml
  base_delivery_carrier_label/views/carrier_account.xml
Labels: approved, ready to merge

#189 [10.0][ADD] delivery_carrier_default_tracking_url
  delivery_carrier_default_tracking_url/README.rst
  delivery_carrier_default_tracking_url/__init__.py
  delivery_carrier_default_tracking_url/__manifest__.py
  delivery_carrier_default_tracking_url/models/__init__.py
  delivery_carrier_default_tracking_url/models/delivery_carrier.py
  delivery_carrier_default_tracking_url/models/sale_order.py
  delivery_carrier_default_tracking_url/models/stock_picking.py
  delivery_carrier_default_tracking_url/readme/CONTRIBUTORS.rst
  delivery_carrier_default_tracking_url/readme/DESCRIPTION.rst
  delivery_carrier_default_tracking_url/readme/USAGE.rst
  delivery_carrier_default_tracking_url/static/description/icon.png
  delivery_carrier_default_tracking_url/static/description/index.html
  delivery_carrier_default_tracking_url/views/delivery_carrier.xml
  delivery_carrier_default_tracking_url/views/sale_order.xml
  delivery_carrier_default_tracking_url/views/stock_picking.xml
  setup/delivery_carrier_default_tracking_url/odoo/addons/delivery_carrier_default_tracking_url
  setup/delivery_carrier_default_tracking_url/setup.cfg
  setup/delivery_carrier_default_tracking_url/setup.py
Labels: approved, needs review, ready to merge
