Repository OCA/delivery-carrier, pull requests merged in 2019-05, with the labels that each got.

#190 [9.0][FIX] delivery_carrier_label_postlogistics: fix integration WSDL file
  delivery_carrier_label_postlogistics/data/integration/barcode_v2_2_wsbc.wsdl
Labels: approved, enhancement, ready to merge

#191 [10.0][FIX] delivery_carrier_label_postlogistics: fix integration WSDL file
  delivery_carrier_label_postlogistics/data/integration/barcode_v2_2_wsbc.wsdl
Labels: enhancement

#193 [12.0][mig] delivery_multi_destination
  delivery_multi_destination/README.rst
  delivery_multi_destination/__init__.py
  delivery_multi_destination/__manifest__.py
  delivery_multi_destination/demo/delivery_carrier_demo.xml
  delivery_multi_destination/i18n/cs_CZ.po
  delivery_multi_destination/i18n/de.po
  delivery_multi_destination/i18n/delivery_multi_destination.pot
  delivery_multi_destination/i18n/es.po
  delivery_multi_destination/i18n/fr.po
  delivery_multi_destination/i18n/it.po
  delivery_multi_destination/i18n/nl.po
  delivery_multi_destination/i18n/nl_NL.po
  delivery_multi_destination/i18n/pt_BR.po
  delivery_multi_destination/i18n/sl.po
  delivery_multi_destination/models/__init__.py
  delivery_multi_destination/models/delivery_carrier.py
  delivery_multi_destination/readme/CONFIGURE.rst
  delivery_multi_destination/readme/CONTRIBUTORS.rst
  delivery_multi_destination/readme/DESCRIPTION.rst
  delivery_multi_destination/readme/ROADMAP.rst
  delivery_multi_destination/readme/USAGE.rst
  delivery_multi_destination/static/description/icon.png
  delivery_multi_destination/static/description/index.html
  delivery_multi_destination/tests/__init__.py
  delivery_multi_destination/tests/test_delivery_multi_destination.py
  delivery_multi_destination/views/delivery_carrier_view.xml
Labels: approved, ready to merge
