Repository OCA/delivery-carrier, pull requests merged in 2020-08, with the labels that each got.

#261 [13.0][MIG] delivery_carrier_partner
  delivery_carrier_partner/README.rst
  delivery_carrier_partner/__init__.py
  delivery_carrier_partner/__manifest__.py
  delivery_carrier_partner/i18n/delivery_carrier_partner.pot
  delivery_carrier_partner/i18n/it.po
  delivery_carrier_partner/models/__init__.py
  delivery_carrier_partner/models/delivery_carrier.py
  delivery_carrier_partner/readme/CONTRIBUTORS.rst
  delivery_carrier_partner/readme/DESCRIPTION.rst
  delivery_carrier_partner/static/description/index.html
  delivery_carrier_partner/views/delivery_carrier_views.xml
  setup/delivery_carrier_partner/odoo/addons/delivery_carrier_partner
  setup/delivery_carrier_partner/setup.py
Labels: approved, bot is merging ⏳, migration, needs review, ready to merge

#277 [IMP] delivery_state: automated action
  delivery_state/README.rst
  delivery_state/__manifest__.py
  delivery_state/data/ir_cron_data.xml
  delivery_state/models/stock_picking.py
  delivery_state/readme/CONFIGURE.rst
  delivery_state/readme/CONTRIBUTORS.rst
  delivery_state/readme/USAGE.rst
  delivery_state/static/description/index.html
  delivery_state/tests/test_delivery_state.py
  delivery_state/views/stock_picking_views.xml
Labels: approved, bot is merging ⏳, enhancement, needs review

#283 [12.0][REF] extract delivery_carrier_info from base_delivery_carrier_label
  base_delivery_carrier_label/__manifest__.py
  base_delivery_carrier_label/models/delivery_carrier.py
  base_delivery_carrier_label/views/delivery.xml
  delivery_carrier_info/__init__.py
  delivery_carrier_info/__manifest__.py
  delivery_carrier_info/models/__init__.py
  delivery_carrier_info/models/delivery_carrier.py
  delivery_carrier_info/readme/CONTRIBUTORS.rst
  delivery_carrier_info/readme/DESCRIPTION.rst
  delivery_carrier_info/readme/USAGE.rst
  delivery_carrier_info/views/delivery_view.xml
Labels: approved, bot is merging ⏳, needs review
