Repository OCA/delivery-carrier, pull requests merged in 2020-10, with the labels that each got.

#295 [12.0] [base_delivery_carrier_label] helper functions + refactoring
  base_delivery_carrier_label/models/carrier_account.py
  base_delivery_carrier_label/models/delivery_carrier.py
  base_delivery_carrier_label/models/stock_picking.py
  base_delivery_carrier_label/tests/__init__.py
  base_delivery_carrier_label/tests/carrier_label_case.py
  base_delivery_carrier_label/tests/test_helper_functions.py
  base_delivery_carrier_label/tests/test_send.py
  base_delivery_carrier_label/views/carrier_account.xml
  base_delivery_carrier_label/views/stock.xml
Labels: approved, bot is merging ⏳, ready to merge

#299 [12.0] Fix deliver_auto_refresh unit tests
  delivery_auto_refresh/tests/test_delivery_auto_refresh.py
Labels: approved, bot is merging ⏳

#222 [12.0][MIG] delivery_carrier_label_batch
  delivery_carrier_label_batch/README.rst
  delivery_carrier_label_batch/__init__.py
  delivery_carrier_label_batch/__manifest__.py
  delivery_carrier_label_batch/data/ir.config_parameter.xml
  delivery_carrier_label_batch/i18n/de.po
  delivery_carrier_label_batch/i18n/delivery_carrier_label_batch.pot
  delivery_carrier_label_batch/i18n/fr.po
  delivery_carrier_label_batch/models/__init__.py
  delivery_carrier_label_batch/models/stock_batch_picking.py
  delivery_carrier_label_batch/pdf_utils.py
  delivery_carrier_label_batch/readme/CONFIGURE.rst
  delivery_carrier_label_batch/readme/CONTRIBUTORS.rst
  delivery_carrier_label_batch/readme/DESCRIPTION.rst
  delivery_carrier_label_batch/readme/USAGE.rst
  delivery_carrier_label_batch/tests/__init__.py
  delivery_carrier_label_batch/tests/dummy.pdf
  delivery_carrier_label_batch/tests/test_generate_labels.py
  delivery_carrier_label_batch/views/stock_batch_picking.xml
  delivery_carrier_label_batch/wizard/__init__.py
  delivery_carrier_label_batch/wizard/apply_carrier.py
  delivery_carrier_label_batch/wizard/apply_carrier_view.xml
  delivery_carrier_label_batch/wizard/generate_labels.py
  delivery_carrier_label_batch/wizard/generate_labels_view.xml
  delivery_carrier_label_batch/zpl_utils.py
  oca_dependencies.txt
Labels: bot is merging ⏳, needs review

#300 [12.0] delivery_carrier_label_batch - Remove broken icon
  delivery_carrier_label_batch/wizard/generate_labels_view.xml
Labels: bot is merging ⏳

#305 14.0 mig delivery carrier info
  delivery_carrier_info/README.rst
  delivery_carrier_info/__init__.py
  delivery_carrier_info/__manifest__.py
  delivery_carrier_info/i18n/delivery_carrier_info.pot
  delivery_carrier_info/models/__init__.py
  delivery_carrier_info/models/delivery_carrier.py
  delivery_carrier_info/readme/CONTRIBUTORS.rst
  delivery_carrier_info/readme/DESCRIPTION.rst
  delivery_carrier_info/readme/USAGE.rst
  delivery_carrier_info/static/description/icon.png
  delivery_carrier_info/static/description/index.html
  delivery_carrier_info/views/delivery_view.xml
Labels: approved, bot is merging ⏳, migration, needs review

#308 [FIX] ceci n'est pas une URL
  delivery_carrier_info/__manifest__.py
Labels: bot is merging ⏳

#307 [13.0] Improve handling of free fee SO lines removal for 13.0
  delivery_free_fee_removal/__manifest__.py
  delivery_free_fee_removal/models/__init__.py
  delivery_free_fee_removal/models/sale_order.py
  delivery_free_fee_removal/models/sale_order_line.py
  delivery_free_fee_removal/readme/DESCRIPTION.rst
  delivery_free_fee_removal/reports/sale_report_templates.xml
  delivery_free_fee_removal/tests/test_delivery_free_fee_removal.py
  delivery_free_fee_removal/views/sale_order_views.xml
Labels: approved, bot is merging ⏳

#289 [ADD] delivery_carrier_label_paazl
  delivery_carrier_label_paazl/README.rst
  delivery_carrier_label_paazl/__init__.py
  delivery_carrier_label_paazl/__manifest__.py
  delivery_carrier_label_paazl/controllers/__init__.py
  delivery_carrier_label_paazl/controllers/main.py
  delivery_carrier_label_paazl/data/delivery_carrier.xml
  delivery_carrier_label_paazl/data/delivery_carrier_template_option.xml
  delivery_carrier_label_paazl/data/ir_config_parameter.xml
  delivery_carrier_label_paazl/i18n/.empty
  delivery_carrier_label_paazl/models/__init__.py
  delivery_carrier_label_paazl/models/carrier_account.py
  delivery_carrier_label_paazl/models/delivery_carrier.py
  delivery_carrier_label_paazl/models/stock_picking.py
  delivery_carrier_label_paazl/readme/CONFIGURE.rst
  delivery_carrier_label_paazl/readme/CONTRIBUTORS.rst
  delivery_carrier_label_paazl/readme/DESCRIPTION.rst
  delivery_carrier_label_paazl/readme/USAGE.rst
  delivery_carrier_label_paazl/readme/newsfragments/.gitkeep
  delivery_carrier_label_paazl/static/description/icon.png
  delivery_carrier_label_paazl/static/description/index.html
  delivery_carrier_label_paazl/tests/__init__.py
  delivery_carrier_label_paazl/tests/test_delivery_carrier_label_paazl.py
  delivery_carrier_label_paazl/views/carrier_account.xml
  requirements.txt
Labels: approved, bot is merging ⏳, ready to merge

#304 [ADD] delivery_carrier_label_ups
  delivery_carrier_label_ups/README.rst
  delivery_carrier_label_ups/__init__.py
  delivery_carrier_label_ups/__manifest__.py
  delivery_carrier_label_ups/data/delivery_carrier.xml
  delivery_carrier_label_ups/data/delivery_carrier_template_option.xml
  delivery_carrier_label_ups/data/ir_config_parameter.xml
  delivery_carrier_label_ups/i18n/.empty
  delivery_carrier_label_ups/models/__init__.py
  delivery_carrier_label_ups/models/carrier_account.py
  delivery_carrier_label_ups/models/delivery_carrier.py
  delivery_carrier_label_ups/models/product_packaging.py
  delivery_carrier_label_ups/models/stock_picking.py
  delivery_carrier_label_ups/readme/CONFIGURE.rst
  delivery_carrier_label_ups/readme/CONTRIBUTORS.rst
  delivery_carrier_label_ups/readme/DESCRIPTION.rst
  delivery_carrier_label_ups/readme/ROADMAP.rst
  delivery_carrier_label_ups/readme/USAGE.rst
  delivery_carrier_label_ups/readme/newsfragments/.gitkeep
  delivery_carrier_label_ups/static/description/icon.png
  delivery_carrier_label_ups/static/description/index.html
  delivery_carrier_label_ups/tests/__init__.py
  delivery_carrier_label_ups/tests/test_delivery_carrier_label_ups.py
  delivery_carrier_label_ups/views/carrier_account.xml
  delivery_carrier_label_ups/views/product_packaging.xml
Labels: approved, bot is merging ⏳, needs review, ready to merge

#310 [13.0][MIG] stock_picking_report_delivery_cost: Migration to 13.0
  setup/stock_picking_report_delivery_cost/odoo/addons/stock_picking_report_delivery_cost
  setup/stock_picking_report_delivery_cost/setup.py
  stock_picking_report_delivery_cost/README.rst
  stock_picking_report_delivery_cost/__init__.py
  stock_picking_report_delivery_cost/__manifest__.py
  stock_picking_report_delivery_cost/i18n/es.po
  stock_picking_report_delivery_cost/i18n/stock_picking_report_delivery_cost.pot
  stock_picking_report_delivery_cost/models/__init__.py
  stock_picking_report_delivery_cost/models/stock_picking.py
  stock_picking_report_delivery_cost/readme/CONTRIBUTORS.rst
  stock_picking_report_delivery_cost/readme/DESCRIPTION.rst
  stock_picking_report_delivery_cost/readme/USAGE.rst
  stock_picking_report_delivery_cost/report/report_deliveryslip.xml
  stock_picking_report_delivery_cost/report/report_shipping.xml
  stock_picking_report_delivery_cost/static/description/icon.png
  stock_picking_report_delivery_cost/static/description/index.html
  stock_picking_report_delivery_cost/tests/__init__.py
  stock_picking_report_delivery_cost/tests/test_stock_picking_report_delivery_cost.py
Labels: approved, bot is merging ⏳
