Repository OCA/delivery-carrier, pull requests merged in 2020-11, with the labels that each got.

#313 [12.0] postlogistics filter int credentials
  delivery_carrier_label_postlogistics/tests/fixtures/cassettes/test_missing_language.yaml
  delivery_carrier_label_postlogistics/tests/fixtures/cassettes/test_store_label.yaml
  delivery_carrier_label_postlogistics/tests/test_postlogistics.py
Labels: bot is merging ⏳

#312 [12.0] Fix access to ir.config_parameter to get access token parameters
  delivery_carrier_label_postlogistics/postlogistics/web_service.py
Labels: approved, bot is merging ⏳, enhancement, needs review, ready to merge

#294 [12.0][FIX] update delivery with multiple lines fails
  delivery_auto_refresh/models/sale_order.py
Labels: approved, bot is merging ⏳, enhancement, needs review

#316 [13.0][PORT] base_delivery_carrier_label (port missing commit into 13.0)
  base_delivery_carrier_label/__manifest__.py
  base_delivery_carrier_label/models/carrier_account.py
  base_delivery_carrier_label/models/delivery_carrier.py
  base_delivery_carrier_label/models/delivery_carrier_option.py
  base_delivery_carrier_label/models/stock_move_line.py
  base_delivery_carrier_label/models/stock_picking.py
  base_delivery_carrier_label/models/stock_quant_package.py
  base_delivery_carrier_label/tests/__init__.py
  base_delivery_carrier_label/tests/carrier_label_case.py
  base_delivery_carrier_label/tests/test_helper_functions.py
  base_delivery_carrier_label/tests/test_send.py
  base_delivery_carrier_label/views/carrier_account.xml
  base_delivery_carrier_label/views/delivery.xml
  base_delivery_carrier_label/views/stock.xml
  base_delivery_carrier_label/wizard/manifest_wizard_view.xml
  delivery_carrier_info/__init__.py
  delivery_carrier_info/__manifest__.py
  delivery_carrier_info/models/__init__.py
  delivery_carrier_info/models/delivery_carrier.py
  delivery_carrier_info/readme/CONTRIBUTORS.rst
  delivery_carrier_info/readme/DESCRIPTION.rst
  delivery_carrier_info/readme/USAGE.rst
  delivery_carrier_info/views/delivery_view.xml
Labels: approved, bot is merging ⏳

#314 [12.0] Postlogistics - Recycle access token
  delivery_carrier_label_postlogistics/postlogistics/web_service.py
Labels: bot is merging ⏳

#301 [12.0] postlogistics sanitize string
  delivery_carrier_label_postlogistics/__manifest__.py
  delivery_carrier_label_postlogistics/postlogistics/web_service.py
Labels: bot is merging ⏳, enhancement, needs review

#321 [UPD] delivery_carrier_info: fix website key in manifest
  delivery_carrier_info/__manifest__.py
Labels: bot is merging ⏳

#319 [13.0][IMP] delivery_free_fee_removal fix invoicing
  delivery_free_fee_removal/models/__init__.py
  delivery_free_fee_removal/models/sale_order.py
  delivery_free_fee_removal/models/sale_order_line.py
  delivery_free_fee_removal/readme/CONTRIBUTORS.rst
  delivery_free_fee_removal/tests/test_delivery_free_fee_removal.py
Labels: approved, bot is merging ⏳, ready to merge
