Repository OCA/delivery-carrier, pull requests merged in 2020-07, with the labels that each got.

#266 [12.0][ADD] delivery_state: Delivery status tracking
  delivery_state/README.rst
  delivery_state/__init__.py
  delivery_state/__manifest__.py
  delivery_state/i18n/delivery_state.pot
  delivery_state/i18n/es.po
  delivery_state/models/__init__.py
  delivery_state/models/delivery_carrier.py
  delivery_state/models/stock_picking.py
  delivery_state/readme/CONTRIBUTORS.rst
  delivery_state/readme/DESCRIPTION.rst
  delivery_state/readme/USAGE.rst
  delivery_state/static/description/index.html
  delivery_state/tests/__init__.py
  delivery_state/tests/test_delivery_state.py
  delivery_state/views/stock_picking_views.xml
Labels: bot is merging ⏳, needs review

#270 [12.0][ADD] delivery_price_method
  delivery_price_method/README.rst
  delivery_price_method/__init__.py
  delivery_price_method/__manifest__.py
  delivery_price_method/models/__init__.py
  delivery_price_method/models/delivery_carrier.py
  delivery_price_method/readme/CONTRIBUTORS.rst
  delivery_price_method/readme/DESCRIPTION.rst
  delivery_price_method/readme/USAGE.rst
  delivery_price_method/static/description/index.html
  delivery_price_method/tests/__init__.py
  delivery_price_method/tests/test_delivery_price_method.py
  delivery_price_method/views/delivery_carrier_views.xml
Labels: approved, bot is merging ⏳

#274 [12.0][ADD] delivery_package_number: New module
  delivery_package_number/README.rst
  delivery_package_number/__init__.py
  delivery_package_number/__manifest__.py
  delivery_package_number/i18n/delivery_package_number.pot
  delivery_package_number/i18n/es.po
  delivery_package_number/models/__init__.py
  delivery_package_number/models/stock_picking.py
  delivery_package_number/readme/CONTRIBUTORS.rst
  delivery_package_number/readme/DESCRIPTION.rst
  delivery_package_number/readme/USAGE.rst
  delivery_package_number/static/description/index.html
  delivery_package_number/tests/__init__.py
  delivery_package_number/tests/test_delivery_package_number.py
  delivery_package_number/views/stock_picking_views.xml
  delivery_package_number/wizard/__init__.py
  delivery_package_number/wizard/stock_immediate_transfer_views.xml
  delivery_package_number/wizard/stock_inmediate_transfer.py
Labels: bot is merging ⏳
