Repository OCA/delivery-carrier, pull requests merged in 2020-09, with the labels that each got.

#255 [FIX] partner_delivery_zone: Fix compute methods for all records
  partner_delivery_zone/models/sale_order.py
  partner_delivery_zone/models/stock_picking.py
  partner_delivery_zone/tests/test_partner_delivery_zone.py
Labels: approved, bot is merging ⏳, ready to merge

#238 [10.0] delivery_carrier_deposit: add group on menu entry
  delivery_carrier_deposit/wizards/deposit.xml
Labels: approved, bot is merging ⏳, enhancement, needs review, ready to merge

#288 [ADD] base_delivery_carrier_label: active flag for options
  base_delivery_carrier_label/models/delivery_carrier.py
  base_delivery_carrier_label/models/delivery_carrier_option.py
  base_delivery_carrier_label/views/delivery.xml
Labels: approved, bot is merging ⏳, enhancement, needs review

#280 [13.0] Migrate delivery_free_fee_removal
  delivery_free_fee_removal/README.rst
  delivery_free_fee_removal/__init__.py
  delivery_free_fee_removal/__manifest__.py
  delivery_free_fee_removal/i18n/delivery_free_fee_removal.pot
  delivery_free_fee_removal/i18n/es.po
  delivery_free_fee_removal/models/__init__.py
  delivery_free_fee_removal/models/sale_order.py
  delivery_free_fee_removal/readme/CONTRIBUTORS.rst
  delivery_free_fee_removal/readme/DESCRIPTION.rst
  delivery_free_fee_removal/static/description/icon.png
  delivery_free_fee_removal/static/description/index.html
  delivery_free_fee_removal/tests/__init__.py
  delivery_free_fee_removal/tests/test_delivery_free_fee_removal.py
  setup/delivery_free_fee_removal/odoo/addons/delivery_free_fee_removal
  setup/delivery_free_fee_removal/setup.py
Labels: approved, bot is merging ⏳, migration, needs review, ready to merge

#271 [10.0][ADD] delivery_carrier_category
  delivery_carrier_category/README.rst
  delivery_carrier_category/__init__.py
  delivery_carrier_category/__manifest__.py
  delivery_carrier_category/data/delivery_carrier_category.xml
  delivery_carrier_category/models/__init__.py
  delivery_carrier_category/models/delivery_carrier.py
  delivery_carrier_category/models/delivery_carrier_category.py
  delivery_carrier_category/readme/CONTRIBUTORS.rst
  delivery_carrier_category/readme/DESCRIPTION.rst
  delivery_carrier_category/readme/USAGE.rst
  delivery_carrier_category/security/delivery_carrier_category.xml
  delivery_carrier_category/static/description/icon.png
  delivery_carrier_category/static/description/index.html
  delivery_carrier_category/tests/__init__.py
  delivery_carrier_category/tests/test_carrier_category.py
  delivery_carrier_category/views/delivery_carrier.xml
  delivery_carrier_category/views/delivery_carrier_category.xml
  setup/delivery_carrier_category/.eggs/README.txt
  setup/delivery_carrier_category/odoo/__init__.py
  setup/delivery_carrier_category/odoo/addons/__init__.py
  setup/delivery_carrier_category/odoo/addons/delivery_carrier_category
  setup/delivery_carrier_category/setup.py
Labels: approved, bot is merging ⏳, needs review, ready to merge
