Repository OCA/delivery-carrier, pull requests merged in 2021-08, with the labels that each got.

#399 [13.0][ADD] delivery_price_rule_volumetric_weight: Add Volumetric Weight to delivery price rules
  delivery_price_rule_volumetric_weight/README.rst
  delivery_price_rule_volumetric_weight/__init__.py
  delivery_price_rule_volumetric_weight/__manifest__.py
  delivery_price_rule_volumetric_weight/i18n/delivery_price_rule_volumetric_weight.pot
  delivery_price_rule_volumetric_weight/i18n/es.po
  delivery_price_rule_volumetric_weight/models/__init__.py
  delivery_price_rule_volumetric_weight/models/delivery_carrier.py
  delivery_price_rule_volumetric_weight/models/delivery_price_rule.py
  delivery_price_rule_volumetric_weight/readme/CONFIGURE.rst
  delivery_price_rule_volumetric_weight/readme/CONTRIBUTORS.rst
  delivery_price_rule_volumetric_weight/readme/DESCRIPTION.rst
  delivery_price_rule_volumetric_weight/readme/USAGE.rst
  delivery_price_rule_volumetric_weight/static/description/icon.png
  delivery_price_rule_volumetric_weight/static/description/index.html
  delivery_price_rule_volumetric_weight/tests/__init__.py
  delivery_price_rule_volumetric_weight/tests/test_delivery_price.py
  oca_dependencies.txt
  setup/delivery_price_rule_volumetric_weight/odoo/addons/delivery_price_rule_volumetric_weight
  setup/delivery_price_rule_volumetric_weight/setup.py
Labels: bot is merging ⏳

#402 Init copier template
  .copier-answers.yml
  .eslintrc.yml
  .flake8
  .github/workflows/pre-commit.yml
  .github/workflows/stale.yml
  .gitignore
  .isort.cfg
  .pre-commit-config.yaml
  .prettierrc.yml
  .pylintrc
  .pylintrc-mandatory
  .travis.yml
  CONTRIBUTING.md
  LICENSE
  README.md
  base_delivery_carrier_label/tests/test_send.py
  delivery_postlogistics/postlogistics/web_service.py
  delivery_send_to_shipper_at_operation/__manifest__.py
  stock_picking_delivery_link/__manifest__.py
Labels: bot is merging ⏳

#372 [12.0][IMP] delivery_carrier_label_paazl: split methods
  delivery_carrier_label_paazl/models/stock_picking.py
  delivery_carrier_label_paazl/tests/test_delivery_carrier_label_paazl.py
Labels: approved, ready to merge, bot is merging ⏳

#341 [ADD] delivery_carrier_label_ups: Support customer returns
  delivery_carrier_label_ups/models/stock_picking.py
  delivery_carrier_label_ups/readme/ROADMAP.rst
  delivery_carrier_label_ups/tests/test_delivery_carrier_label_ups.py
Labels: bot is merging ⏳

#404 [14.0][IMP] delivery_roulier_laposte_fr tests: mute vcr.cassette logger
  delivery_roulier_laposte_fr/tests/test_laposte_label_dom.py
Labels: bot is merging ⏳

#334 [MIG] delivery_carrier_pricelist: Migration to 14.0
  delivery_carrier_pricelist/README.rst
  delivery_carrier_pricelist/__init__.py
  delivery_carrier_pricelist/__manifest__.py
  delivery_carrier_pricelist/models/__init__.py
  delivery_carrier_pricelist/models/delivery_carrier.py
  delivery_carrier_pricelist/models/stock_picking.py
  delivery_carrier_pricelist/readme/CONTRIBUTORS.rst
  delivery_carrier_pricelist/readme/CREDITS.rst
  delivery_carrier_pricelist/readme/DESCRIPTION.rst
  delivery_carrier_pricelist/security/ir.model.access.csv
  delivery_carrier_pricelist/static/description/index.html
  delivery_carrier_pricelist/tests/__init__.py
  delivery_carrier_pricelist/tests/test_delivery_pricelist.py
  delivery_carrier_pricelist/wizards/__init__.py
  delivery_carrier_pricelist/wizards/choose_delivery_carrier.py
  setup/delivery_carrier_pricelist/odoo/addons/delivery_carrier_pricelist
  setup/delivery_carrier_pricelist/setup.py
Labels: bot is merging ⏳

#360 [14.0][MIG] delivery_package_number: Migration to 14.0
  delivery_package_number/README.rst
  delivery_package_number/__init__.py
  delivery_package_number/__manifest__.py
  delivery_package_number/i18n/delivery_package_number.pot
  delivery_package_number/i18n/es.po
  delivery_package_number/i18n/sl.po
  delivery_package_number/models/__init__.py
  delivery_package_number/models/stock_picking.py
  delivery_package_number/readme/CONTRIBUTORS.rst
  delivery_package_number/readme/DESCRIPTION.rst
  delivery_package_number/readme/USAGE.rst
  delivery_package_number/static/description/icon.png
  delivery_package_number/static/description/index.html
  delivery_package_number/tests/__init__.py
  delivery_package_number/tests/test_delivery_package_number.py
  delivery_package_number/views/stock_picking_views.xml
  delivery_package_number/wizard/__init__.py
  delivery_package_number/wizard/stock_immediate_transfer_views.xml
  delivery_package_number/wizard/stock_inmediate_transfer.py
  setup/_metapackage/VERSION.txt
  setup/delivery_package_number/odoo/addons/delivery_package_number
  setup/delivery_package_number/setup.py
Labels: needs fixing, approved, ready to merge, bot is merging ⏳

#405 [12.0][FIX] paazl: prevent literal `False` showing up on label
  delivery_carrier_label_paazl/models/stock_picking.py
Labels: approved, bot is merging ⏳

#374 14.0 mig partner delivery zone
  partner_delivery_zone/README.rst
  partner_delivery_zone/__init__.py
  partner_delivery_zone/__manifest__.py
  partner_delivery_zone/i18n/de.po
  partner_delivery_zone/i18n/es.po
  partner_delivery_zone/i18n/fr_FR.po
  partner_delivery_zone/i18n/partner_delivery_zone.pot
  partner_delivery_zone/i18n/zh_CN.po
  partner_delivery_zone/models/__init__.py
  partner_delivery_zone/models/partner_delivery_zone.py
  partner_delivery_zone/models/res_partner.py
  partner_delivery_zone/models/sale_order.py
  partner_delivery_zone/models/stock_move.py
  partner_delivery_zone/models/stock_picking.py
  partner_delivery_zone/readme/CONFIGURATION.rst
  partner_delivery_zone/readme/CONTRIBUTORS.rst
  partner_delivery_zone/readme/DESCRIPTION.rst
  partner_delivery_zone/readme/ROADMAP.rst
  partner_delivery_zone/readme/USAGE.rst
  partner_delivery_zone/security/ir.model.access.csv
  partner_delivery_zone/static/description/icon.png
  partner_delivery_zone/static/description/index.html
  partner_delivery_zone/tests/__init__.py
  partner_delivery_zone/tests/test_partner_delivery_zone.py
  partner_delivery_zone/views/partner_delivery_zone_view.xml
  partner_delivery_zone/views/report_deliveryslip.xml
  partner_delivery_zone/views/report_shipping.xml
  partner_delivery_zone/views/res_partner_view.xml
  partner_delivery_zone/views/sale_order_view.xml
  partner_delivery_zone/views/stock_picking_view.xml
  setup/partner_delivery_zone/odoo/addons/partner_delivery_zone
  setup/partner_delivery_zone/setup.py
Labels: needs review, approved, migration, bot is merging ⏳
