Repository OCA/delivery-carrier, pull requests merged in 2021-07, with the labels that each got.

#380 [14.0][ADD] delivery_carrier_city
  delivery_carrier_city/__init__.py
  delivery_carrier_city/__manifest__.py
  delivery_carrier_city/models/__init__.py
  delivery_carrier_city/models/delivery_carrier.py
  delivery_carrier_city/readme/CONTRIBUTORS.rst
  delivery_carrier_city/readme/DESCRIPTION.rst
  delivery_carrier_city/tests/__init__.py
  delivery_carrier_city/tests/test_delivery_carrier_city.py
  delivery_carrier_city/views/delivery_carrier.xml
  setup/delivery_carrier_city/odoo/addons/delivery_carrier_city
  setup/delivery_carrier_city/setup.py
Labels: bot is merging ⏳

#389 [14.0][MIG] stock_picking_delivery_link
  setup/stock_picking_delivery_link/odoo/addons/stock_picking_delivery_link
  setup/stock_picking_delivery_link/setup.py
  stock_picking_delivery_link/README.rst
  stock_picking_delivery_link/__init__.py
  stock_picking_delivery_link/__manifest__.py
  stock_picking_delivery_link/i18n/stock_picking_delivery_link.pot
  stock_picking_delivery_link/models/__init__.py
  stock_picking_delivery_link/models/stock_picking.py
  stock_picking_delivery_link/readme/CONTRIBUTORS.rst
  stock_picking_delivery_link/readme/DESCRIPTION.rst
  stock_picking_delivery_link/static/description/icon.png
  stock_picking_delivery_link/static/description/index.html
  stock_picking_delivery_link/tests/__init__.py
  stock_picking_delivery_link/tests/common.py
  stock_picking_delivery_link/tests/test_delivery_link.py
  stock_picking_delivery_link/views/stock_picking.xml
Labels: approved, bot is merging ⏳, migration, needs review

#388 [12.0] Fix postlogistics error when email contains a "realname"
  delivery_carrier_label_postlogistics/postlogistics/web_service.py
Labels: approved, bot is merging ⏳

#373 14.0 mig delivery multi destination
  delivery_multi_destination/README.rst
  delivery_multi_destination/__init__.py
  delivery_multi_destination/__manifest__.py
  delivery_multi_destination/demo/delivery_carrier_demo.xml
  delivery_multi_destination/i18n/cs_CZ.po
  delivery_multi_destination/i18n/de.po
  delivery_multi_destination/i18n/delivery_multi_destination.pot
  delivery_multi_destination/i18n/es.po
  delivery_multi_destination/i18n/fr.po
  delivery_multi_destination/i18n/it.po
  delivery_multi_destination/i18n/nl.po
  delivery_multi_destination/i18n/nl_NL.po
  delivery_multi_destination/i18n/pt_BR.po
  delivery_multi_destination/i18n/sl.po
  delivery_multi_destination/i18n/zh_CN.po
  delivery_multi_destination/models/__init__.py
  delivery_multi_destination/models/delivery_carrier.py
  delivery_multi_destination/readme/CONFIGURE.rst
  delivery_multi_destination/readme/CONTRIBUTORS.rst
  delivery_multi_destination/readme/DESCRIPTION.rst
  delivery_multi_destination/readme/ROADMAP.rst
  delivery_multi_destination/readme/USAGE.rst
  delivery_multi_destination/static/description/icon.png
  delivery_multi_destination/static/description/index.html
  delivery_multi_destination/tests/__init__.py
  delivery_multi_destination/tests/test_delivery_multi_destination.py
  delivery_multi_destination/views/delivery_carrier_view.xml
  setup/delivery_multi_destination/odoo/addons/delivery_multi_destination
  setup/delivery_multi_destination/setup.py
Labels: approved, bot is merging ⏳

#347 [14][MIG] delivery_roulier
  delivery_roulier/README.rst
  delivery_roulier/__init__.py
  delivery_roulier/__manifest__.py
  delivery_roulier/decorator.py
  delivery_roulier/demo/product.xml
  delivery_roulier/models/__init__.py
  delivery_roulier/models/delivery_carrier.py
  delivery_roulier/models/stock_move_line.py
  delivery_roulier/models/stock_picking.py
  delivery_roulier/models/stock_quant_package.py
  delivery_roulier/readme/CONTRIBUTORS.rst
  delivery_roulier/readme/DESCRIPTION.rst
  delivery_roulier/readme/USAGE.rst
  delivery_roulier/tests/__init__.py
  delivery_roulier/tests/models.py
  delivery_roulier/tests/test_delivery_roulier.py
  delivery_roulier/views/carrier_account.xml
  delivery_roulier/views/stock_quant_package.xml
  requirements.txt
  setup/delivery_roulier/odoo/addons/delivery_roulier
  setup/delivery_roulier/setup.py
  test-requirements.txt
Labels: approved, bot is merging ⏳, migration, needs review, ready to merge

#348 [14][MIG] delivery_roulier_option
  delivery_roulier_option/README.rst
  delivery_roulier_option/__init__.py
  delivery_roulier_option/__manifest__.py
  delivery_roulier_option/data/delivery.xml
  delivery_roulier_option/models/__init__.py
  delivery_roulier_option/models/delivery_option.py
  delivery_roulier_option/models/stock_picking.py
  delivery_roulier_option/models/stock_quant_package.py
  delivery_roulier_option/readme/CONTRIBUTORS.rst
  delivery_roulier_option/readme/DESCRIPTION.rst
  setup/delivery_roulier_option/odoo/addons/delivery_roulier_option
  setup/delivery_roulier_option/setup.py
Labels: approved, bot is merging ⏳

#387 [12.0] Fix Postlogistics webservice error handling
  delivery_carrier_label_postlogistics/models/stock.py
Labels: approved, bot is merging ⏳

#349 [14][MIG] delivery_roulier_laposte
  delivery_roulier/tests/test_delivery_roulier.py
  delivery_roulier_laposte_fr/README.rst
  delivery_roulier_laposte_fr/__init__.py
  delivery_roulier_laposte_fr/__manifest__.py
  delivery_roulier_laposte_fr/data/delivery.xml
  delivery_roulier_laposte_fr/models/__init__.py
  delivery_roulier_laposte_fr/models/delivery.py
  delivery_roulier_laposte_fr/models/stock_picking.py
  delivery_roulier_laposte_fr/models/stock_quant_package.py
  delivery_roulier_laposte_fr/readme/CONFIGURE.rst
  delivery_roulier_laposte_fr/readme/CONTRIBUTORS.rst
  delivery_roulier_laposte_fr/readme/CREDITS.rst
  delivery_roulier_laposte_fr/readme/DESCRIPTION.rst
  delivery_roulier_laposte_fr/static/description/icon.png
  delivery_roulier_laposte_fr/static/description/laposte_small.png
  delivery_roulier_laposte_fr/static/description/logo.jpg
  delivery_roulier_laposte_fr/tests/__init__.py
  delivery_roulier_laposte_fr/tests/cassettes/LaposteLabelDomCase.test_labels.yaml
  delivery_roulier_laposte_fr/tests/cassettes/LaposteLabelFranceCase.test_labels.yaml
  delivery_roulier_laposte_fr/tests/test_laposte_label_dom.py
  delivery_roulier_laposte_fr/tests/test_laposte_label_france.py
  delivery_roulier_laposte_fr/views/stock_picking.xml
  setup/delivery_roulier_laposte_fr/odoo/addons/delivery_roulier_laposte_fr
  setup/delivery_roulier_laposte_fr/setup.py
  test-requirements.txt
Labels: approved, bot is merging ⏳

#390 [12.0][FIX] delivery_carrier_label_ups: access to ir.config_parameter
  delivery_carrier_label_ups/models/stock_picking.py
Labels: approved, bot is merging ⏳, ready to merge

#391 [12.0][FIX] base_delivery_carrier_label: form views usability
  base_delivery_carrier_label/views/delivery.xml
Labels: approved, bot is merging ⏳

#393 [13.0][FIX] delivery_package_fee: put only active fees on SO
  delivery_package_fee/models/stock_picking.py
Labels: approved, bot is merging ⏳

#397 [13.0] delivery_package_fee: fix copy w/ no order lines
  delivery_package_fee/models/sale_order.py
Labels: approved, bot is merging ⏳, bug

#398 [13.0] delivery_postlogistics: Add disallowed chars
  delivery_postlogistics/postlogistics/web_service.py
  delivery_postlogistics/tests/test_sanitize_values.py
Labels: approved, bot is merging ⏳

#324 [12.0][FIX] restore domain behaviour from v9
  delivery_carrier_label_postlogistics/models/delivery.py
  delivery_carrier_label_postlogistics/tests/test_delivery.py
Labels: bot is merging ⏳
