Repository OCA/delivery-carrier, pull requests merged in 2021-02, with the labels that each got.

#333 [13.0][ADD] delivery_purchase: New module
  delivery_purchase/README.rst
  delivery_purchase/__init__.py
  delivery_purchase/__manifest__.py
  delivery_purchase/deadme/CONTRIBUTORS.rst
  delivery_purchase/deadme/DESCRIPTION.rst
  delivery_purchase/deadme/USAGE.rst
  delivery_purchase/models/__init__.py
  delivery_purchase/models/delivery_carrier.py
  delivery_purchase/models/purchase_order.py
  delivery_purchase/models/stock_picking.py
  delivery_purchase/static/description/icon.png
  delivery_purchase/tests/__init__.py
  delivery_purchase/tests/test_delivery_purchase.py
  delivery_purchase/views/purchase_order_view.xml
  setup/delivery_purchase/odoo/addons/delivery_purchase
  setup/delivery_purchase/setup.py
Labels: approved, bot is merging ⏳, needs review

#330 [13.0][IMP] delivery_state: automatic email sending
  delivery_state/README.rst
  delivery_state/__manifest__.py
  delivery_state/data/mail_template.xml
  delivery_state/i18n/delivery_state.pot
  delivery_state/i18n/es.po
  delivery_state/migrations/13.0.2.0.0/post-migrate.py
  delivery_state/readme/CONFIGURE.rst
  delivery_state/readme/USAGE.rst
  delivery_state/static/description/index.html
  delivery_state/tests/test_delivery_state.py
Labels: bot is merging ⏳, enhancement, needs review

#293 [13.0][MIG] delivery_price_method
  delivery_price_method/README.rst
  delivery_price_method/__init__.py
  delivery_price_method/__manifest__.py
  delivery_price_method/i18n/delivery_price_method.pot
  delivery_price_method/models/__init__.py
  delivery_price_method/models/delivery_carrier.py
  delivery_price_method/readme/CONTRIBUTORS.rst
  delivery_price_method/readme/DESCRIPTION.rst
  delivery_price_method/readme/USAGE.rst
  delivery_price_method/static/description/icon.png
  delivery_price_method/static/description/index.html
  delivery_price_method/tests/__init__.py
  delivery_price_method/tests/test_delivery_price_method.py
  delivery_price_method/views/delivery_carrier_views.xml
  setup/delivery_price_method/odoo/addons/delivery_price_method
  setup/delivery_price_method/setup.py
Labels: approved, bot is merging ⏳
