Repository OCA/delivery-carrier, pull requests merged in 2021-11, with the labels that each got.

#435 [14.0][MIG] delivery_carrier_partner
  delivery_carrier_partner/README.rst
  delivery_carrier_partner/__init__.py
  delivery_carrier_partner/__manifest__.py
  delivery_carrier_partner/i18n/delivery_carrier_partner.pot
  delivery_carrier_partner/i18n/it.po
  delivery_carrier_partner/models/__init__.py
  delivery_carrier_partner/models/delivery_carrier.py
  delivery_carrier_partner/readme/CONTRIBUTORS.rst
  delivery_carrier_partner/readme/DESCRIPTION.rst
  delivery_carrier_partner/static/description/icon.png
  delivery_carrier_partner/static/description/index.html
  delivery_carrier_partner/views/delivery_carrier_views.xml
  setup/delivery_carrier_partner/odoo/addons/delivery_carrier_partner
  setup/delivery_carrier_partner/setup.py
Labels: approved, bot is merging ⏳

#425 [14.0][MIG] stock_picking_carrier_from_rule: Migration to 14.0
  setup/stock_picking_carrier_from_rule/odoo/addons/stock_picking_carrier_from_rule
  setup/stock_picking_carrier_from_rule/setup.py
  stock_picking_carrier_from_rule/README.rst
  stock_picking_carrier_from_rule/__init__.py
  stock_picking_carrier_from_rule/__manifest__.py
  stock_picking_carrier_from_rule/i18n/stock_picking_carrier_from_rule.pot
  stock_picking_carrier_from_rule/models/__init__.py
  stock_picking_carrier_from_rule/models/stock_move.py
  stock_picking_carrier_from_rule/readme/CONTRIBUTORS.rst
  stock_picking_carrier_from_rule/readme/CREDITS.rst
  stock_picking_carrier_from_rule/readme/DESCRIPTION.rst
  stock_picking_carrier_from_rule/readme/ROADMAP.rst
  stock_picking_carrier_from_rule/static/description/icon.png
  stock_picking_carrier_from_rule/static/description/index.html
Labels: approved, migration, ready to merge, bot is merging ⏳

#431 [14.0][FW] delivery_package_fee: multiple ports from 13.0
  delivery_package_fee/models/delivery_carrier.py
  delivery_package_fee/models/delivery_package_fee.py
  delivery_package_fee/models/sale_order.py
  delivery_package_fee/models/sale_order_line.py
  delivery_package_fee/models/stock_picking.py
  delivery_package_fee/views/delivery_carrier_views.xml
Labels: bug, bot is merging ⏳

#430 [13.0][REF] delivery_ups_oca: Code refactor.
  delivery_ups_oca/i18n/delivery_ups_oca.pot
  delivery_ups_oca/models/delivery_carrier.py
  delivery_ups_oca/models/ups_request.py
Labels: approved, bot is merging ⏳

#440 [13.0][FIX] delivery_auto_refresh: Fix error when adding products to cart on website
  delivery_auto_refresh/models/sale_order.py
Labels: approved, bot is merging ⏳

#433 [12.0][IMP] delivery_carrier_label_ups: split of methods
  delivery_carrier_label_ups/models/carrier_account.py
  delivery_carrier_label_ups/models/stock_picking.py
  delivery_carrier_label_ups/tests/test_delivery_carrier_label_ups.py
  delivery_carrier_label_ups/views/carrier_account.xml
Labels: approved, ready to merge, bot is merging ⏳

#426 [14.0][ADD] partner_default_delivery_carrier
  partner_default_delivery_carrier/__init__.py
  partner_default_delivery_carrier/__manifest__.py
  partner_default_delivery_carrier/models/__init__.py
  partner_default_delivery_carrier/models/res_config_settings.py
  partner_default_delivery_carrier/readme/CONFIGURE.rst
  partner_default_delivery_carrier/readme/CONTRIBUTORS.rst
  partner_default_delivery_carrier/readme/DESCRIPTION.rst
  partner_default_delivery_carrier/static/description/icon.png
  partner_default_delivery_carrier/tests/__init__.py
  partner_default_delivery_carrier/tests/test_default_delivery_carrier.py
  partner_default_delivery_carrier/views/res_config_settings.xml
  setup/partner_default_delivery_carrier/odoo/addons/partner_default_delivery_carrier
  setup/partner_default_delivery_carrier/setup.py
Labels: approved, bot is merging ⏳

#381 [14.0][ADD] delivery_carrier_location
  delivery_carrier_location/__init__.py
  delivery_carrier_location/__manifest__.py
  delivery_carrier_location/models/__init__.py
  delivery_carrier_location/models/delivery_carrier.py
  delivery_carrier_location/readme/CONTRIBUTORS.rst
  delivery_carrier_location/readme/DESCRIPTION.rst
  delivery_carrier_location/tests/__init__.py
  delivery_carrier_location/tests/test_delivery_carrier_location.py
  delivery_carrier_location/views/delivery_carrier.xml
  oca_dependencies.txt
  setup/delivery_carrier_location/odoo/addons/delivery_carrier_location
  setup/delivery_carrier_location/setup.py
Labels: needs review, bot is merging ⏳
