Repository OCA/delivery-carrier, pull requests merged in 2021-03, with the labels that each got.

#339 [13.0][MIG] delivery_package_number: Migration to 13.0
  delivery_package_number/README.rst
  delivery_package_number/__init__.py
  delivery_package_number/__manifest__.py
  delivery_package_number/i18n/delivery_package_number.pot
  delivery_package_number/i18n/es.po
  delivery_package_number/i18n/sl.po
  delivery_package_number/models/__init__.py
  delivery_package_number/models/stock_picking.py
  delivery_package_number/readme/CONTRIBUTORS.rst
  delivery_package_number/readme/DESCRIPTION.rst
  delivery_package_number/readme/USAGE.rst
  delivery_package_number/static/description/icon.png
  delivery_package_number/static/description/index.html
  delivery_package_number/tests/__init__.py
  delivery_package_number/tests/test_delivery_package_number.py
  delivery_package_number/views/stock_picking_views.xml
  delivery_package_number/wizard/__init__.py
  delivery_package_number/wizard/stock_immediate_transfer_views.xml
  delivery_package_number/wizard/stock_inmediate_transfer.py
  setup/delivery_package_number/odoo/addons/delivery_package_number
  setup/delivery_package_number/setup.py
Labels: bot is merging ⏳

#290 [IMP] partner_delivery_zone: Sync delivery zone between order and picking
  partner_delivery_zone/models/sale_order.py
  partner_delivery_zone/models/stock_picking.py
  partner_delivery_zone/tests/test_partner_delivery_zone.py
Labels: approved, bot is merging ⏳, ready to merge

#325 [12.0][IMP] generate labels for all packages in stock picking
  delivery_carrier_label_postlogistics/models/stock.py
  delivery_carrier_label_postlogistics/postlogistics/web_service.py
Labels: approved, bot is merging ⏳, ready to merge

#279 [13.0] Add delivery_carrier_pricelist
  delivery_carrier_pricelist/__init__.py
  delivery_carrier_pricelist/__manifest__.py
  delivery_carrier_pricelist/models/__init__.py
  delivery_carrier_pricelist/models/delivery_carrier.py
  delivery_carrier_pricelist/models/stock_picking.py
  delivery_carrier_pricelist/readme/CONTRIBUTORS.rst
  delivery_carrier_pricelist/readme/DESCRIPTION.rst
  delivery_carrier_pricelist/tests/__init__.py
  delivery_carrier_pricelist/tests/test_delivery_pricelist.py
  delivery_carrier_pricelist/wizards/__init__.py
  delivery_carrier_pricelist/wizards/choose_delivery_carrier.py
  setup/delivery_carrier_pricelist/odoo/addons/delivery_carrier_pricelist
  setup/delivery_carrier_pricelist/setup.py
Labels: approved, bot is merging ⏳, needs review

#335 [10.0] delivery_dropoff_site : add inherit on onchange_partner_shipping_id
  base_delivery_carrier_label/wizard/manifest_wizard.py
  delivery_carrier_category/security/delivery_carrier_category.xml
  delivery_carrier_category/views/delivery_carrier_category.xml
  delivery_carrier_default_tracking_url/__manifest__.py
  delivery_carrier_deposit/models/deposit_slip.py
  delivery_carrier_label_postlogistics/patches/suds_recursion_patch.py
  delivery_carrier_label_postlogistics/postlogistics/web_service.py
  delivery_dropoff_site/models/sale_order.py
Labels: approved, bot is merging ⏳, enhancement, needs review
