Repository OCA/delivery-carrier, pull requests merged in 2021-01, with the labels that each got.

#328 [IMP] delivery_state: automatic email sending
  delivery_state/__manifest__.py
  delivery_state/data/mail_template.xml
  delivery_state/i18n/delivery_state.pot
  delivery_state/i18n/es.po
  delivery_state/models/__init__.py
  delivery_state/models/res_company.py
  delivery_state/models/res_config_settings.py
  delivery_state/models/stock_picking.py
  delivery_state/readme/CONFIGURE.rst
  delivery_state/readme/USAGE.rst
  delivery_state/tests/test_delivery_state.py
  delivery_state/views/res_config_settings_views.xml
Labels: approved, bot is merging ⏳, enhancement, needs review, ready to merge

#291 [13.0][MIG] delivery_state
  delivery_state/README.rst
  delivery_state/__init__.py
  delivery_state/__manifest__.py
  delivery_state/data/ir_cron_data.xml
  delivery_state/i18n/delivery_state.pot
  delivery_state/i18n/es.po
  delivery_state/models/__init__.py
  delivery_state/models/delivery_carrier.py
  delivery_state/models/stock_picking.py
  delivery_state/readme/CONFIGURE.rst
  delivery_state/readme/CONTRIBUTORS.rst
  delivery_state/readme/DESCRIPTION.rst
  delivery_state/readme/USAGE.rst
  delivery_state/static/description/icon.png
  delivery_state/static/description/index.html
  delivery_state/tests/__init__.py
  delivery_state/tests/test_delivery_state.py
  delivery_state/views/stock_picking_views.xml
  setup/delivery_state/odoo/addons/delivery_state
  setup/delivery_state/setup.py
Labels: approved, bot is merging ⏳, migration, needs review

#329 [13.0] [MIG] delivery_multi_destination: Migration to v13.0
  delivery_multi_destination/README.rst
  delivery_multi_destination/__init__.py
  delivery_multi_destination/__manifest__.py
  delivery_multi_destination/demo/delivery_carrier_demo.xml
  delivery_multi_destination/i18n/cs_CZ.po
  delivery_multi_destination/i18n/de.po
  delivery_multi_destination/i18n/delivery_multi_destination.pot
  delivery_multi_destination/i18n/es.po
  delivery_multi_destination/i18n/fr.po
  delivery_multi_destination/i18n/it.po
  delivery_multi_destination/i18n/nl.po
  delivery_multi_destination/i18n/nl_NL.po
  delivery_multi_destination/i18n/pt_BR.po
  delivery_multi_destination/i18n/sl.po
  delivery_multi_destination/i18n/zh_CN.po
  delivery_multi_destination/models/__init__.py
  delivery_multi_destination/models/delivery_carrier.py
  delivery_multi_destination/readme/CONFIGURE.rst
  delivery_multi_destination/readme/CONTRIBUTORS.rst
  delivery_multi_destination/readme/DESCRIPTION.rst
  delivery_multi_destination/readme/ROADMAP.rst
  delivery_multi_destination/readme/USAGE.rst
  delivery_multi_destination/static/description/icon.png
  delivery_multi_destination/static/description/index.html
  delivery_multi_destination/tests/__init__.py
  delivery_multi_destination/tests/test_delivery_multi_destination.py
  delivery_multi_destination/views/delivery_carrier_view.xml
  setup/delivery_multi_destination/odoo/addons/delivery_multi_destination
  setup/delivery_multi_destination/setup.py
Labels: bot is merging ⏳
