Repository OCA/delivery-carrier, pull requests merged in 2021-04, with the labels that each got.

#282 [13.0] Add delivery_package_fee
  delivery_package_fee/__init__.py
  delivery_package_fee/__manifest__.py
  delivery_package_fee/models/__init__.py
  delivery_package_fee/models/delivery_carrier.py
  delivery_package_fee/models/delivery_package_fee.py
  delivery_package_fee/models/sale_order.py
  delivery_package_fee/models/sale_order_line.py
  delivery_package_fee/models/stock_picking.py
  delivery_package_fee/readme/CONFIGURE.rst
  delivery_package_fee/readme/CONTRIBUTORS.rst
  delivery_package_fee/readme/DESCRIPTION.rst
  delivery_package_fee/security/ir.model.access.csv
  delivery_package_fee/tests/__init__.py
  delivery_package_fee/tests/test_package_fee.py
  delivery_package_fee/views/delivery_carrier_views.xml
  setup/delivery_package_fee/odoo/addons/delivery_package_fee
  setup/delivery_package_fee/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#351 [13.0] Add server_environment_delivery
  oca_dependencies.txt
  server_environment_delivery/README.rst
  server_environment_delivery/__init__.py
  server_environment_delivery/__manifest__.py
  server_environment_delivery/models/__init__.py
  server_environment_delivery/models/delivery_carrier.py
  server_environment_delivery/readme/CONFIGURE.rst
  server_environment_delivery/readme/CONTRIBUTORS.rst
  server_environment_delivery/readme/DESCRIPTION.rst
  server_environment_delivery/static/description/index.html
  setup/server_environment_delivery/odoo/addons/server_environment_delivery
  setup/server_environment_delivery/setup.py
Labels: approved, bot is merging ⏳

#356 [13.0][FIX] delivery_postlogistics: avoid duplication of labels
  delivery_postlogistics/models/stock_picking.py
Labels: bot is merging ⏳

#327 [13.0][ADD] delivery_postlogistics_server_env
  delivery_postlogistics_server_env/__init__.py
  delivery_postlogistics_server_env/__manifest__.py
  delivery_postlogistics_server_env/models/__init__.py
  delivery_postlogistics_server_env/models/delivery_carrier.py
  delivery_postlogistics_server_env/readme/CONTRIBUTORS.rst
  delivery_postlogistics_server_env/readme/DESCRIPTION.rst
Labels: approved, bot is merging ⏳

#354 [13.0][ADD] New module 'stock_picking_delivery_link'
  setup/stock_picking_delivery_link/odoo/addons/stock_picking_delivery_link
  setup/stock_picking_delivery_link/setup.py
  stock_picking_delivery_link/README.rst
  stock_picking_delivery_link/__init__.py
  stock_picking_delivery_link/__manifest__.py
  stock_picking_delivery_link/models/__init__.py
  stock_picking_delivery_link/models/stock_picking.py
  stock_picking_delivery_link/readme/CONTRIBUTORS.rst
  stock_picking_delivery_link/readme/DESCRIPTION.rst
  stock_picking_delivery_link/static/description/index.html
  stock_picking_delivery_link/tests/__init__.py
  stock_picking_delivery_link/tests/common.py
  stock_picking_delivery_link/tests/test_delivery_link.py
  stock_picking_delivery_link/views/stock_picking.xml
Labels: approved, bot is merging ⏳, needs review

#357 [13.0][IMP] delivery_postlogistics: add pack_weight parameter on _prepare_attributes
  delivery_postlogistics/postlogistics/web_service.py
Labels: approved, bot is merging ⏳

#355 [13.0][ADD] Send delivery notification from any operation
  delivery_send_to_shipper_at_operation/README.rst
  delivery_send_to_shipper_at_operation/__init__.py
  delivery_send_to_shipper_at_operation/__manifest__.py
  delivery_send_to_shipper_at_operation/models/__init__.py
  delivery_send_to_shipper_at_operation/models/delivery_carrier.py
  delivery_send_to_shipper_at_operation/models/stock_picking.py
  delivery_send_to_shipper_at_operation/readme/CONTRIBUTORS.rst
  delivery_send_to_shipper_at_operation/readme/DESCRIPTION.rst
  delivery_send_to_shipper_at_operation/readme/ROADMAP.rst
  delivery_send_to_shipper_at_operation/readme/USAGE.rst
  delivery_send_to_shipper_at_operation/static/description/delivery_carrier1.png
  delivery_send_to_shipper_at_operation/static/description/delivery_carrier2.png
  delivery_send_to_shipper_at_operation/static/description/index.html
  delivery_send_to_shipper_at_operation/tests/__init__.py
  delivery_send_to_shipper_at_operation/tests/test_send_to_shipper.py
  delivery_send_to_shipper_at_operation/views/delivery_carrier.xml
  delivery_send_to_shipper_at_operation/views/stock_picking.xml
  setup/delivery_send_to_shipper_at_operation/odoo/addons/delivery_send_to_shipper_at_operation
  setup/delivery_send_to_shipper_at_operation/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#311 [12.0] postlogistics - Fix writing of tracking_number
  base_delivery_carrier_label/models/stock_picking.py
  delivery_carrier_label_postlogistics/models/stock.py
  delivery_carrier_label_postlogistics/tests/test_postlogistics.py
Labels: bot is merging ⏳

#337 [MIG] delivery_package_fee: Migration to 14.0
  delivery_package_fee/README.rst
  delivery_package_fee/__init__.py
  delivery_package_fee/__manifest__.py
  delivery_package_fee/models/__init__.py
  delivery_package_fee/models/delivery_carrier.py
  delivery_package_fee/models/delivery_package_fee.py
  delivery_package_fee/models/sale_order.py
  delivery_package_fee/models/sale_order_line.py
  delivery_package_fee/models/stock_picking.py
  delivery_package_fee/readme/CONFIGURE.rst
  delivery_package_fee/readme/CONTRIBUTORS.rst
  delivery_package_fee/readme/DESCRIPTION.rst
  delivery_package_fee/security/ir.model.access.csv
  delivery_package_fee/static/description/index.html
  delivery_package_fee/tests/__init__.py
  delivery_package_fee/tests/test_package_fee.py
  delivery_package_fee/views/delivery_carrier_views.xml
  setup/delivery_package_fee/odoo/addons/delivery_package_fee
  setup/delivery_package_fee/setup.py
Labels: approved, bot is merging ⏳, migration, needs review

#364 [13.0][FIX] partner_delivery_zone: Restore missing commits from v12
  partner_delivery_zone/models/partner_delivery_zone.py
  partner_delivery_zone/models/stock_move.py
  partner_delivery_zone/tests/test_partner_delivery_zone.py
Labels: approved, bot is merging ⏳

#362 [13.0] [MIG] delivery_auto_refresh: Migration to v13
  delivery_auto_refresh/README.rst
  delivery_auto_refresh/__init__.py
  delivery_auto_refresh/__manifest__.py
  delivery_auto_refresh/data/ir_config_parameter.xml
  delivery_auto_refresh/i18n/ca.po
  delivery_auto_refresh/i18n/cs_CZ.po
  delivery_auto_refresh/i18n/de.po
  delivery_auto_refresh/i18n/delivery_auto_refresh.pot
  delivery_auto_refresh/i18n/el_GR.po
  delivery_auto_refresh/i18n/es.po
  delivery_auto_refresh/i18n/es_ES.po
  delivery_auto_refresh/i18n/es_VE.po
  delivery_auto_refresh/i18n/fi.po
  delivery_auto_refresh/i18n/fr.po
  delivery_auto_refresh/i18n/gl.po
  delivery_auto_refresh/i18n/hr.po
  delivery_auto_refresh/i18n/hr_HR.po
  delivery_auto_refresh/i18n/hu.po
  delivery_auto_refresh/i18n/it.po
  delivery_auto_refresh/i18n/nl.po
  delivery_auto_refresh/i18n/nl_NL.po
  delivery_auto_refresh/i18n/pt.po
  delivery_auto_refresh/i18n/pt_BR.po
  delivery_auto_refresh/i18n/ro.po
  delivery_auto_refresh/i18n/sl.po
  delivery_auto_refresh/i18n/tr.po
  delivery_auto_refresh/i18n/tr_TR.po
  delivery_auto_refresh/i18n/vi_VN.po
  delivery_auto_refresh/i18n/zh_CN.po
  delivery_auto_refresh/models/__init__.py
  delivery_auto_refresh/models/sale_order.py
  delivery_auto_refresh/models/stock_picking.py
  delivery_auto_refresh/readme/CONFIGURE.rst
  delivery_auto_refresh/readme/CONTRIBUTORS.rst
  delivery_auto_refresh/readme/DESCRIPTION.rst
  delivery_auto_refresh/readme/ROADMAP.rst
  delivery_auto_refresh/static/description/icon.png
  delivery_auto_refresh/static/description/index.html
  delivery_auto_refresh/tests/__init__.py
  delivery_auto_refresh/tests/test_delivery_auto_refresh.py
  delivery_auto_refresh/views/sale_order_views.xml
  setup/delivery_auto_refresh/odoo/addons/delivery_auto_refresh
  setup/delivery_auto_refresh/setup.py
Labels: bot is merging ⏳
