Repository OCA/delivery-carrier, pull requests merged in 2021-09, with the labels that each got.

#408 [12.0][MIG] delivery_price_rule_untaxed
  delivery_price_rule_untaxed/README.rst
  delivery_price_rule_untaxed/__init__.py
  delivery_price_rule_untaxed/__manifest__.py
  delivery_price_rule_untaxed/data/delivery_price_rule_untaxed_demo.xml
  delivery_price_rule_untaxed/i18n/delivery_price_rule_untaxed.pot
  delivery_price_rule_untaxed/i18n/fr.po
  delivery_price_rule_untaxed/i18n/it.po
  delivery_price_rule_untaxed/models/__init__.py
  delivery_price_rule_untaxed/models/delivery_carrier.py
  delivery_price_rule_untaxed/models/delivery_price_rule.py
  delivery_price_rule_untaxed/readme/CONTRIBUTORS.rst
  delivery_price_rule_untaxed/readme/DESCRIPTION.rst
  delivery_price_rule_untaxed/static/description/icon.png
  delivery_price_rule_untaxed/static/description/index.html
  delivery_price_rule_untaxed/tests/__init__.py
  delivery_price_rule_untaxed/tests/test_delivery_price_rule_untaxed.py
Labels: needs review, approved, migration, bot is merging ⏳

#414 [FIX] delivery_price_method: method permissions
  delivery_price_method/models/delivery_carrier.py
Labels: bot is merging ⏳

#394 [13.0][FIX TRAD] partner_delivery_zone - french translation was not taken into account
  partner_delivery_zone/i18n/fr.po
Labels: enhancement, approved, ready to merge, bot is merging ⏳

#406 [UPD] Also update service level on stock.picking
  delivery_carrier_service_level/models/stock_picking.py
Labels: approved, ready to merge, bot is merging ⏳

#375 [14][base_delivery_carrier_label]Allow to have multiple carrier accounts for a same delivery type
  base_delivery_carrier_label/models/carrier_account.py
  base_delivery_carrier_label/models/stock_picking.py
  base_delivery_carrier_label/tests/test_helper_functions.py
  base_delivery_carrier_label/views/carrier_account.xml
Labels: approved, bot is merging ⏳

#403 [14.0][MIG] delivery_carrier_category
  delivery_carrier_category/README.rst
  delivery_carrier_category/__init__.py
  delivery_carrier_category/__manifest__.py
  delivery_carrier_category/data/delivery_carrier_category.xml
  delivery_carrier_category/i18n/delivery_carrier_category.pot
  delivery_carrier_category/models/__init__.py
  delivery_carrier_category/models/delivery_carrier.py
  delivery_carrier_category/models/delivery_carrier_category.py
  delivery_carrier_category/readme/CONTRIBUTORS.rst
  delivery_carrier_category/readme/DESCRIPTION.rst
  delivery_carrier_category/readme/USAGE.rst
  delivery_carrier_category/security/delivery_carrier_category.xml
  delivery_carrier_category/static/description/icon.png
  delivery_carrier_category/static/description/index.html
  delivery_carrier_category/tests/__init__.py
  delivery_carrier_category/tests/test_carrier_category.py
  delivery_carrier_category/views/delivery_carrier.xml
  delivery_carrier_category/views/delivery_carrier_category.xml
  setup/delivery_carrier_category/odoo/addons/delivery_carrier_category
  setup/delivery_carrier_category/setup.py
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#411 [14.0] [MIG] delivery_free_fee_removal
  delivery_free_fee_removal/README.rst
  delivery_free_fee_removal/__init__.py
  delivery_free_fee_removal/__manifest__.py
  delivery_free_fee_removal/i18n/delivery_free_fee_removal.pot
  delivery_free_fee_removal/i18n/es.po
  delivery_free_fee_removal/models/__init__.py
  delivery_free_fee_removal/models/sale_order.py
  delivery_free_fee_removal/models/sale_order_line.py
  delivery_free_fee_removal/readme/CONTRIBUTORS.rst
  delivery_free_fee_removal/readme/CREDITS.rst
  delivery_free_fee_removal/readme/DESCRIPTION.rst
  delivery_free_fee_removal/reports/sale_report_templates.xml
  delivery_free_fee_removal/static/description/icon.png
  delivery_free_fee_removal/static/description/index.html
  delivery_free_fee_removal/tests/__init__.py
  delivery_free_fee_removal/tests/test_delivery_free_fee_removal.py
  delivery_free_fee_removal/views/sale_order_views.xml
  setup/delivery_free_fee_removal/odoo/addons/delivery_free_fee_removal
  setup/delivery_free_fee_removal/setup.py
Labels: needs review, migration, bot is merging ⏳

#417 [13.0][ADD] stock_picking_carrier_from_rule
  stock_picking_carrier_from_rule/__init__.py
  stock_picking_carrier_from_rule/__manifest__.py
  stock_picking_carrier_from_rule/models/__init__.py
  stock_picking_carrier_from_rule/models/stock_move.py
  stock_picking_carrier_from_rule/readme/CONTRIBUTORS.rst
  stock_picking_carrier_from_rule/readme/DESCRIPTION.rst
  stock_picking_carrier_from_rule/readme/ROADMAP.rst
Labels: approved, bot is merging ⏳
