Repository OCA/delivery-carrier, pull requests merged in 2021-10, with the labels that each got.

#421 [13.0][FIX] delivery_ups_oca: Prevent error when convert price in different currency
  delivery_ups_oca/models/delivery_carrier.py
  delivery_ups_oca/models/ups_request.py
  delivery_ups_oca/tests/test_delivery_ups.py
Labels: approved, bot is merging ⏳

#416 [12.0][IMP] delivery_carrier_label_paazl: removed description sent to carrier
  delivery_carrier_label_paazl/models/stock_picking.py
Labels: approved, ready to merge, bot is merging ⏳

#423 [14.0][MIG] delivery_send_to_shipper_at_operation: Migration to 14.0
  delivery_send_to_shipper_at_operation/README.rst
  delivery_send_to_shipper_at_operation/__init__.py
  delivery_send_to_shipper_at_operation/__manifest__.py
  delivery_send_to_shipper_at_operation/i18n/delivery_send_to_shipper_at_operation.pot
  delivery_send_to_shipper_at_operation/models/__init__.py
  delivery_send_to_shipper_at_operation/models/delivery_carrier.py
  delivery_send_to_shipper_at_operation/models/stock_picking.py
  delivery_send_to_shipper_at_operation/readme/CONTRIBUTORS.rst
  delivery_send_to_shipper_at_operation/readme/CREDITS.rst
  delivery_send_to_shipper_at_operation/readme/DESCRIPTION.rst
  delivery_send_to_shipper_at_operation/readme/ROADMAP.rst
  delivery_send_to_shipper_at_operation/readme/USAGE.rst
  delivery_send_to_shipper_at_operation/static/description/delivery_carrier1.png
  delivery_send_to_shipper_at_operation/static/description/delivery_carrier2.png
  delivery_send_to_shipper_at_operation/static/description/icon.png
  delivery_send_to_shipper_at_operation/static/description/index.html
  delivery_send_to_shipper_at_operation/tests/__init__.py
  delivery_send_to_shipper_at_operation/tests/test_send_to_shipper.py
  delivery_send_to_shipper_at_operation/views/delivery_carrier.xml
  delivery_send_to_shipper_at_operation/views/stock_picking.xml
  setup/delivery_send_to_shipper_at_operation/odoo/addons/delivery_send_to_shipper_at_operation
  setup/delivery_send_to_shipper_at_operation/setup.py
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳
