Repository OCA/delivery-carrier, pull requests merged in 2021-05, with the labels that each got.

#183 [10.0] delivery_carrier_label_postlogistics: inverse addresses on incoming shipments
  delivery_carrier_label_postlogistics/postlogistics/web_service.py
  delivery_carrier_label_postlogistics/views/stock.xml
Labels: approved, bot is merging ⏳, enhancement, ready to merge

#285 [ADD] Module to manage carrier service levels
  delivery_carrier_service_level/README.rst
  delivery_carrier_service_level/__init__.py
  delivery_carrier_service_level/__manifest__.py
  delivery_carrier_service_level/models/__init__.py
  delivery_carrier_service_level/models/carrier_service_level.py
  delivery_carrier_service_level/models/stock_picking.py
  delivery_carrier_service_level/readme/CONFIGURE.rst
  delivery_carrier_service_level/readme/CONTRIBUTORS.rst
  delivery_carrier_service_level/readme/DESCRIPTION.rst
  delivery_carrier_service_level/readme/USAGE.rst
  delivery_carrier_service_level/security/ir.model.access.csv
  delivery_carrier_service_level/static/description/icon.png
  delivery_carrier_service_level/static/description/index.html
  delivery_carrier_service_level/views/carrier_service_level.xml
  delivery_carrier_service_level/views/stock_picking.xml
Labels: approved, bot is merging ⏳, needs review

#366 [13.0][FIX] delivery_postlogistics: several fixes
  delivery_postlogistics/__manifest__.py
  delivery_postlogistics/i18n/delivery_postlogistics.pot
  delivery_postlogistics/models/delivery_carrier.py
  delivery_postlogistics/models/postlogistics_carrier_template_options.py
  delivery_postlogistics/models/postlogistics_shipping_label.py
  delivery_postlogistics/models/product_packaging.py
  delivery_postlogistics/models/res_partner.py
  delivery_postlogistics/models/stock_picking.py
  delivery_postlogistics/models/stock_quant_package.py
  delivery_postlogistics/postlogistics/web_service.py
  delivery_postlogistics/readme/CONFIGURE.rst
  delivery_postlogistics/readme/INSTALL.rst
  delivery_postlogistics/views/delivery.xml
  delivery_postlogistics/views/postlogistics_license.xml
  delivery_postlogistics/views/product_packaging.xml
Labels: approved, bot is merging ⏳

#361 [13.0][FIX] delivery_package_fee: flag order lines
  delivery_package_fee/models/delivery_carrier.py
  delivery_package_fee/models/delivery_package_fee.py
  delivery_package_fee/models/sale_order_line.py
  delivery_package_fee/views/delivery_carrier_views.xml
Labels: approved, bot is merging ⏳, ready to merge

#368 [13.0][IMP]delivery_auto_refresh: prevent warning decoration after refresh
  delivery_auto_refresh/models/sale_order.py
Labels: approved, bot is merging ⏳

#352 [12.0][RFR] carrier label tests: extract Test classes from Case classes for easier overriding
  base_delivery_carrier_label/tests/carrier_label_case.py
  delivery_carrier_label_paazl/models/stock_picking.py
  delivery_carrier_label_paazl/tests/test_delivery_carrier_label_paazl.py
  delivery_carrier_label_ups/tests/test_delivery_carrier_label_ups.py
Labels: approved, bot is merging ⏳, needs review, ready to merge

#346 [12.0][FIX] delivery_carrier_label_paazl: Typo PAZZL
  delivery_carrier_label_paazl/data/delivery_carrier.xml
Labels: approved, bot is merging ⏳, ready to merge

#369 [13.0][FIX] delivery_auto_refresh: Error on test
  delivery_auto_refresh/tests/test_delivery_auto_refresh.py
Labels: approved, bot is merging ⏳
