Repository OCA/delivery-carrier, pull requests merged in 2022-03, with the labels that each got.

#467 [FIX] delivery_auto_refresh: avoid singleton
  delivery_auto_refresh/models/sale_order.py
Labels: approved, bot is merging ⏳

#442 [14.0] Fix carrier account intercompany security rule
  base_delivery_carrier_label/security/carrier_security.xml
Labels: enhancement, approved, bot is merging ⏳

#468 [14.0][MIG] delivery_carrier_label_batch - Migration to 14.0
  delivery_carrier_label_batch/README.rst
  delivery_carrier_label_batch/__init__.py
  delivery_carrier_label_batch/__manifest__.py
  delivery_carrier_label_batch/data/ir.config_parameter.xml
  delivery_carrier_label_batch/i18n/de.po
  delivery_carrier_label_batch/i18n/delivery_carrier_label_batch.pot
  delivery_carrier_label_batch/i18n/fr.po
  delivery_carrier_label_batch/models/__init__.py
  delivery_carrier_label_batch/models/stock_batch_picking.py
  delivery_carrier_label_batch/pdf_utils.py
  delivery_carrier_label_batch/readme/CONFIGURE.rst
  delivery_carrier_label_batch/readme/CONTRIBUTORS.rst
  delivery_carrier_label_batch/readme/CREDITS.rst
  delivery_carrier_label_batch/readme/DESCRIPTION.rst
  delivery_carrier_label_batch/readme/USAGE.rst
  delivery_carrier_label_batch/security/ir.model.access.csv
  delivery_carrier_label_batch/static/description/icon.png
  delivery_carrier_label_batch/static/description/index.html
  delivery_carrier_label_batch/tests/__init__.py
  delivery_carrier_label_batch/tests/dummy.pdf
  delivery_carrier_label_batch/tests/test_generate_labels.py
  delivery_carrier_label_batch/views/stock_batch_picking.xml
  delivery_carrier_label_batch/wizard/__init__.py
  delivery_carrier_label_batch/wizard/apply_carrier.py
  delivery_carrier_label_batch/wizard/apply_carrier_view.xml
  delivery_carrier_label_batch/wizard/generate_labels.py
  delivery_carrier_label_batch/wizard/generate_labels_view.xml
  delivery_carrier_label_batch/zpl_utils.py
  requirements.txt
  setup/delivery_carrier_label_batch/odoo/addons/delivery_carrier_label_batch
  setup/delivery_carrier_label_batch/setup.py
Labels: needs review, approved, migration, bot is merging ⏳

#469 [FIX] delivery_auto_refresh: don't allow to pick a not allowed carrier
  delivery_auto_refresh/models/sale_order.py
  delivery_auto_refresh/views/sale_order_views.xml
Labels: bot is merging ⏳

#451 [14.0][MIG] base_delivery_carrier_label: port pr from 12.0 to 14.0
  base_delivery_carrier_label/models/delivery_carrier_option.py
  base_delivery_carrier_label/tests/carrier_label_case.py
  base_delivery_carrier_label/tests/test_helper_functions.py
  base_delivery_carrier_label/views/delivery.xml
  base_delivery_carrier_label/views/stock.xml
Labels: approved, bot is merging ⏳
