Repository OCA/delivery-carrier, pull requests merged in 2022-12, with the labels that each got.

#542 [15.0][MIG] delivery_multi_destination: Migration to 15.0
  delivery_multi_destination/README.rst
  delivery_multi_destination/__init__.py
  delivery_multi_destination/__manifest__.py
  delivery_multi_destination/demo/delivery_carrier_demo.xml
  delivery_multi_destination/i18n/cs_CZ.po
  delivery_multi_destination/i18n/de.po
  delivery_multi_destination/i18n/delivery_multi_destination.pot
  delivery_multi_destination/i18n/es.po
  delivery_multi_destination/i18n/fr.po
  delivery_multi_destination/i18n/it.po
  delivery_multi_destination/i18n/nl.po
  delivery_multi_destination/i18n/nl_NL.po
  delivery_multi_destination/i18n/pt_BR.po
  delivery_multi_destination/i18n/sl.po
  delivery_multi_destination/i18n/zh_CN.po
  delivery_multi_destination/models/__init__.py
  delivery_multi_destination/models/delivery_carrier.py
  delivery_multi_destination/readme/CONFIGURE.rst
  delivery_multi_destination/readme/CONTRIBUTORS.rst
  delivery_multi_destination/readme/DESCRIPTION.rst
  delivery_multi_destination/readme/ROADMAP.rst
  delivery_multi_destination/readme/USAGE.rst
  delivery_multi_destination/static/description/icon.png
  delivery_multi_destination/static/description/index.html
  delivery_multi_destination/tests/__init__.py
  delivery_multi_destination/tests/test_delivery_multi_destination.py
  delivery_multi_destination/views/delivery_carrier_view.xml
  setup/delivery_multi_destination/odoo/addons/delivery_multi_destination
  setup/delivery_multi_destination/setup.py
Labels: approved, bot is merging ⏳

#571 [16.0][MIG] delivery_carrier_agency
  delivery_carrier_agency/README.rst
  delivery_carrier_agency/__init__.py
  delivery_carrier_agency/__manifest__.py
  delivery_carrier_agency/i18n/delivery_carrier_agency.pot
  delivery_carrier_agency/models/__init__.py
  delivery_carrier_agency/models/delivery_carrier_agency.py
  delivery_carrier_agency/models/stock_picking.py
  delivery_carrier_agency/readme/CONTRIBUTORS.rst
  delivery_carrier_agency/readme/DESCRIPTION.rst
  delivery_carrier_agency/security/ir.model.access.csv
  delivery_carrier_agency/static/description/icon.png
  delivery_carrier_agency/static/description/index.html
  delivery_carrier_agency/tests/__init__.py
  delivery_carrier_agency/tests/test_carrier_agency.py
  delivery_carrier_agency/views/delivery_carrier_agency_view.xml
  setup/delivery_carrier_agency/odoo/addons/delivery_carrier_agency
  setup/delivery_carrier_agency/setup.py
Labels: approved, migration, ready to merge, bot is merging ⏳

#511 [14.0][FIX] delivery_carrier_label_batch: invalid field
  delivery_carrier_label_batch/models/stock_batch_picking.py
Labels: bug, approved, bot is merging ⏳

#577 [13.0][FIX] delivery_tnt_oca: Set correct weight if not using packages
  delivery_tnt_oca/models/tnt_request.py
  delivery_tnt_oca/tests/test_delivery_tnt.py
Labels: bot is merging ⏳

#578 [13.0][FIX] delivery_ups_oca: Fix cancel_shipment method
  delivery_ups_oca/models/ups_request.py
Labels: approved, bot is merging ⏳

#581 [13.0][FIX] delivery_tnt_oca: Set correct dimensions from packages
  delivery_tnt_oca/models/tnt_request.py
Labels: approved, bot is merging ⏳

#586 [15.0][IMP] delivery_state: new state to ignore further update calls
  delivery_state/models/stock_picking.py
Labels: approved, bot is merging ⏳

#582 [13.0][IMP] delivery_tnt_oca: Add the tnt_service_option field in the carrier to send that value to the API.
  delivery_tnt_oca/i18n/delivery_tnt_oca.pot
  delivery_tnt_oca/i18n/es.po
  delivery_tnt_oca/models/delivery_carrier.py
  delivery_tnt_oca/models/tnt_request.py
  delivery_tnt_oca/views/delivery_carrier_view.xml
Labels: approved, bot is merging ⏳

#584 [15.0][IMP] delivery_cttexpress: force delivery_price_method dependency
  delivery_cttexpress/README.rst
  delivery_cttexpress/__manifest__.py
  delivery_cttexpress/models/delivery_carrier.py
  delivery_cttexpress/readme/CONFIGURE.rst
  delivery_cttexpress/readme/INSTALL.rst
  delivery_cttexpress/static/description/index.html
Labels: approved, bot is merging ⏳

#587 [16.0][IMP] delivery_state: new state to ignore further update calls
  delivery_state/models/stock_picking.py
Labels: approved, bot is merging ⏳

#588 [14.0][IMP] delivery_tnt_oca: Add the tnt_service_option field in the carrier to send that value to the API.
  delivery_tnt_oca/i18n/delivery_tnt_oca.pot
  delivery_tnt_oca/i18n/es.po
  delivery_tnt_oca/models/delivery_carrier.py
  delivery_tnt_oca/models/tnt_request.py
  delivery_tnt_oca/views/delivery_carrier_view.xml
Labels: bot is merging ⏳

#589 [16.0][IMP] delivery_cttexpress: force delivery_price_method dependency
  delivery_cttexpress/README.rst
  delivery_cttexpress/__manifest__.py
  delivery_cttexpress/models/delivery_carrier.py
  delivery_cttexpress/readme/CONFIGURE.rst
  delivery_cttexpress/readme/INSTALL.rst
  delivery_cttexpress/static/description/index.html
Labels: approved, bot is merging ⏳

#556 [15.0][IMP] partner_delivery_schedule: Tests more resilient
  partner_delivery_schedule/tests/test_partner_delivery_schedule.py
Labels: approved, bot is merging ⏳

#591 [13.0][IMP] delivery_tnt_oca: Set minimum dimensions of 0.1
  delivery_tnt_oca/models/tnt_request.py
  delivery_tnt_oca/tests/test_delivery_tnt.py
Labels: approved, bot is merging ⏳

#590 [13.0][IMP] delivery_tnt_oca: Remove unnecessary BOOK tag from ACTIVITY
  delivery_tnt_oca/models/tnt_request.py
Labels: approved, bot is merging ⏳

#592 [14.0][IMP] delivery_tnt_oca: Set minimum dimensions of 0.1
  delivery_tnt_oca/models/tnt_request.py
  delivery_tnt_oca/tests/test_delivery_tnt.py
Labels: approved, bot is merging ⏳

#593 [14.0][IMP] delivery_tnt_oca: Remove unnecessary BOOK tag from ACTIVITY
  delivery_tnt_oca/models/tnt_request.py
Labels: bot is merging ⏳
