Repository OCA/delivery-carrier, pull requests merged in 2022-02, with the labels that each got.

#460 [14.0][FIX] delivery_roulier: Fix access right issues when using actions
  delivery_roulier/models/stock_picking.py
Labels: bug, approved, bot is merging ⏳

#463 [13.0][FIX] delivery_price_method: method permissions
  delivery_price_method/models/delivery_carrier.py
Labels: approved, bot is merging ⏳

#269 [10.0][delivery_carrier_label_postlogistics] Street1 printed before S…
  delivery_carrier_label_postlogistics/postlogistics/web_service.py
Labels: enhancement, approved, ready to merge, bot is merging ⏳

#445 [12.0][FIX] delivery_carrier_label_ups: total UPS shipment price
  delivery_carrier_label_ups/models/stock_picking.py
  delivery_carrier_label_ups/tests/test_delivery_carrier_label_ups.py
Labels: approved, ready to merge, bot is merging ⏳
