Repository OCA/delivery-carrier, pull requests merged in 2022-04, with the labels that each got.

#473 [14.0] delivery_auto_refresh: migration to v14
  delivery_auto_refresh/README.rst
  delivery_auto_refresh/__init__.py
  delivery_auto_refresh/__manifest__.py
  delivery_auto_refresh/data/ir_config_parameter.xml
  delivery_auto_refresh/i18n/ca.po
  delivery_auto_refresh/i18n/cs_CZ.po
  delivery_auto_refresh/i18n/de.po
  delivery_auto_refresh/i18n/delivery_auto_refresh.pot
  delivery_auto_refresh/i18n/el_GR.po
  delivery_auto_refresh/i18n/es.po
  delivery_auto_refresh/i18n/es_ES.po
  delivery_auto_refresh/i18n/es_VE.po
  delivery_auto_refresh/i18n/fi.po
  delivery_auto_refresh/i18n/fr.po
  delivery_auto_refresh/i18n/gl.po
  delivery_auto_refresh/i18n/hr.po
  delivery_auto_refresh/i18n/hr_HR.po
  delivery_auto_refresh/i18n/hu.po
  delivery_auto_refresh/i18n/it.po
  delivery_auto_refresh/i18n/nl.po
  delivery_auto_refresh/i18n/nl_NL.po
  delivery_auto_refresh/i18n/pt.po
  delivery_auto_refresh/i18n/pt_BR.po
  delivery_auto_refresh/i18n/ro.po
  delivery_auto_refresh/i18n/sl.po
  delivery_auto_refresh/i18n/tr.po
  delivery_auto_refresh/i18n/tr_TR.po
  delivery_auto_refresh/i18n/vi_VN.po
  delivery_auto_refresh/i18n/zh_CN.po
  delivery_auto_refresh/models/__init__.py
  delivery_auto_refresh/models/sale_order.py
  delivery_auto_refresh/models/stock_picking.py
  delivery_auto_refresh/readme/CONFIGURE.rst
  delivery_auto_refresh/readme/CONTRIBUTORS.rst
  delivery_auto_refresh/readme/DESCRIPTION.rst
  delivery_auto_refresh/readme/ROADMAP.rst
  delivery_auto_refresh/static/description/icon.png
  delivery_auto_refresh/static/description/index.html
  delivery_auto_refresh/tests/__init__.py
  delivery_auto_refresh/tests/test_delivery_auto_refresh.py
  delivery_auto_refresh/utils.py
  delivery_auto_refresh/views/sale_order_views.xml
  setup/delivery_auto_refresh/odoo/addons/delivery_auto_refresh
  setup/delivery_auto_refresh/setup.py
Labels: approved, bot is merging ⏳

#461 [14.0][FIX] delivery_postlogistics: fix split on bool
  delivery_postlogistics/models/product_packaging.py
  delivery_postlogistics/tests/__init__.py
  delivery_postlogistics/tests/test_packaging_code.py
Labels: bug, approved, ready to merge, bot is merging ⏳

#424 [14.0][ADD] delivery_carrier_customer_info
  delivery_carrier_customer_info/__init__.py
  delivery_carrier_customer_info/__manifest__.py
  delivery_carrier_customer_info/models/__init__.py
  delivery_carrier_customer_info/models/res_partner.py
  delivery_carrier_customer_info/models/res_partner_delivery_info.py
  delivery_carrier_customer_info/readme/CONTRIBUTORS.rst
  delivery_carrier_customer_info/readme/DESCRIPTION.rst
  delivery_carrier_customer_info/security/ir.model.access.csv
  delivery_carrier_customer_info/views/menus.xml
  delivery_carrier_customer_info/views/res_partner.xml
  delivery_carrier_customer_info/views/res_partner_delivery_info.xml
  setup/delivery_carrier_customer_info/odoo/addons/delivery_carrier_customer_info
  setup/delivery_carrier_customer_info/setup.py
Labels: needs review, bot is merging ⏳, stale

#474 [ADD] delivery_price_rule_untaxed
  delivery_price_rule_untaxed/README.rst
  delivery_price_rule_untaxed/__init__.py
  delivery_price_rule_untaxed/__manifest__.py
  delivery_price_rule_untaxed/data/delivery_price_rule_untaxed_demo.xml
  delivery_price_rule_untaxed/i18n/delivery_price_rule_untaxed.pot
  delivery_price_rule_untaxed/i18n/fr.po
  delivery_price_rule_untaxed/i18n/it.po
  delivery_price_rule_untaxed/models/__init__.py
  delivery_price_rule_untaxed/models/delivery_carrier.py
  delivery_price_rule_untaxed/models/delivery_price_rule.py
  delivery_price_rule_untaxed/readme/CONTRIBUTORS.rst
  delivery_price_rule_untaxed/readme/DESCRIPTION.rst
  delivery_price_rule_untaxed/static/description/icon.png
  delivery_price_rule_untaxed/static/description/index.html
  delivery_price_rule_untaxed/tests/__init__.py
  delivery_price_rule_untaxed/tests/test_delivery_price_rule_untaxed.py
  setup/delivery_price_rule_untaxed/odoo/addons/delivery_price_rule_untaxed
  setup/delivery_price_rule_untaxed/setup.py
Labels: needs review, approved, migration, bot is merging ⏳

#478 [13.0][IMP] delivery_*: Promote modules to Stable
  delivery_package_number/__manifest__.py
  delivery_price_method/__manifest__.py
  delivery_state/__manifest__.py
  delivery_ups_oca/models/delivery_carrier.py
  delivery_ups_oca/models/ups_request.py
  delivery_ups_oca/tests/test_delivery_ups.py
Labels: bot is merging ⏳

#477 [13.0][ADD] delivery_carrier_multi_zip: Multiple ZIP intervals for the same delivery method
  delivery_carrier_multi_zip/README.rst
  delivery_carrier_multi_zip/__init__.py
  delivery_carrier_multi_zip/__manifest__.py
  delivery_carrier_multi_zip/hooks.py
  delivery_carrier_multi_zip/i18n/delivery_carrier_multi_zip.pot
  delivery_carrier_multi_zip/i18n/es.po
  delivery_carrier_multi_zip/models/__init__.py
  delivery_carrier_multi_zip/models/delivery_carrier.py
  delivery_carrier_multi_zip/readme/CONFIGURE.rst
  delivery_carrier_multi_zip/readme/CONTRIBUTORS.rst
  delivery_carrier_multi_zip/readme/DESCRIPTION.rst
  delivery_carrier_multi_zip/readme/INSTALL.rst
  delivery_carrier_multi_zip/readme/ROADMAP.rst
  delivery_carrier_multi_zip/security/ir.model.access.csv
  delivery_carrier_multi_zip/static/description/icon.png
  delivery_carrier_multi_zip/static/description/index.html
  delivery_carrier_multi_zip/tests/__init__.py
  delivery_carrier_multi_zip/tests/test_delivery_carrier_multi_zip.py
  delivery_carrier_multi_zip/views/delivery_carrier_view.xml
  setup/delivery_carrier_multi_zip/odoo/addons/delivery_carrier_multi_zip
  setup/delivery_carrier_multi_zip/setup.py
Labels: approved, bot is merging ⏳
