Repository OCA/delivery-carrier, pull requests merged in 2022-10, with the labels that each got.

#535 [12.0][FIX] delivery_state: cron
  delivery_state/models/stock_picking.py
Labels: approved, bot is merging ⏳

#532 [15.0][MIG] stock_picking_delivery_link
  setup/stock_picking_delivery_link/odoo/addons/stock_picking_delivery_link
  setup/stock_picking_delivery_link/setup.py
  stock_picking_delivery_link/README.rst
  stock_picking_delivery_link/__init__.py
  stock_picking_delivery_link/__manifest__.py
  stock_picking_delivery_link/i18n/stock_picking_delivery_link.pot
  stock_picking_delivery_link/models/__init__.py
  stock_picking_delivery_link/models/stock_picking.py
  stock_picking_delivery_link/readme/CONTRIBUTORS.rst
  stock_picking_delivery_link/readme/DESCRIPTION.rst
  stock_picking_delivery_link/static/description/icon.png
  stock_picking_delivery_link/static/description/index.html
  stock_picking_delivery_link/tests/__init__.py
  stock_picking_delivery_link/tests/common.py
  stock_picking_delivery_link/tests/test_delivery_link.py
  stock_picking_delivery_link/views/stock_picking.xml
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#481 [14.0] delivery_carrier_label_batch: Allow testing labels generation
  delivery_carrier_label_batch/tests/test_generate_labels.py
  delivery_carrier_label_batch/wizard/generate_labels.py
Labels: approved, bot is merging ⏳

#536 [15.0][MIG] delivery_price_method: Migration to 15.0
  delivery_price_method/README.rst
  delivery_price_method/__init__.py
  delivery_price_method/__manifest__.py
  delivery_price_method/i18n/delivery_price_method.pot
  delivery_price_method/i18n/es.po
  delivery_price_method/i18n/es_CL.po
  delivery_price_method/i18n/es_VE.po
  delivery_price_method/models/__init__.py
  delivery_price_method/models/delivery_carrier.py
  delivery_price_method/readme/CONTRIBUTORS.rst
  delivery_price_method/readme/DESCRIPTION.rst
  delivery_price_method/readme/USAGE.rst
  delivery_price_method/static/description/icon.png
  delivery_price_method/static/description/index.html
  delivery_price_method/tests/__init__.py
  delivery_price_method/tests/test_delivery_price_method.py
  delivery_price_method/views/delivery_carrier_views.xml
  partner_delivery_zone/tests/test_partner_delivery_zone.py
  setup/delivery_price_method/odoo/addons/delivery_price_method
  setup/delivery_price_method/setup.py
Labels: needs review, approved, migration, bot is merging ⏳

#538 [15.0][MIG] partner_delivery_schedule: Migration to 15.0
  partner_delivery_schedule/README.rst
  partner_delivery_schedule/__init__.py
  partner_delivery_schedule/__manifest__.py
  partner_delivery_schedule/i18n/es.po
  partner_delivery_schedule/i18n/nl.po
  partner_delivery_schedule/i18n/partner_delivery_schedule.pot
  partner_delivery_schedule/i18n/zh_CN.po
  partner_delivery_schedule/models/__init__.py
  partner_delivery_schedule/models/partner_delivery_schedule.py
  partner_delivery_schedule/models/res_partner.py
  partner_delivery_schedule/readme/CONTRIBUTORS.rst
  partner_delivery_schedule/readme/DESCRIPTION.rst
  partner_delivery_schedule/readme/USAGE.rst
  partner_delivery_schedule/security/ir.model.access.csv
  partner_delivery_schedule/static/description/icon.png
  partner_delivery_schedule/static/description/index.html
  partner_delivery_schedule/tests/__init__.py
  partner_delivery_schedule/tests/test_partner_delivery_schedule.py
  partner_delivery_schedule/views/partner_delivery_schedule_view.xml
  partner_delivery_schedule/views/report_shipping.xml
  partner_delivery_schedule/views/res_partner_view.xml
  setup/partner_delivery_schedule/odoo/addons/partner_delivery_schedule
  setup/partner_delivery_schedule/setup.py
Labels: approved, bot is merging ⏳

#539 [14.0][MIG] delivery_carrier_multi_zip: Migration to 14.0
  delivery_carrier_multi_zip/README.rst
  delivery_carrier_multi_zip/__init__.py
  delivery_carrier_multi_zip/__manifest__.py
  delivery_carrier_multi_zip/hooks.py
  delivery_carrier_multi_zip/i18n/de.po
  delivery_carrier_multi_zip/i18n/delivery_carrier_multi_zip.pot
  delivery_carrier_multi_zip/i18n/es.po
  delivery_carrier_multi_zip/models/__init__.py
  delivery_carrier_multi_zip/models/delivery_carrier.py
  delivery_carrier_multi_zip/readme/CONFIGURE.rst
  delivery_carrier_multi_zip/readme/CONTRIBUTORS.rst
  delivery_carrier_multi_zip/readme/DESCRIPTION.rst
  delivery_carrier_multi_zip/readme/INSTALL.rst
  delivery_carrier_multi_zip/readme/ROADMAP.rst
  delivery_carrier_multi_zip/security/ir.model.access.csv
  delivery_carrier_multi_zip/static/description/icon.png
  delivery_carrier_multi_zip/static/description/index.html
  delivery_carrier_multi_zip/tests/__init__.py
  delivery_carrier_multi_zip/tests/test_delivery_carrier_multi_zip.py
  delivery_carrier_multi_zip/views/delivery_carrier_view.xml
  setup/delivery_carrier_multi_zip/odoo/addons/delivery_carrier_multi_zip
  setup/delivery_carrier_multi_zip/setup.py
Labels: bot is merging ⏳
