Repository OCA/delivery-carrier, pull requests merged in 2022-06, with the labels that each got.

#454 [14.0][IMP] delivery_correos_express: International deliveries
  delivery_correos_express/models/delivery_carrier.py
Labels: approved, ready to merge, bot is merging ⏳

#495 [13.0][FIX] delivery_ups_oca: Show the errors to avoid the error of access to a non-existing key in the code.
  delivery_ups_oca/models/ups_request.py
  delivery_ups_oca/tests/test_delivery_ups.py
  delivery_ups_oca/views/delivery_carrier_view.xml
Labels: approved, bot is merging ⏳

#498 [13.0][FIX] delivery_tnt_oca: Change to .txt extension to prevent printer incompatibilities.
  delivery_tnt_oca/models/delivery_carrier.py
Labels: approved, bot is merging ⏳

#499 [13.0][IMP] delivery_tnt_oca: Add tnt_last_request log allways.
  delivery_tnt_oca/models/tnt_request.py
  delivery_tnt_oca/views/delivery_carrier_view.xml
Labels: bot is merging ⏳

#484 [14.0][MIG] delivery_tnt_oca: Migration to 14.0
  delivery_tnt_oca/README.rst
  delivery_tnt_oca/__init__.py
  delivery_tnt_oca/__manifest__.py
  delivery_tnt_oca/doc/ExpressConnect/ExpressConnect Pricing Integration Guide v3 Schema.pdf
  delivery_tnt_oca/doc/ExpressConnect/ExpressConnect Shipping Integration Guide v3.pdf
  delivery_tnt_oca/doc/ExpressConnect/ExpressConnect_Tracking_V3_1.pdf
  delivery_tnt_oca/doc/ExpressLabel/ExpressLabel Integration Guide v1.10.pdf
  delivery_tnt_oca/doc/ExpressLabel/ExpressLabel_Integration Guide_Arrangements.pdf
  delivery_tnt_oca/i18n/delivery_tnt_oca.pot
  delivery_tnt_oca/i18n/es.po
  delivery_tnt_oca/models/__init__.py
  delivery_tnt_oca/models/delivery_carrier.py
  delivery_tnt_oca/models/product_packaging.py
  delivery_tnt_oca/models/stock_picking.py
  delivery_tnt_oca/models/tnt_request.py
  delivery_tnt_oca/readme/CONFIGURE.rst
  delivery_tnt_oca/readme/CONTRIBUTORS.rst
  delivery_tnt_oca/readme/DESCRIPTION.rst
  delivery_tnt_oca/readme/ROADMAP.rst
  delivery_tnt_oca/readme/USAGE.rst
  delivery_tnt_oca/report/picking_templates.xml
  delivery_tnt_oca/report/stock_report_views.xml
  delivery_tnt_oca/static/description/icon.png
  delivery_tnt_oca/static/description/index.html
  delivery_tnt_oca/tests/__init__.py
  delivery_tnt_oca/tests/test_delivery_tnt.py
  delivery_tnt_oca/views/delivery_carrier_view.xml
  requirements.txt
  setup/delivery_tnt_oca/odoo/addons/delivery_tnt_oca
  setup/delivery_tnt_oca/setup.py
Labels: needs review, approved, migration, bot is merging ⏳

#500 [14.0][FIX] delivery_tnt_oca: Encode data to utf-8 to prevent error in some cases (Šempas for example)
  delivery_tnt_oca/models/tnt_request.py
Labels: approved, bot is merging ⏳
