Repository OCA/delivery-carrier, pull requests merged in 2022-11, with the labels that each got.

#522 [14.0] Add delivery_carrier_package_measure_required
  delivery_carrier_package_measure_required/__init__.py
  delivery_carrier_package_measure_required/__manifest__.py
  delivery_carrier_package_measure_required/models/__init__.py
  delivery_carrier_package_measure_required/models/product_packaging.py
  delivery_carrier_package_measure_required/models/stock_picking.py
  delivery_carrier_package_measure_required/models/stock_quant_package.py
  delivery_carrier_package_measure_required/readme/CONTRIBUTORS.rst
  delivery_carrier_package_measure_required/readme/DESCRIPTION.rst
  delivery_carrier_package_measure_required/tests/__init__.py
  delivery_carrier_package_measure_required/tests/test_delivery_carrier_package_measure_require.py
  delivery_carrier_package_measure_required/views/product_packaging.xml
  delivery_carrier_package_measure_required/wizard/__init__.py
  delivery_carrier_package_measure_required/wizard/choose_delivery_package.py
  delivery_carrier_package_measure_required/wizard/choose_delivery_package.xml
  setup/delivery_carrier_package_measure_required/odoo/addons/delivery_carrier_package_measure_required
  setup/delivery_carrier_package_measure_required/setup.py
Labels: needs review, approved, ready to merge, bot is merging ⏳

#547 [12.0][FIX+IMP] Use copier template + Switch to GitHub actions
  .copier-answers.yml
  .editorconfig
  .flake8
  .github/workflows/pre-commit.yml
  .github/workflows/stale.yml
  .github/workflows/test.yml
  .gitignore
  .pre-commit-config.yaml
  .pylintrc
  .pylintrc-mandatory
  .travis.yml
  LICENSE
  README.md
  delivery_carrier_info/__manifest__.py
  delivery_carrier_label_batch/__manifest__.py
  delivery_carrier_partner/__manifest__.py
  delivery_price_rule_untaxed/__manifest__.py
  requirements.txt
Labels: bot is merging ⏳

#533 [12.0][ADD] delivery_cttexpress: New module
  delivery_cttexpress/README.rst
  delivery_cttexpress/__init__.py
  delivery_cttexpress/__manifest__.py
  delivery_cttexpress/i18n/delivery_cttexpress.pot
  delivery_cttexpress/i18n/es.po
  delivery_cttexpress/models/__init__.py
  delivery_cttexpress/models/cttexpress_master_data.py
  delivery_cttexpress/models/cttexpress_request.py
  delivery_cttexpress/models/delivery_carrier.py
  delivery_cttexpress/models/stock_picking.py
  delivery_cttexpress/readme/CONFIGURE.rst
  delivery_cttexpress/readme/CONTRIBUTORS.rst
  delivery_cttexpress/readme/CREDITS.rst
  delivery_cttexpress/readme/DESCRIPTION.rst
  delivery_cttexpress/readme/INSTALL.rst
  delivery_cttexpress/readme/ROADMAP.rst
  delivery_cttexpress/readme/USAGE.rst
  delivery_cttexpress/static/description/icon.png
  delivery_cttexpress/static/description/icon.svg
  delivery_cttexpress/static/description/index.html
  delivery_cttexpress/tests/__init__.py
  delivery_cttexpress/tests/test_delivery_cttexpress.py
  delivery_cttexpress/views/delivery_cttexpress_view.xml
  delivery_cttexpress/views/stock_picking_views.xml
  delivery_cttexpress/wizards/__init__.py
  delivery_cttexpress/wizards/cttexpress_manifest_wizard.py
  delivery_cttexpress/wizards/cttexpress_manifest_wizard_views.xml
  delivery_cttexpress/wizards/cttexpress_pickup_wizard.py
  delivery_cttexpress/wizards/cttexpress_pickup_wizard.xml
  setup/delivery_cttexpress/odoo/addons/delivery_cttexpress
  setup/delivery_cttexpress/setup.py
Labels: needs review, approved, ready to merge, bot is merging ⏳

#548 [13.0][MIG] delivery_cttexpress: migration to 13.0
  delivery_cttexpress/README.rst
  delivery_cttexpress/__init__.py
  delivery_cttexpress/__manifest__.py
  delivery_cttexpress/i18n/delivery_cttexpress.pot
  delivery_cttexpress/i18n/es.po
  delivery_cttexpress/models/__init__.py
  delivery_cttexpress/models/cttexpress_master_data.py
  delivery_cttexpress/models/cttexpress_request.py
  delivery_cttexpress/models/delivery_carrier.py
  delivery_cttexpress/models/stock_picking.py
  delivery_cttexpress/readme/CONFIGURE.rst
  delivery_cttexpress/readme/CONTRIBUTORS.rst
  delivery_cttexpress/readme/CREDITS.rst
  delivery_cttexpress/readme/DESCRIPTION.rst
  delivery_cttexpress/readme/INSTALL.rst
  delivery_cttexpress/readme/ROADMAP.rst
  delivery_cttexpress/readme/USAGE.rst
  delivery_cttexpress/static/description/icon.png
  delivery_cttexpress/static/description/icon.svg
  delivery_cttexpress/static/description/index.html
  delivery_cttexpress/tests/__init__.py
  delivery_cttexpress/tests/test_delivery_cttexpress.py
  delivery_cttexpress/views/delivery_cttexpress_view.xml
  delivery_cttexpress/views/stock_picking_views.xml
  delivery_cttexpress/wizards/__init__.py
  delivery_cttexpress/wizards/cttexpress_manifest_wizard.py
  delivery_cttexpress/wizards/cttexpress_manifest_wizard_views.xml
  delivery_cttexpress/wizards/cttexpress_pickup_wizard.py
  delivery_cttexpress/wizards/cttexpress_pickup_wizard.xml
  setup/delivery_cttexpress/odoo/addons/delivery_cttexpress
  setup/delivery_cttexpress/setup.py
Labels: approved, bot is merging ⏳

#549 [14.0][MIG] delivery_cttexpress: migration to 14.0
  delivery_cttexpress/README.rst
  delivery_cttexpress/__init__.py
  delivery_cttexpress/__manifest__.py
  delivery_cttexpress/i18n/delivery_cttexpress.pot
  delivery_cttexpress/i18n/es.po
  delivery_cttexpress/models/__init__.py
  delivery_cttexpress/models/cttexpress_master_data.py
  delivery_cttexpress/models/cttexpress_request.py
  delivery_cttexpress/models/delivery_carrier.py
  delivery_cttexpress/models/stock_picking.py
  delivery_cttexpress/readme/CONFIGURE.rst
  delivery_cttexpress/readme/CONTRIBUTORS.rst
  delivery_cttexpress/readme/CREDITS.rst
  delivery_cttexpress/readme/DESCRIPTION.rst
  delivery_cttexpress/readme/INSTALL.rst
  delivery_cttexpress/readme/ROADMAP.rst
  delivery_cttexpress/readme/USAGE.rst
  delivery_cttexpress/security/ir.model.access.csv
  delivery_cttexpress/static/description/icon.png
  delivery_cttexpress/static/description/icon.svg
  delivery_cttexpress/static/description/index.html
  delivery_cttexpress/tests/__init__.py
  delivery_cttexpress/tests/test_delivery_cttexpress.py
  delivery_cttexpress/views/delivery_cttexpress_view.xml
  delivery_cttexpress/views/stock_picking_views.xml
  delivery_cttexpress/wizards/__init__.py
  delivery_cttexpress/wizards/cttexpress_manifest_wizard.py
  delivery_cttexpress/wizards/cttexpress_manifest_wizard_views.xml
  delivery_cttexpress/wizards/cttexpress_pickup_wizard.py
  delivery_cttexpress/wizards/cttexpress_pickup_wizard.xml
  setup/delivery_cttexpress/odoo/addons/delivery_cttexpress
  setup/delivery_cttexpress/setup.py
Labels: approved, bot is merging ⏳

#550 [15.0][MIG] delivery_cttexpress: Migration to 15.0
  delivery_cttexpress/README.rst
  delivery_cttexpress/__init__.py
  delivery_cttexpress/__manifest__.py
  delivery_cttexpress/i18n/delivery_cttexpress.pot
  delivery_cttexpress/i18n/es.po
  delivery_cttexpress/models/__init__.py
  delivery_cttexpress/models/cttexpress_master_data.py
  delivery_cttexpress/models/cttexpress_request.py
  delivery_cttexpress/models/delivery_carrier.py
  delivery_cttexpress/models/stock_picking.py
  delivery_cttexpress/readme/CONFIGURE.rst
  delivery_cttexpress/readme/CONTRIBUTORS.rst
  delivery_cttexpress/readme/CREDITS.rst
  delivery_cttexpress/readme/DESCRIPTION.rst
  delivery_cttexpress/readme/INSTALL.rst
  delivery_cttexpress/readme/ROADMAP.rst
  delivery_cttexpress/readme/USAGE.rst
  delivery_cttexpress/security/ir.model.access.csv
  delivery_cttexpress/static/description/icon.png
  delivery_cttexpress/static/description/icon.svg
  delivery_cttexpress/static/description/index.html
  delivery_cttexpress/tests/__init__.py
  delivery_cttexpress/tests/test_delivery_cttexpress.py
  delivery_cttexpress/views/delivery_cttexpress_view.xml
  delivery_cttexpress/views/stock_picking_views.xml
  delivery_cttexpress/wizards/__init__.py
  delivery_cttexpress/wizards/cttexpress_manifest_wizard.py
  delivery_cttexpress/wizards/cttexpress_manifest_wizard_views.xml
  delivery_cttexpress/wizards/cttexpress_pickup_wizard.py
  delivery_cttexpress/wizards/cttexpress_pickup_wizard.xml
  requirements.txt
  setup/delivery_cttexpress/odoo/addons/delivery_cttexpress
  setup/delivery_cttexpress/setup.py
Labels: bot is merging ⏳

#553 [16.0][MIG] delivery_package_number: Migration to 16.0
  delivery_package_number/README.rst
  delivery_package_number/__init__.py
  delivery_package_number/__manifest__.py
  delivery_package_number/i18n/delivery_package_number.pot
  delivery_package_number/i18n/es.po
  delivery_package_number/i18n/sl.po
  delivery_package_number/models/__init__.py
  delivery_package_number/models/stock_picking.py
  delivery_package_number/readme/CONTRIBUTORS.rst
  delivery_package_number/readme/DESCRIPTION.rst
  delivery_package_number/readme/USAGE.rst
  delivery_package_number/static/description/icon.png
  delivery_package_number/static/description/index.html
  delivery_package_number/tests/__init__.py
  delivery_package_number/tests/test_delivery_package_number.py
  delivery_package_number/views/stock_picking_views.xml
  delivery_package_number/wizard/__init__.py
  delivery_package_number/wizard/stock_immediate_transfer_views.xml
  delivery_package_number/wizard/stock_inmediate_transfer.py
  setup/delivery_package_number/odoo/addons/delivery_package_number
  setup/delivery_package_number/setup.py
Labels: approved, bot is merging ⏳

#546 [14.0][FIX] delivery_carrier_package_measure_required for not done transfer
  delivery_carrier_package_measure_required/models/stock_quant_package.py
  delivery_carrier_package_measure_required/tests/test_delivery_carrier_package_measure_require.py
Labels: bug, approved, ready to merge, bot is merging ⏳

#552 [13.0][IMP] delivery_price_rule_volumetric_weight: Add highest_weight option.
  delivery_price_rule_volumetric_weight/README.rst
  delivery_price_rule_volumetric_weight/models/delivery_carrier.py
  delivery_price_rule_volumetric_weight/models/delivery_price_rule.py
  delivery_price_rule_volumetric_weight/readme/CONFIGURE.rst
  delivery_price_rule_volumetric_weight/static/description/index.html
  delivery_price_rule_volumetric_weight/tests/test_delivery_price.py
Labels: approved, bot is merging ⏳

#557 [13.0][ADD] delivery_sending: New module
  delivery_sending/README.rst
  delivery_sending/__init__.py
  delivery_sending/__manifest__.py
  delivery_sending/api/ws_clientes.wsdl.xml
  delivery_sending/i18n/delivery_sending.pot
  delivery_sending/i18n/es.po
  delivery_sending/models/__init__.py
  delivery_sending/models/delivery_carrier.py
  delivery_sending/models/product_packaging.py
  delivery_sending/models/sending_master_data.py
  delivery_sending/models/sending_request.py
  delivery_sending/models/stock_picking.py
  delivery_sending/readme/CONFIGURE.rst
  delivery_sending/readme/CONTRIBUTORS.rst
  delivery_sending/readme/DESCRIPTION.rst
  delivery_sending/readme/INSTALL.rst
  delivery_sending/readme/ROADMAP.rst
  delivery_sending/readme/USAGE.rst
  delivery_sending/static/description/icon.png
  delivery_sending/static/description/index.html
  delivery_sending/tests/__init__.py
  delivery_sending/tests/test_delivery_sending.py
  delivery_sending/views/delivery_sending_view.xml
  delivery_sending/views/stock_picking_views.xml
  setup/delivery_sending/odoo/addons/delivery_sending
  setup/delivery_sending/setup.py
Labels: approved, bot is merging ⏳

#555 [13.0][FIX] delivery_state: cron
  delivery_state/models/stock_picking.py
Labels: approved, bot is merging ⏳

#558 [14.0][FW] [FIX] delivery_state: cron
  delivery_state/models/stock_picking.py
Labels: approved, bot is merging ⏳

#551 [16.0][MIG] delivery_state: Migration to 16.0
  delivery_state/README.rst
  delivery_state/__init__.py
  delivery_state/__manifest__.py
  delivery_state/data/ir_cron_data.xml
  delivery_state/data/mail_template.xml
  delivery_state/i18n/delivery_state.pot
  delivery_state/i18n/es.po
  delivery_state/migrations/16.0.1.0.0/pre-migration.py
  delivery_state/models/__init__.py
  delivery_state/models/delivery_carrier.py
  delivery_state/models/res_company.py
  delivery_state/models/res_config_settings.py
  delivery_state/models/stock_picking.py
  delivery_state/readme/CONFIGURE.rst
  delivery_state/readme/CONTRIBUTORS.rst
  delivery_state/readme/DESCRIPTION.rst
  delivery_state/readme/USAGE.rst
  delivery_state/static/description/icon.png
  delivery_state/static/description/index.html
  delivery_state/tests/__init__.py
  delivery_state/tests/test_delivery_state.py
  delivery_state/views/res_config_settings_view.xml
  delivery_state/views/stock_picking_views.xml
  setup/delivery_state/odoo/addons/delivery_state
  setup/delivery_state/setup.py
Labels: needs review, approved, migration, bot is merging ⏳

#559 [15.0][FIX] delivery_state: cron
  delivery_state/models/stock_picking.py
Labels: approved, bot is merging ⏳

#562 [13.0][FIX] delivery_sending: Avoid displaying a non-existent error
  delivery_sending/models/delivery_carrier.py
Labels: approved, bot is merging ⏳

#554 [16.0][MIG] delivery_price_method: Migration to 16.0
  delivery_price_method/README.rst
  delivery_price_method/__init__.py
  delivery_price_method/__manifest__.py
  delivery_price_method/i18n/delivery_price_method.pot
  delivery_price_method/i18n/es.po
  delivery_price_method/i18n/es_CL.po
  delivery_price_method/i18n/es_VE.po
  delivery_price_method/models/__init__.py
  delivery_price_method/models/delivery_carrier.py
  delivery_price_method/readme/CONTRIBUTORS.rst
  delivery_price_method/readme/DESCRIPTION.rst
  delivery_price_method/readme/USAGE.rst
  delivery_price_method/static/description/icon.png
  delivery_price_method/static/description/index.html
  delivery_price_method/tests/__init__.py
  delivery_price_method/tests/test_delivery_price_method.py
  delivery_price_method/views/delivery_carrier_views.xml
  setup/delivery_price_method/odoo/addons/delivery_price_method
  setup/delivery_price_method/setup.py
Labels: bot is merging ⏳

#566 [16.0][MIG] delivery_cttexpress: Migration to 16.0
  delivery_cttexpress/README.rst
  delivery_cttexpress/__init__.py
  delivery_cttexpress/__manifest__.py
  delivery_cttexpress/i18n/delivery_cttexpress.pot
  delivery_cttexpress/i18n/es.po
  delivery_cttexpress/models/__init__.py
  delivery_cttexpress/models/cttexpress_master_data.py
  delivery_cttexpress/models/cttexpress_request.py
  delivery_cttexpress/models/delivery_carrier.py
  delivery_cttexpress/models/stock_picking.py
  delivery_cttexpress/readme/CONFIGURE.rst
  delivery_cttexpress/readme/CONTRIBUTORS.rst
  delivery_cttexpress/readme/CREDITS.rst
  delivery_cttexpress/readme/DESCRIPTION.rst
  delivery_cttexpress/readme/INSTALL.rst
  delivery_cttexpress/readme/ROADMAP.rst
  delivery_cttexpress/readme/USAGE.rst
  delivery_cttexpress/security/ir.model.access.csv
  delivery_cttexpress/static/description/icon.png
  delivery_cttexpress/static/description/icon.svg
  delivery_cttexpress/static/description/index.html
  delivery_cttexpress/tests/__init__.py
  delivery_cttexpress/tests/test_delivery_cttexpress.py
  delivery_cttexpress/views/delivery_cttexpress_view.xml
  delivery_cttexpress/views/stock_picking_views.xml
  delivery_cttexpress/wizards/__init__.py
  delivery_cttexpress/wizards/cttexpress_manifest_wizard.py
  delivery_cttexpress/wizards/cttexpress_manifest_wizard_views.xml
  delivery_cttexpress/wizards/cttexpress_pickup_wizard.py
  delivery_cttexpress/wizards/cttexpress_pickup_wizard.xml
  requirements.txt
  setup/delivery_cttexpress/odoo/addons/delivery_cttexpress
  setup/delivery_cttexpress/setup.py
Labels: approved, bot is merging ⏳

#544 [15.0] [MIG] connector_routific: Migration to 15.0
  connector_routific/README.rst
  connector_routific/__init__.py
  connector_routific/__manifest__.py
  connector_routific/data/sequence.xml
  connector_routific/i18n/connector_routific.pot
  connector_routific/i18n/es.po
  connector_routific/models/__init__.py
  connector_routific/models/product_attribute.py
  connector_routific/models/res_partner.py
  connector_routific/models/routific_config.py
  connector_routific/models/routific_project.py
  connector_routific/models/routific_project_driver.py
  connector_routific/models/stock_picking.py
  connector_routific/readme/CONFIGURE.rst
  connector_routific/readme/CONTRIBUTORS.rst
  connector_routific/readme/DESCRIPTION.rst
  connector_routific/readme/USAGE.rst
  connector_routific/security/ir.model.access.csv
  connector_routific/static/description/icon.png
  connector_routific/static/description/index.html
  connector_routific/tests/__init__.py
  connector_routific/tests/test_connector_routific.py
  connector_routific/views/product_attribute_views.xml
  connector_routific/views/res_partner_view.xml
  connector_routific/views/routific_config_views.xml
  connector_routific/views/routific_driver_views.xml
  connector_routific/views/routific_project_driver_view.xml
  connector_routific/views/routific_project_views.xml
  connector_routific/views/stock_picking_views.xml
  connector_routific/wizards/__init__.py
  connector_routific/wizards/routific_project_creator.py
  connector_routific/wizards/routific_project_creator_view.xml
  requirements.txt
  setup/connector_routific/odoo/addons/connector_routific
  setup/connector_routific/setup.py
Labels: approved, bot is merging ⏳

#569 [15.0][MIG] delivery_free_fee_removal: Migration to 15.0
  delivery_free_fee_removal/README.rst
  delivery_free_fee_removal/__init__.py
  delivery_free_fee_removal/__manifest__.py
  delivery_free_fee_removal/i18n/delivery_free_fee_removal.pot
  delivery_free_fee_removal/i18n/es.po
  delivery_free_fee_removal/models/__init__.py
  delivery_free_fee_removal/models/sale_order.py
  delivery_free_fee_removal/models/sale_order_line.py
  delivery_free_fee_removal/readme/CONTRIBUTORS.rst
  delivery_free_fee_removal/readme/CREDITS.rst
  delivery_free_fee_removal/readme/DESCRIPTION.rst
  delivery_free_fee_removal/reports/sale_report_templates.xml
  delivery_free_fee_removal/static/description/icon.png
  delivery_free_fee_removal/static/description/index.html
  delivery_free_fee_removal/tests/__init__.py
  delivery_free_fee_removal/tests/test_delivery_free_fee_removal.py
  delivery_free_fee_removal/views/sale_order_views.xml
  setup/delivery_free_fee_removal/odoo/addons/delivery_free_fee_removal
  setup/delivery_free_fee_removal/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#568 [16.0][MIG] migrate delivery_carrier_info
  delivery_carrier_info/README.rst
  delivery_carrier_info/__init__.py
  delivery_carrier_info/__manifest__.py
  delivery_carrier_info/i18n/delivery_carrier_info.pot
  delivery_carrier_info/migrations/16.0.1.0.0/pre-migration.py
  delivery_carrier_info/models/__init__.py
  delivery_carrier_info/models/delivery_carrier.py
  delivery_carrier_info/readme/CONTRIBUTORS.rst
  delivery_carrier_info/readme/DESCRIPTION.rst
  delivery_carrier_info/readme/USAGE.rst
  delivery_carrier_info/static/description/icon.png
  delivery_carrier_info/static/description/index.html
  delivery_carrier_info/views/delivery_view.xml
  setup/delivery_carrier_info/odoo/addons/delivery_carrier_info
  setup/delivery_carrier_info/setup.py
Labels: approved, bot is merging ⏳
