Repository OCA/delivery-carrier, pull requests merged in 2022-05, with the labels that each got.

#479 [14.0][FIX] base_delivery_carrier: Fix alternative_send_shipping return value
  base_delivery_carrier_label/models/delivery_carrier.py
Labels: approved, bot is merging ⏳

#485 [13.0][FIX] delivery_free_fee_removal: Method action_confirm don't return supper values
  delivery_free_fee_removal/models/sale_order.py
Labels: approved, bot is merging ⏳

#489 [FIX] add noupdate for carrier_paazl in delivery.carrier
  delivery_carrier_label_paazl/data/delivery_carrier.xml
Labels: approved, bot is merging ⏳

#488 [14.0][FIX] base_delivery_carrier_label: avoid duplicating carrier_id
  base_delivery_carrier_label/__manifest__.py
  base_delivery_carrier_label/views/stock.xml
Labels: bug, bot is merging ⏳

#353 [13.0][ADD] connector_routific: New module for connect with Routific Platform
  connector_routific/README.rst
  connector_routific/__init__.py
  connector_routific/__manifest__.py
  connector_routific/data/sequence.xml
  connector_routific/i18n/connector_routific.pot
  connector_routific/i18n/es.po
  connector_routific/models/__init__.py
  connector_routific/models/product_attribute.py
  connector_routific/models/res_partner.py
  connector_routific/models/routific_config.py
  connector_routific/models/routific_project.py
  connector_routific/models/routific_project_driver.py
  connector_routific/models/stock_picking.py
  connector_routific/readme/CONFIGURE.rst
  connector_routific/readme/CONTRIBUTORS.rst
  connector_routific/readme/DESCRIPTION.rst
  connector_routific/readme/USAGE.rst
  connector_routific/security/ir.model.access.csv
  connector_routific/static/description/icon.png
  connector_routific/static/description/index.html
  connector_routific/tests/__init__.py
  connector_routific/tests/test_connector_routific.py
  connector_routific/views/product_attribute_views.xml
  connector_routific/views/res_partner_view.xml
  connector_routific/views/routific_config_views.xml
  connector_routific/views/routific_driver_views.xml
  connector_routific/views/routific_project_driver_view.xml
  connector_routific/views/routific_project_views.xml
  connector_routific/views/stock_picking_views.xml
  connector_routific/wizards/__init__.py
  connector_routific/wizards/routific_project_creator.py
  connector_routific/wizards/routific_project_creator_view.xml
  requeriments.txt
  setup/connector_routific/odoo/addons/connector_routific
  setup/connector_routific/setup.py
Labels: needs review, approved, bot is merging ⏳, stale
