Repository OCA/delivery-carrier, pull requests merged in 2022-08, with the labels that each got.

#510 [15.0][MIG] partner_delivery_zone: Migration to 15.0
  partner_delivery_zone/README.rst
  partner_delivery_zone/__init__.py
  partner_delivery_zone/__manifest__.py
  partner_delivery_zone/i18n/de.po
  partner_delivery_zone/i18n/es.po
  partner_delivery_zone/i18n/fr_FR.po
  partner_delivery_zone/i18n/it.po
  partner_delivery_zone/i18n/partner_delivery_zone.pot
  partner_delivery_zone/i18n/zh_CN.po
  partner_delivery_zone/models/__init__.py
  partner_delivery_zone/models/partner_delivery_zone.py
  partner_delivery_zone/models/res_partner.py
  partner_delivery_zone/models/sale_order.py
  partner_delivery_zone/models/stock_move.py
  partner_delivery_zone/models/stock_picking.py
  partner_delivery_zone/readme/CONFIGURATION.rst
  partner_delivery_zone/readme/CONFIGURE.rst
  partner_delivery_zone/readme/CONTRIBUTORS.rst
  partner_delivery_zone/readme/DESCRIPTION.rst
  partner_delivery_zone/readme/ROADMAP.rst
  partner_delivery_zone/readme/USAGE.rst
  partner_delivery_zone/security/ir.model.access.csv
  partner_delivery_zone/static/description/icon.png
  partner_delivery_zone/static/description/index.html
  partner_delivery_zone/tests/__init__.py
  partner_delivery_zone/tests/test_partner_delivery_zone.py
  partner_delivery_zone/views/partner_delivery_zone_view.xml
  partner_delivery_zone/views/report_deliveryslip.xml
  partner_delivery_zone/views/report_shipping.xml
  partner_delivery_zone/views/res_partner_view.xml
  partner_delivery_zone/views/sale_order_view.xml
  partner_delivery_zone/views/stock_picking_view.xml
  setup/partner_delivery_zone/odoo/addons/partner_delivery_zone
  setup/partner_delivery_zone/setup.py
Labels: approved, bot is merging ⏳

#503 [14.0] delivery_send_to_shipper_at_operation: keep and split tracking with a comma
  delivery_send_to_shipper_at_operation/models/stock_picking.py
  delivery_send_to_shipper_at_operation/tests/test_send_to_shipper.py
Labels: approved, ready to merge, bot is merging ⏳

#515 [15.0][MIG] delivery_package_number: Migration to 15.0
  delivery_package_number/README.rst
  delivery_package_number/__init__.py
  delivery_package_number/__manifest__.py
  delivery_package_number/i18n/delivery_package_number.pot
  delivery_package_number/i18n/es.po
  delivery_package_number/i18n/sl.po
  delivery_package_number/models/__init__.py
  delivery_package_number/models/stock_picking.py
  delivery_package_number/readme/CONTRIBUTORS.rst
  delivery_package_number/readme/DESCRIPTION.rst
  delivery_package_number/readme/USAGE.rst
  delivery_package_number/static/description/icon.png
  delivery_package_number/static/description/index.html
  delivery_package_number/tests/__init__.py
  delivery_package_number/tests/test_delivery_package_number.py
  delivery_package_number/views/stock_picking_views.xml
  delivery_package_number/wizard/__init__.py
  delivery_package_number/wizard/stock_immediate_transfer_views.xml
  delivery_package_number/wizard/stock_inmediate_transfer.py
  setup/delivery_package_number/odoo/addons/delivery_package_number
  setup/delivery_package_number/setup.py
Labels: approved, bot is merging ⏳

#497 [13.0][FIX] delivery_ups_oca: Create label from create_shipping response to avoid error.
  delivery_ups_oca/__manifest__.py
  delivery_ups_oca/i18n/delivery_ups_oca.pot
  delivery_ups_oca/models/__init__.py
  delivery_ups_oca/models/delivery_carrier.py
  delivery_ups_oca/models/stock_picking.py
  delivery_ups_oca/models/ups_request.py
  delivery_ups_oca/tests/test_delivery_ups.py
  delivery_ups_oca/views/delivery_carrier_view.xml
  delivery_ups_oca/views/stock_picking_view.xml
Labels: approved, bot is merging ⏳

#506 [ADD] delivery_translatable in 15.0
  delivery_translatable/README.rst
  delivery_translatable/__init__.py
  delivery_translatable/__manifest__.py
  delivery_translatable/models/__init__.py
  delivery_translatable/models/delivery.py
  delivery_translatable/readme/CONTRIBUTORS.rst
  delivery_translatable/readme/DESCRIPTION.rst
  setup/delivery_translatable/odoo/addons/delivery_translatable
  setup/delivery_translatable/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#501 [13.0][IMP] delivery_tnt_oca: Add pieceLine info from rate_shipment request + Round some data to 2 decimal places
  delivery_tnt_oca/__manifest__.py
  delivery_tnt_oca/data/product_packaging_data.xml
  delivery_tnt_oca/i18n/delivery_tnt_oca.pot
  delivery_tnt_oca/i18n/es.po
  delivery_tnt_oca/models/delivery_carrier.py
  delivery_tnt_oca/models/tnt_request.py
  delivery_tnt_oca/tests/test_delivery_tnt.py
  delivery_tnt_oca/views/delivery_carrier_view.xml
Labels: approved, bot is merging ⏳

#517 [14.0][IMP] delivery_tnt_oca: Add pieceLine info from rate_shipment request + Round some data to 2 decimal places
  delivery_tnt_oca/__manifest__.py
  delivery_tnt_oca/data/product_packaging_data.xml
  delivery_tnt_oca/i18n/delivery_tnt_oca.pot
  delivery_tnt_oca/i18n/es.po
  delivery_tnt_oca/models/delivery_carrier.py
  delivery_tnt_oca/models/tnt_request.py
  delivery_tnt_oca/tests/test_delivery_tnt.py
  delivery_tnt_oca/views/delivery_carrier_view.xml
Labels: approved, bot is merging ⏳

#518 [14.0][MIG] delivery_price_method: Migration to 14.0
  delivery_price_method/README.rst
  delivery_price_method/__init__.py
  delivery_price_method/__manifest__.py
  delivery_price_method/i18n/delivery_price_method.pot
  delivery_price_method/i18n/es.po
  delivery_price_method/i18n/es_CL.po
  delivery_price_method/i18n/es_VE.po
  delivery_price_method/models/__init__.py
  delivery_price_method/models/delivery_carrier.py
  delivery_price_method/readme/CONTRIBUTORS.rst
  delivery_price_method/readme/DESCRIPTION.rst
  delivery_price_method/readme/USAGE.rst
  delivery_price_method/static/description/icon.png
  delivery_price_method/static/description/index.html
  delivery_price_method/tests/__init__.py
  delivery_price_method/tests/test_delivery_price_method.py
  delivery_price_method/views/delivery_carrier_views.xml
  setup/delivery_price_method/odoo/addons/delivery_price_method
  setup/delivery_price_method/setup.py
Labels: approved, bot is merging ⏳

#519 [13.0][IMP] delivery_package_number: Hide Number of packages in Immediate Transfer wizard if picking have not carrier.
  delivery_package_number/i18n/delivery_package_number.pot
  delivery_package_number/i18n/es.po
  delivery_package_number/wizard/stock_immediate_transfer_views.xml
  delivery_package_number/wizard/stock_inmediate_transfer.py
Labels: approved, bot is merging ⏳

#520 [14.0][IMP] delivery_package_number: Hide Number of packages in Immediate Transfer wizard if picking have not carrier.
  delivery_package_number/i18n/delivery_package_number.pot
  delivery_package_number/i18n/es.po
  delivery_package_number/wizard/stock_immediate_transfer_views.xml
  delivery_package_number/wizard/stock_inmediate_transfer.py
Labels: approved, bot is merging ⏳

#521 [15.0][IMP] delivery_package_number: Hide Number of packages in Immediate Transfer wizard if picking have not carrier.
  delivery_package_number/i18n/delivery_package_number.pot
  delivery_package_number/i18n/es.po
  delivery_package_number/wizard/stock_immediate_transfer_views.xml
  delivery_package_number/wizard/stock_inmediate_transfer.py
Labels: approved, bot is merging ⏳

#526 [UPD] Switch to Github Actions
  .copier-answers.yml
  .github/workflows/test.yml
  .gitignore
  .pre-commit-config.yaml
  .pylintrc
  .pylintrc-mandatory
  .travis.yml
  README.md
Labels: bot is merging ⏳
