Repository OCA/delivery-carrier, pull requests merged in 2023-04, with the labels that each got.

#619 [16.0][MIG] delivery_postlogistics: Migration to 16.0
  delivery_postlogistics/README.rst
  delivery_postlogistics/__init__.py
  delivery_postlogistics/__manifest__.py
  delivery_postlogistics/data/barcode handbuch.PDF
  delivery_postlogistics/data/delivery.xml
  delivery_postlogistics/data/partner.xml
  delivery_postlogistics/data/product.xml
  delivery_postlogistics/i18n/delivery_postlogistics.pot
  delivery_postlogistics/models/__init__.py
  delivery_postlogistics/models/delivery_carrier.py
  delivery_postlogistics/models/postlogistics_carrier_template_options.py
  delivery_postlogistics/models/postlogistics_license.py
  delivery_postlogistics/models/postlogistics_shipping_label.py
  delivery_postlogistics/models/res_partner.py
  delivery_postlogistics/models/stock_move.py
  delivery_postlogistics/models/stock_package_type.py
  delivery_postlogistics/models/stock_picking.py
  delivery_postlogistics/models/stock_quant_package.py
  delivery_postlogistics/postlogistics/__init__.py
  delivery_postlogistics/postlogistics/web_service.py
  delivery_postlogistics/readme/CONFIGURE.rst
  delivery_postlogistics/readme/CONTRIBUTORS.rst
  delivery_postlogistics/readme/CREDITS.rst
  delivery_postlogistics/readme/DESCRIPTION.rst
  delivery_postlogistics/readme/ROADMAP.rst
  delivery_postlogistics/security/ir.model.access.csv
  delivery_postlogistics/static/description/icon.svg
  delivery_postlogistics/static/description/index.html
  delivery_postlogistics/static/img/postlogistics-logo.jpg
  delivery_postlogistics/tests/__init__.py
  delivery_postlogistics/tests/common.py
  delivery_postlogistics/tests/fixtures/cassettes/test_missing_language.yaml
  delivery_postlogistics/tests/fixtures/cassettes/test_store_label.yaml
  delivery_postlogistics/tests/test_packaging_code.py
  delivery_postlogistics/tests/test_postlogistics.py
  delivery_postlogistics/tests/test_sanitize_values.py
  delivery_postlogistics/views/delivery.xml
  delivery_postlogistics/views/postlogistics_license.xml
  delivery_postlogistics/views/res_partner_view.xml
  delivery_postlogistics/views/stock.xml
  delivery_postlogistics/views/stock_package_type_view.xml
  delivery_postlogistics/views/stock_quant_package_view.xml
  setup/delivery_postlogistics/odoo/addons/delivery_postlogistics
  setup/delivery_postlogistics/setup.py
  test-requirements.txt
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#630 [14.0] delivery_carrier_pricelist: fix concurrency errors
  delivery_carrier_pricelist/models/delivery_carrier.py
  delivery_carrier_pricelist/tests/test_delivery_pricelist.py
Labels: bug, approved, bot is merging ⏳

#509 [14.0][IMP] delivery_carrier_label_batch: tracking reference purge when regenerating labels
  delivery_carrier_label_batch/models/stock_batch_picking.py
  delivery_carrier_label_batch/tests/test_generate_labels.py
  delivery_carrier_label_batch/wizard/generate_labels.py
Labels: bot is merging ⏳
