Repository OCA/delivery-carrier, pull requests merged in 2023-07, with the labels that each got.

#662 [IMP] base_delivery_carrier_label : write the parcel tracking uri if available
  base_delivery_carrier_label/models/stock_picking.py
  base_delivery_carrier_label/tests/test_send.py
Labels: approved, bot is merging ⏳

#671 [15.0][OU-ADD] delivery_state: Delete old template on post-migration
  delivery_state/migrations/15.0.1.0.0/post-migration.py
Labels: approved

#672 [14.0][FIX] delivery_carrier_package_measure_required: fix warning constrains
  delivery_carrier_package_measure_required/models/stock_quant_package.py
  delivery_carrier_package_measure_required/tests/test_delivery_carrier_package_measure_require.py
Labels: bot is merging ⏳

#612 [14.0][FIX] base_delivery_carrier_files: Reset cursor back for StringIO()
  base_delivery_carrier_files/csv_writer/unicode_writer.py
Labels: enhancement, needs review, approved, ready to merge, bot is merging ⏳

#659 [14.0] Fix access to not-existing record self after rollback
  delivery_postlogistics/models/stock_picking.py
Labels: approved, bot is merging ⏳

#604 [16.0][ADD] delivery_estimated_package_quantity_by_weight
  delivery_estimated_package_quantity_by_weight/README.rst
  delivery_estimated_package_quantity_by_weight/__init__.py
  delivery_estimated_package_quantity_by_weight/__manifest__.py
  delivery_estimated_package_quantity_by_weight/i18n/delivery_estimated_package_quantity_by_weight.pot
  delivery_estimated_package_quantity_by_weight/i18n/fr_BE.po
  delivery_estimated_package_quantity_by_weight/models/__init__.py
  delivery_estimated_package_quantity_by_weight/models/delivery_carrier.py
  delivery_estimated_package_quantity_by_weight/models/stock_picking.py
  delivery_estimated_package_quantity_by_weight/readme/CONTRIBUTORS.rst
  delivery_estimated_package_quantity_by_weight/readme/DESCRIPTION.rst
  delivery_estimated_package_quantity_by_weight/readme/USAGE.rst
  delivery_estimated_package_quantity_by_weight/static/description/index.html
  delivery_estimated_package_quantity_by_weight/tests/__init__.py
  delivery_estimated_package_quantity_by_weight/tests/test_stock_picking.py
  delivery_estimated_package_quantity_by_weight/views/delivery_carrier_views.xml
  delivery_estimated_package_quantity_by_weight/views/stock_picking_views.xml
  setup/delivery_estimated_package_quantity_by_weight/odoo/addons/delivery_estimated_package_quantity_by_weight
  setup/delivery_estimated_package_quantity_by_weight/setup.py
Labels: needs review, approved, ready to merge, bot is merging ⏳

#675 [14.0][IMP] delivery schenker and delivery_schenker_picking_volume
  delivery_schenker/models/delivery_carrier.py
  delivery_schenker/tests/common.py
  delivery_schenker/tests/test_delivery_schenker.py
  delivery_schenker_picking_volume/models/delivery_carrier.py
  delivery_schenker_picking_volume/tests/__init__.py
  delivery_schenker_picking_volume/tests/test_delivery_schenker.py
Labels: approved, ready to merge, bot is merging ⏳

#669 [16.0][FIX] delivery_postlogistics: if street2 is defined, show it after street on shipping label
  delivery_postlogistics/postlogistics/web_service.py
Labels: approved, bot is merging ⏳

#668 Add delivery_carrier_return_barcode_pattern
  delivery_carrier_return_barcode_pattern/README.rst
  delivery_carrier_return_barcode_pattern/__init__.py
  delivery_carrier_return_barcode_pattern/__manifest__.py
  delivery_carrier_return_barcode_pattern/models/__init__.py
  delivery_carrier_return_barcode_pattern/models/delivery_carrier.py
  delivery_carrier_return_barcode_pattern/readme/CONTRIBUTORS.rst
  delivery_carrier_return_barcode_pattern/readme/DESCRIPTION.rst
  delivery_carrier_return_barcode_pattern/tests/__init__.py
  delivery_carrier_return_barcode_pattern/tests/test_delivery_carrier_return_barcode.py
  delivery_carrier_return_barcode_pattern/views/delivery_carrier.xml
  setup/delivery_carrier_return_barcode_pattern/odoo/addons/delivery_carrier_return_barcode_pattern
  setup/delivery_carrier_return_barcode_pattern/setup.py
Labels: needs review, approved, ready to merge, bot is merging ⏳
