Repository OCA/delivery-carrier, pull requests merged in 2023-05, with the labels that each got.

#634 [13.0][FIX] delivery_multi_destination: Avoid error in creation of a multiple carrier with UX
  delivery_multi_destination/models/delivery_carrier.py
  delivery_multi_destination/tests/test_delivery_multi_destination.py
Labels: approved, bot is merging ⏳

#635 [14.0][FIX] delivery_multi_destination: Avoid error in creation of a multiple carrier with UX
  delivery_multi_destination/models/delivery_carrier.py
  delivery_multi_destination/tests/test_delivery_multi_destination.py
Labels: approved, bot is merging ⏳

#636 [15.0][FIX] delivery_multi_destination: Avoid error in creation of a multiple carrier with UX
  delivery_multi_destination/models/delivery_carrier.py
  delivery_multi_destination/tests/test_delivery_multi_destination.py
Labels: approved, bot is merging ⏳

#633 [FIX] delivery_schenker: Bugfix volume calculation
  delivery_schenker/models/delivery_carrier.py
  delivery_schenker_picking_volume/models/delivery_carrier.py
Labels: approved, bot is merging ⏳

#624 [FIX] stock_picking_delivery_link: Add view for picking type option
  stock_picking_delivery_link/__manifest__.py
  stock_picking_delivery_link/views/stock_picking_type.xml
Labels: needs review, approved, ready to merge, bot is merging ⏳

#647 [15.0][OU-ADD] delivery_auto_refresh: Migration script to delete deactivated parameters
  delivery_auto_refresh/migrations/15.0.1.0.0/pre-migration.py
Labels: approved, ready to merge
