Repository OCA/delivery-carrier, pull requests merged in 2023-02, with the labels that each got.

#606 [14.0][FIX] delivery_tnt_oca: Incorrect method name
  delivery_tnt_oca/models/delivery_carrier.py
Labels: bot is merging ⏳

#608 [UPD] Copier update
  .copier-answers.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
Labels: bot is merging ⏳

#594 [16.0][ADD] delivery_carrier_max_weight_constraint
  delivery_carrier_max_weight_constraint/README.rst
  delivery_carrier_max_weight_constraint/__init__.py
  delivery_carrier_max_weight_constraint/__manifest__.py
  delivery_carrier_max_weight_constraint/models/__init__.py
  delivery_carrier_max_weight_constraint/models/delivery_carrier.py
  delivery_carrier_max_weight_constraint/models/res_company.py
  delivery_carrier_max_weight_constraint/models/res_config_settings.py
  delivery_carrier_max_weight_constraint/models/stock_package_type.py
  delivery_carrier_max_weight_constraint/readme/CONTRIBUTORS.rst
  delivery_carrier_max_weight_constraint/readme/DESCRIPTION.rst
  delivery_carrier_max_weight_constraint/readme/USAGE.rst
  delivery_carrier_max_weight_constraint/static/description/icon.png
  delivery_carrier_max_weight_constraint/tests/__init__.py
  delivery_carrier_max_weight_constraint/tests/test_max_weight_constraint.py
  delivery_carrier_max_weight_constraint/views/delivery_carrier_views.xml
  delivery_carrier_max_weight_constraint/views/res_config_settings_views.xml
  delivery_carrier_max_weight_constraint/views/stock_package_type_views.xml
  delivery_carrier_max_weight_constraint/wizards/__init__.py
  delivery_carrier_max_weight_constraint/wizards/choose_delivery_package.py
  setup/delivery_carrier_max_weight_constraint/odoo/addons/delivery_carrier_max_weight_constraint
  setup/delivery_carrier_max_weight_constraint/setup.py
Labels: needs review, approved, ready to merge, bot is merging ⏳

#610 [15.0][MIG] delivery_purchase: Migration to 15.0
  delivery_purchase/README.rst
  delivery_purchase/__init__.py
  delivery_purchase/__manifest__.py
  delivery_purchase/i18n/delivery_purchase.pot
  delivery_purchase/i18n/es.po
  delivery_purchase/models/__init__.py
  delivery_purchase/models/delivery_carrier.py
  delivery_purchase/models/purchase_order.py
  delivery_purchase/models/stock_picking.py
  delivery_purchase/readme/CONTRIBUTORS.rst
  delivery_purchase/readme/DESCRIPTION.rst
  delivery_purchase/readme/USAGE.rst
  delivery_purchase/static/description/icon.png
  delivery_purchase/static/description/index.html
  delivery_purchase/tests/__init__.py
  delivery_purchase/tests/test_delivery_purchase.py
  delivery_purchase/views/purchase_order_view.xml
  setup/delivery_purchase/odoo/addons/delivery_purchase
  setup/delivery_purchase/setup.py
Labels: approved, bot is merging ⏳

#613 [14.0] Remove obsolete oca_dependencies.txt
  oca_dependencies.txt
Labels: needs review

#609 [14.0][MIG] delivery_postlogistics_dangerous_goods
  delivery_postlogistics/tests/test_postlogistics.py
  delivery_postlogistics_dangerous_goods/README.rst
  delivery_postlogistics_dangerous_goods/__init__.py
  delivery_postlogistics_dangerous_goods/__manifest__.py
  delivery_postlogistics_dangerous_goods/models/__init__.py
  delivery_postlogistics_dangerous_goods/models/stock_picking.py
  delivery_postlogistics_dangerous_goods/postlogistics/__init__.py
  delivery_postlogistics_dangerous_goods/postlogistics/web_service.py
  delivery_postlogistics_dangerous_goods/readme/CONTRIBUTORS.rst
  delivery_postlogistics_dangerous_goods/readme/DESCRIPTION.rst
  delivery_postlogistics_dangerous_goods/static/description/index.html
  delivery_postlogistics_dangerous_goods/tests/__init__.py
  delivery_postlogistics_dangerous_goods/tests/test_postlogistics_dangerous_goods.py
  setup/delivery_postlogistics_dangerous_goods/odoo/addons/delivery_postlogistics_dangerous_goods
  setup/delivery_postlogistics_dangerous_goods/setup.py
Labels: approved, migration, bot is merging ⏳
