Repository OCA/delivery-carrier, pull requests merged in 2023-12, with the labels that each got.

#730 [15.0][IMP] delivery_package_number: Allow set package numbers at confirm and new labels
  delivery_package_number/README.rst
  delivery_package_number/__manifest__.py
  delivery_package_number/data/paperformat_data.xml
  delivery_package_number/models/__init__.py
  delivery_package_number/models/stock_picking.py
  delivery_package_number/models/stock_picking_type.py
  delivery_package_number/readme/CONTRIBUTORS.rst
  delivery_package_number/reports/report_package_number.xml
  delivery_package_number/security/ir.model.access.csv
  delivery_package_number/static/description/index.html
  delivery_package_number/views/stock_picking_type_views.xml
  delivery_package_number/wizard/__init__.py
  delivery_package_number/wizard/stock_backorder_confirmation.py
  delivery_package_number/wizard/stock_backorder_confirmation_views.xml
  delivery_package_number/wizard/stock_immediate_transfer_views.xml
  delivery_package_number/wizard/stock_inmediate_transfer.py
  delivery_package_number/wizard/stock_number_package_mixin.py
  delivery_package_number/wizard/stock_number_package_validate_wiz.py
  delivery_package_number/wizard/stock_number_package_validate_wiz_view.xml
Labels: approved, bot is merging ⏳

#720 [14.0][FIX] delivery_send_to_shipper_at_operation
  delivery_send_to_shipper_at_operation/models/stock_picking.py
  delivery_send_to_shipper_at_operation/readme/CONTRIBUTORS.rst
Labels: approved, ready to merge, bot is merging ⏳

#740 [14.0][FIX] delivery_purchase: Change the position of the carrier to the purchase order header
  delivery_purchase/views/purchase_order_view.xml
Labels: approved, bot is merging ⏳

#741 [14.0][IMP] delivery_purchase: Set carrier_price when creating a picking
  delivery_purchase/models/purchase_order.py
  delivery_purchase/tests/test_delivery_purchase.py
Labels: approved, bot is merging ⏳

#742 [15.0][IMP] delivery_purchase: FWPs changes from 14.0
  delivery_purchase/README.rst
  delivery_purchase/__manifest__.py
  delivery_purchase/i18n/delivery_purchase.pot
  delivery_purchase/i18n/es.po
  delivery_purchase/models/purchase_order.py
  delivery_purchase/models/stock_picking.py
  delivery_purchase/readme/USAGE.rst
  delivery_purchase/static/description/index.html
  delivery_purchase/tests/test_delivery_purchase.py
  delivery_purchase/views/purchase_order_view.xml
  delivery_purchase/views/stock_picking_view.xml
Labels: approved, bot is merging ⏳

#746 [16.0][IMP] improve logging
  base_delivery_carrier_label/models/stock_move_line.py
Labels: bot is merging ⏳

#749 [UPD] Copier update
  .copier-answers.yml
  .gitignore
  .pre-commit-config.yaml
Labels: bot is merging ⏳

#656 [IMP] delivery_auto_refresh: Compatibility with sale_tier_validation
  delivery_auto_refresh/models/sale_order.py
Labels: approved, ready to merge, bot is merging ⏳

#750 [IMP] delivery_package_number: Allow set package numbers at confirm and new labels
  delivery_package_number/README.rst
  delivery_package_number/__manifest__.py
  delivery_package_number/data/paperformat_data.xml
  delivery_package_number/models/__init__.py
  delivery_package_number/models/stock_picking.py
  delivery_package_number/models/stock_picking_type.py
  delivery_package_number/readme/CONTRIBUTORS.rst
  delivery_package_number/reports/report_package_number.xml
  delivery_package_number/security/ir.model.access.csv
  delivery_package_number/static/description/index.html
  delivery_package_number/views/stock_picking_type_views.xml
  delivery_package_number/wizard/__init__.py
  delivery_package_number/wizard/stock_backorder_confirmation.py
  delivery_package_number/wizard/stock_backorder_confirmation_views.xml
  delivery_package_number/wizard/stock_immediate_transfer_views.xml
  delivery_package_number/wizard/stock_inmediate_transfer.py
  delivery_package_number/wizard/stock_number_package_mixin.py
  delivery_package_number/wizard/stock_number_package_validate_wiz.py
  delivery_package_number/wizard/stock_number_package_validate_wiz_view.xml
Labels: approved, bot is merging ⏳
