Repository OCA/delivery-carrier, pull requests merged in 2023-01, with the labels that each got.

#595 [15.0][MIG] stock_picking_report_delivery_cost: Migration to version 15.0
  setup/stock_picking_report_delivery_cost/odoo/addons/stock_picking_report_delivery_cost
  setup/stock_picking_report_delivery_cost/setup.py
  stock_picking_report_delivery_cost/README.rst
  stock_picking_report_delivery_cost/__init__.py
  stock_picking_report_delivery_cost/__manifest__.py
  stock_picking_report_delivery_cost/i18n/es.po
  stock_picking_report_delivery_cost/i18n/stock_picking_report_delivery_cost.pot
  stock_picking_report_delivery_cost/models/__init__.py
  stock_picking_report_delivery_cost/models/stock_picking.py
  stock_picking_report_delivery_cost/readme/CONTRIBUTORS.rst
  stock_picking_report_delivery_cost/readme/DESCRIPTION.rst
  stock_picking_report_delivery_cost/readme/USAGE.rst
  stock_picking_report_delivery_cost/report/report_deliveryslip.xml
  stock_picking_report_delivery_cost/report/report_shipping.xml
  stock_picking_report_delivery_cost/static/description/icon.png
  stock_picking_report_delivery_cost/static/description/index.html
  stock_picking_report_delivery_cost/tests/__init__.py
  stock_picking_report_delivery_cost/tests/test_stock_picking_report_delivery_cost.py
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#596 [16.0][MIG] stock_picking_delivery_link
  setup/stock_picking_delivery_link/odoo/addons/stock_picking_delivery_link
  setup/stock_picking_delivery_link/setup.py
  stock_picking_delivery_link/README.rst
  stock_picking_delivery_link/__init__.py
  stock_picking_delivery_link/__manifest__.py
  stock_picking_delivery_link/i18n/stock_picking_delivery_link.pot
  stock_picking_delivery_link/models/__init__.py
  stock_picking_delivery_link/models/stock_picking.py
  stock_picking_delivery_link/models/stock_picking_type.py
  stock_picking_delivery_link/readme/CONTRIBUTORS.rst
  stock_picking_delivery_link/readme/DESCRIPTION.rst
  stock_picking_delivery_link/static/description/icon.png
  stock_picking_delivery_link/static/description/index.html
  stock_picking_delivery_link/tests/__init__.py
  stock_picking_delivery_link/tests/common.py
  stock_picking_delivery_link/tests/test_delivery_link.py
  stock_picking_delivery_link/views/stock_picking.xml
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#600 [13.0][IMP] partner_delivery_zone: Add delivery zone field in sale tree view
  partner_delivery_zone/views/sale_order_view.xml
Labels: enhancement, needs review, approved, bot is merging ⏳

#601 [15.0][IMP] partner_delivery_zone: Add delivery zone field in sale tree view
  partner_delivery_zone/views/sale_order_view.xml
Labels: approved, bot is merging ⏳
