Repository OCA/delivery-carrier, pull requests merged in 2023-10, with the labels that each got.

#693 [16.0][MIG] delivery_package_fee: Migrate to version 16.0
  delivery_package_fee/README.rst
  delivery_package_fee/__init__.py
  delivery_package_fee/__manifest__.py
  delivery_package_fee/i18n/delivery_package_fee.pot
  delivery_package_fee/models/__init__.py
  delivery_package_fee/models/delivery_carrier.py
  delivery_package_fee/models/delivery_package_fee.py
  delivery_package_fee/models/sale_order.py
  delivery_package_fee/models/sale_order_line.py
  delivery_package_fee/models/stock_picking.py
  delivery_package_fee/readme/CONFIGURE.rst
  delivery_package_fee/readme/CONTRIBUTORS.rst
  delivery_package_fee/readme/CREDITS.rst
  delivery_package_fee/readme/DESCRIPTION.rst
  delivery_package_fee/security/ir.model.access.csv
  delivery_package_fee/static/description/icon.png
  delivery_package_fee/static/description/index.html
  delivery_package_fee/tests/__init__.py
  delivery_package_fee/tests/test_package_fee.py
  delivery_package_fee/views/delivery_carrier_views.xml
  setup/delivery_package_fee/odoo/addons/delivery_package_fee
  setup/delivery_package_fee/setup.py
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#655 [16][FIX] delivery_carrier_account : Fix rights, it should be on inventory side rather than sale side
  delivery_carrier_account/security/ir.model.access.csv
Labels: approved, bot is merging ⏳, stale

#616 [16.0][MIG] carrier_account_environment
  carrier_account_environment/README.rst
  carrier_account_environment/__init__.py
  carrier_account_environment/__manifest__.py
  carrier_account_environment/i18n/carrier_account_environment.pot
  carrier_account_environment/i18n/carrier_environment.pot
  carrier_account_environment/models/__init__.py
  carrier_account_environment/models/carrier_account.py
  carrier_account_environment/readme/CONFIGURE.rst
  carrier_account_environment/readme/CONTRIBUTORS.rst
  carrier_account_environment/readme/DESCRIPTION.rst
  carrier_account_environment/readme/USAGE.rst
  carrier_account_environment/static/description/icon.png
  carrier_account_environment/static/description/index.html
  setup/carrier_account_environment/odoo/addons/carrier_account_environment
  setup/carrier_account_environment/setup.py
Labels: needs review, approved, migration, bot is merging ⏳

#714 [16.0][REF] Use copier v1.17.1 (previously v1.14.2)
  .copier-answers.yml
  .eslintrc.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  .pylintrc
  .pylintrc-mandatory
  delivery_postlogistics/postlogistics/web_service.py
Labels: bot is merging ⏳

#654 [16][MIG] delivery_roulier
  delivery_roulier/README.rst
  delivery_roulier/__init__.py
  delivery_roulier/__manifest__.py
  delivery_roulier/decorator.py
  delivery_roulier/demo/product.xml
  delivery_roulier/i18n/delivery_roulier.pot
  delivery_roulier/models/__init__.py
  delivery_roulier/models/delivery_carrier.py
  delivery_roulier/models/stock_move_line.py
  delivery_roulier/models/stock_picking.py
  delivery_roulier/models/stock_quant_package.py
  delivery_roulier/readme/CONFIGURE.rst
  delivery_roulier/readme/CONTRIBUTORS.rst
  delivery_roulier/readme/DESCRIPTION.rst
  delivery_roulier/readme/USAGE.rst
  delivery_roulier/static/description/icon.png
  delivery_roulier/static/description/index.html
  delivery_roulier/tests/__init__.py
  delivery_roulier/tests/models.py
  delivery_roulier/tests/test_delivery_roulier.py
  requirements.txt
  setup/delivery_roulier/odoo/addons/delivery_roulier
  setup/delivery_roulier/setup.py
  test-requirements.txt
Labels: approved, bot is merging ⏳

#717 [15.0][FIX] delivery_package_number: comment in code is added
  delivery_package_number/wizard/stock_backorder_confirmation.py
  delivery_package_number/wizard/stock_inmediate_transfer.py
Labels: approved, bot is merging ⏳

#689 [16.0][FIX] postlogistics: Set customer name mandatory
  delivery_postlogistics/postlogistics/web_service.py
Labels: approved, ready to merge, bot is merging ⏳

#715 [UPD] delivery_package_fee: delivery fee by stock package type
  delivery_package_fee/README.rst
  delivery_package_fee/models/delivery_package_fee.py
  delivery_package_fee/models/sale_order.py
  delivery_package_fee/static/description/index.html
  delivery_package_fee/tests/test_package_fee.py
  delivery_package_fee/views/delivery_carrier_views.xml
Labels: enhancement, needs review, approved, bot is merging ⏳

#721 [15.0][IMP] delivery-carrier : test performance improvement
  partner_delivery_schedule/tests/test_partner_delivery_schedule.py
  partner_delivery_zone/tests/test_partner_delivery_zone.py
Labels: bot is merging ⏳

#722 [16.0][IMP] delivery-carrier : test performance improvement
  partner_delivery_zone/tests/test_partner_delivery_zone.py
Labels: approved, bot is merging ⏳

#724 [14.0] dotfiles update needs manual intervention
  .copier-answers.yml
  .eslintrc.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  base_delivery_carrier_files/data/carrier_file_demo.xml
  base_delivery_carrier_files/i18n/base_delivery_carrier_files.pot
  base_delivery_carrier_files/views/carrier_file_view.xml
  base_delivery_carrier_files/wizards/generate_carrier_files_view.xml
  base_delivery_carrier_label/i18n/base_delivery_carrier_label.pot
  base_delivery_carrier_label/views/delivery.xml
  delivery_carrier_label_batch/data/ir.config_parameter.xml
  delivery_package_fee/views/delivery_carrier_views.xml
  delivery_tnt_oca/report/picking_templates.xml
  partner_delivery_zone/i18n/partner_delivery_zone.pot
  partner_delivery_zone/views/partner_delivery_zone_view.xml
Labels: needs review, bot is merging ⏳
