Repository OCA/delivery-carrier, pull requests merged in 2023-09, with the labels that each got.

#691 [14.0] delivery_postlogistics: improve rendering of error messages
  delivery_postlogistics/models/stock_picking.py
  delivery_postlogistics/tests/test_sanitize_values.py
Labels: approved, ready to merge, bot is merging ⏳

#695 [14.0][FIX] delivery_auto_refresh
  delivery_auto_refresh/models/sale_order.py
  delivery_auto_refresh/tests/test_delivery_auto_refresh.py
Labels: enhancement, needs review, approved, bot is merging ⏳

#692 [14.0] delivery_postlogistics: fix 'sanitize_strings' to always return strings
  delivery_postlogistics/postlogistics/web_service.py
  delivery_postlogistics/tests/test_sanitize_values.py
Labels: approved, ready to merge, bot is merging ⏳

#699 [15.0][FIX] delivery_auto_refresh: fix auto_add_delivery_line setting
  delivery_auto_refresh/models/sale_order.py
  delivery_auto_refresh/tests/test_delivery_auto_refresh.py
Labels: bot is merging ⏳

#700 [16.0][FIX] delivery_auto_refresh: fix auto_add_delivery_line setting
  delivery_auto_refresh/models/sale_order.py
  delivery_auto_refresh/tests/test_delivery_auto_refresh.py
Labels: bot is merging ⏳

#696 [15.0][FIX] delivery_package_number: Don't reset number on backorder
  delivery_package_number/models/stock_picking.py
  delivery_package_number/tests/test_delivery_package_number.py
Labels: approved, ready to merge, bot is merging ⏳

#701 [16.0][FIX] delivery_package_number: Don't reset number on backorder
  delivery_package_number/models/stock_picking.py
  delivery_package_number/tests/test_delivery_package_number.py
Labels: approved, bot is merging ⏳

#350 [14][ADD] delivery_roulier_chronopost
  delivery_roulier_chronopost_fr/__init__.py
  delivery_roulier_chronopost_fr/__manifest__.py
  delivery_roulier_chronopost_fr/data/delivery.xml
  delivery_roulier_chronopost_fr/data/product.xml
  delivery_roulier_chronopost_fr/models/__init__.py
  delivery_roulier_chronopost_fr/models/carrier_account.py
  delivery_roulier_chronopost_fr/models/delivery_carrier.py
  delivery_roulier_chronopost_fr/models/stock_picking.py
  delivery_roulier_chronopost_fr/models/stock_quant_package.py
  delivery_roulier_chronopost_fr/readme/CONTRIBUTORS.rst
  delivery_roulier_chronopost_fr/readme/DESCRIPTION.rst
  delivery_roulier_chronopost_fr/readme/ROADMAP.rst
  delivery_roulier_chronopost_fr/static/description/icon.png
  delivery_roulier_chronopost_fr/tests/__init__.py
  delivery_roulier_chronopost_fr/tests/cassettes/ChronopostLabelCase.test_labels.yaml
  delivery_roulier_chronopost_fr/tests/test_label_chronopost.py
  delivery_roulier_chronopost_fr/views/carrier_account.xml
  setup/delivery_roulier_chronopost_fr/odoo/addons/delivery_roulier_chronopost_fr
  setup/delivery_roulier_chronopost_fr/setup.py
Labels: needs review, approved, bot is merging ⏳

#704 [14.0][FIX] delivery_tnt_oca: delivery_package_number compatibility
  delivery_tnt_oca/tests/test_delivery_tnt.py
Labels: approved, bot is merging ⏳

#682 [14.0][ADD] delivery_price_product_domain: add new module
  delivery_price_product_domain/README.rst
  delivery_price_product_domain/__init__.py
  delivery_price_product_domain/__manifest__.py
  delivery_price_product_domain/models/__init__.py
  delivery_price_product_domain/models/delivery_carrier.py
  delivery_price_product_domain/models/delivery_price_rule.py
  delivery_price_product_domain/readme/CONTRIBUTORS.rst
  delivery_price_product_domain/readme/DESCRIPTION.rst
  delivery_price_product_domain/readme/USAGE.rst
  delivery_price_product_domain/tests/__init__.py
  delivery_price_product_domain/tests/test_delivery_price_product_domain.py
  delivery_price_product_domain/views/delivery_price_rule_views.xml
  setup/delivery_price_product_domain/odoo/addons/delivery_price_product_domain
  setup/delivery_price_product_domain/setup.py
Labels: needs review, approved, ready to merge, bot is merging ⏳

#648 [16.0][MIG] partner_delivery_zone
  partner_delivery_zone/README.rst
  partner_delivery_zone/__init__.py
  partner_delivery_zone/__manifest__.py
  partner_delivery_zone/i18n/de.po
  partner_delivery_zone/i18n/es.po
  partner_delivery_zone/i18n/fr_FR.po
  partner_delivery_zone/i18n/it.po
  partner_delivery_zone/i18n/partner_delivery_zone.pot
  partner_delivery_zone/i18n/zh_CN.po
  partner_delivery_zone/models/__init__.py
  partner_delivery_zone/models/partner_delivery_zone.py
  partner_delivery_zone/models/res_partner.py
  partner_delivery_zone/models/sale_order.py
  partner_delivery_zone/models/stock_move.py
  partner_delivery_zone/models/stock_picking.py
  partner_delivery_zone/readme/CONFIGURATION.rst
  partner_delivery_zone/readme/CONFIGURE.rst
  partner_delivery_zone/readme/CONTRIBUTORS.rst
  partner_delivery_zone/readme/DESCRIPTION.rst
  partner_delivery_zone/readme/ROADMAP.rst
  partner_delivery_zone/readme/USAGE.rst
  partner_delivery_zone/security/ir.model.access.csv
  partner_delivery_zone/static/description/icon.png
  partner_delivery_zone/static/description/index.html
  partner_delivery_zone/tests/__init__.py
  partner_delivery_zone/tests/test_partner_delivery_zone.py
  partner_delivery_zone/views/partner_delivery_zone_view.xml
  partner_delivery_zone/views/report_deliveryslip.xml
  partner_delivery_zone/views/report_shipping.xml
  partner_delivery_zone/views/res_partner_view.xml
  partner_delivery_zone/views/sale_order_view.xml
  partner_delivery_zone/views/stock_picking_view.xml
  setup/partner_delivery_zone/odoo/addons/partner_delivery_zone
  setup/partner_delivery_zone/setup.py
Labels: needs review, migration, bot is merging ⏳, stale

#705 [IMP] delivery_package_number: number of packages in the backorder wizard
  delivery_package_number/__manifest__.py
  delivery_package_number/readme/CONTRIBUTORS.rst
  delivery_package_number/wizard/__init__.py
  delivery_package_number/wizard/stock_backorder_confirmation.py
  delivery_package_number/wizard/stock_backorder_confirmation_views.xml
Labels: approved, bot is merging ⏳

#640 [16.0][MIG] delivery_carrier_partner
  delivery_carrier_label_gls/static/description/index.html
  delivery_carrier_partner/README.rst
  delivery_carrier_partner/__init__.py
  delivery_carrier_partner/__manifest__.py
  delivery_carrier_partner/i18n/delivery_carrier_partner.pot
  delivery_carrier_partner/i18n/fr.po
  delivery_carrier_partner/i18n/it.po
  delivery_carrier_partner/models/__init__.py
  delivery_carrier_partner/models/delivery_carrier.py
  delivery_carrier_partner/readme/CONTRIBUTORS.rst
  delivery_carrier_partner/readme/DESCRIPTION.rst
  delivery_carrier_partner/static/description/icon.png
  delivery_carrier_partner/static/description/index.html
  delivery_carrier_partner/views/delivery_carrier_views.xml
  setup/delivery_carrier_partner/odoo/addons/delivery_carrier_partner
  setup/delivery_carrier_partner/setup.py
Labels: needs review, approved, migration, bot is merging ⏳
