Repository OCA/delivery-carrier, pull requests merged in 2023-11, with the labels that each got.

#725 [14.0][MIG] delivery_purchase: Migration to 14.0
  delivery_purchase/README.rst
  delivery_purchase/__init__.py
  delivery_purchase/__manifest__.py
  delivery_purchase/i18n/delivery_purchase.pot
  delivery_purchase/i18n/es.po
  delivery_purchase/models/__init__.py
  delivery_purchase/models/delivery_carrier.py
  delivery_purchase/models/purchase_order.py
  delivery_purchase/models/stock_picking.py
  delivery_purchase/readme/CONTRIBUTORS.rst
  delivery_purchase/readme/DESCRIPTION.rst
  delivery_purchase/readme/USAGE.rst
  delivery_purchase/static/description/icon.png
  delivery_purchase/static/description/index.html
  delivery_purchase/tests/__init__.py
  delivery_purchase/tests/test_delivery_purchase.py
  delivery_purchase/views/purchase_order_view.xml
  delivery_purchase/views/stock_picking_view.xml
  setup/delivery_purchase/odoo/addons/delivery_purchase
  setup/delivery_purchase/setup.py
Labels: approved, bot is merging ⏳

#680 [ADD] delivery_packaging_archive:
  delivery_packaging_archive/README.rst
  delivery_packaging_archive/__init__.py
  delivery_packaging_archive/__manifest__.py
  delivery_packaging_archive/models/__init__.py
  delivery_packaging_archive/models/product_packaging.py
  delivery_packaging_archive/readme/CONTRIBUTORS.rst
  delivery_packaging_archive/readme/DESCRIPTION.rst
  delivery_packaging_archive/static/description/index.html
  delivery_packaging_archive/views/product_packaging_views.xml
  setup/delivery_packaging_archive/odoo/addons/delivery_packaging_archive
  setup/delivery_packaging_archive/setup.py
Labels: needs review, approved, ready to merge, bot is merging ⏳

#718 [16.0][FIX] delivery_package_fee: call map_tax in fiscal.position properly
  delivery_package_fee/models/sale_order.py
  delivery_package_fee/tests/test_package_fee.py
Labels: approved, bot is merging ⏳

#732 [14.0][FIX] delivery_postlogistics: hide key secret on view
  delivery_postlogistics/views/delivery.xml
Labels: bot is merging ⏳

#687 [14.0][FIX] delivery_carrier: Do not send a package to schenker
  delivery_schenker/models/delivery_carrier.py
  delivery_schenker/tests/common.py
  delivery_schenker/tests/test_delivery_schenker.py
Labels: approved, bot is merging ⏳
