Repository OCA/delivery-carrier, pull requests merged in 2024-05, with the labels that each got.

#779 [17.0][MIG] delivery_carrier_info
  delivery_carrier_info/README.rst
  delivery_carrier_info/__init__.py
  delivery_carrier_info/__manifest__.py
  delivery_carrier_info/i18n/delivery_carrier_info.pot
  delivery_carrier_info/i18n/es.po
  delivery_carrier_info/models/__init__.py
  delivery_carrier_info/models/delivery_carrier.py
  delivery_carrier_info/pyproject.toml
  delivery_carrier_info/readme/CONTRIBUTORS.md
  delivery_carrier_info/readme/DESCRIPTION.md
  delivery_carrier_info/readme/USAGE.md
  delivery_carrier_info/static/description/icon.png
  delivery_carrier_info/static/description/index.html
  delivery_carrier_info/views/delivery_view.xml
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#808 [15.0][FIX] delivery_cttexpress: disable tests
  delivery_cttexpress/tests/__init__.py
Labels: bot is merging ⏳

#809 [14.0][FIX] delivery_cttexpress: disable tests
  delivery_cttexpress/tests/__init__.py
Labels: bot is merging ⏳

#810 [16.0][FIX] delivery_cttexpress: disable tests
  delivery_cttexpress/tests/__init__.py
Labels: bot is merging ⏳

#811 [13.0][FIX] delivery_cttexpress: disable tests
  delivery_cttexpress/tests/__init__.py
Labels: bot is merging ⏳

#767 [14.0][IMP] delivery_carrier_return_barcode_pattern: Exclude inactive carriers
  delivery_carrier_return_barcode_pattern/models/delivery_carrier.py
Labels: enhancement, needs review, approved, ready to merge, bot is merging ⏳

#737 [13.0][IMP] delivery_cttexpress: configurable label delay
  delivery_cttexpress/models/delivery_carrier.py
  delivery_cttexpress/views/delivery_cttexpress_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#798 [16.0][FIX] delivery_postlogistics: splitting package label by package
  delivery_postlogistics/postlogistics/web_service.py
Labels: enhancement, needs review, approved, ready to merge, bot is merging ⏳

#709 [15.0][MIG] delivery_carrier_partner
  delivery_carrier_partner/README.rst
  delivery_carrier_partner/__init__.py
  delivery_carrier_partner/__manifest__.py
  delivery_carrier_partner/i18n/delivery_carrier_partner.pot
  delivery_carrier_partner/i18n/it.po
  delivery_carrier_partner/models/__init__.py
  delivery_carrier_partner/models/delivery_carrier.py
  delivery_carrier_partner/readme/CONTRIBUTORS.rst
  delivery_carrier_partner/readme/DESCRIPTION.rst
  delivery_carrier_partner/static/description/icon.png
  delivery_carrier_partner/static/description/index.html
  delivery_carrier_partner/views/delivery_carrier_views.xml
  setup/delivery_carrier_partner/odoo/addons/delivery_carrier_partner
  setup/delivery_carrier_partner/setup.py
Labels: needs review, approved, bot is merging ⏳, stale

#801 [14][ADD] delivery_schenker_quant_package_dimension: Length Width Height
  delivery_schenker/models/delivery_carrier.py
  delivery_schenker_quant_package_dimension/README.rst
  delivery_schenker_quant_package_dimension/__init__.py
  delivery_schenker_quant_package_dimension/__manifest__.py
  delivery_schenker_quant_package_dimension/models/__init__.py
  delivery_schenker_quant_package_dimension/models/delivery_carrier.py
  delivery_schenker_quant_package_dimension/readme/CONTRIBUTORS.rst
  delivery_schenker_quant_package_dimension/readme/DESCRIPTION.rst
  delivery_schenker_quant_package_dimension/static/description/index.html
  delivery_schenker_quant_package_dimension/tests/__init__.py
  delivery_schenker_quant_package_dimension/tests/test_delivery_schenker.py
  setup/delivery_schenker_quant_package_dimension/odoo/addons/delivery_schenker_quant_package_dimension
  setup/delivery_schenker_quant_package_dimension/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#781 [16.0][FIX] stock_picking_delivery_link: Test compatibility with purchase
  stock_picking_delivery_link/tests/test_delivery_link.py
Labels: bot is merging ⏳

#776 [14.0] [MIG-IMP] delivery_ups_oca, migration and oauth
  delivery_ups_oca/README.rst
  delivery_ups_oca/__init__.py
  delivery_ups_oca/__manifest__.py
  delivery_ups_oca/data/product_packaging_data.xml
  delivery_ups_oca/i18n/delivery_ups_oca.pot
  delivery_ups_oca/models/__init__.py
  delivery_ups_oca/models/delivery_carrier.py
  delivery_ups_oca/models/product_packaging.py
  delivery_ups_oca/models/stock_picking.py
  delivery_ups_oca/models/ups_request.py
  delivery_ups_oca/readme/CONFIGURE.rst
  delivery_ups_oca/readme/CONTRIBUTORS.rst
  delivery_ups_oca/readme/DESCRIPTION.rst
  delivery_ups_oca/readme/ROADMAP.rst
  delivery_ups_oca/readme/USAGE.rst
  delivery_ups_oca/static/description/icon.png
  delivery_ups_oca/static/description/index.html
  delivery_ups_oca/tests/__init__.py
  delivery_ups_oca/tests/test_delivery_ups.py
  delivery_ups_oca/views/delivery_carrier_view.xml
  delivery_ups_oca/views/stock_picking_view.xml
  setup/delivery_ups_oca/odoo/addons/delivery_ups_oca
  setup/delivery_ups_oca/setup.py
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#793 15.0 mig delivery_price_rule_untaxed
  delivery_price_rule_untaxed/README.rst
  delivery_price_rule_untaxed/__init__.py
  delivery_price_rule_untaxed/__manifest__.py
  delivery_price_rule_untaxed/data/delivery_price_rule_untaxed_demo.xml
  delivery_price_rule_untaxed/i18n/delivery_price_rule_untaxed.pot
  delivery_price_rule_untaxed/i18n/es.po
  delivery_price_rule_untaxed/i18n/fr.po
  delivery_price_rule_untaxed/i18n/it.po
  delivery_price_rule_untaxed/models/__init__.py
  delivery_price_rule_untaxed/models/delivery_carrier.py
  delivery_price_rule_untaxed/models/delivery_price_rule.py
  delivery_price_rule_untaxed/readme/CONTRIBUTORS.rst
  delivery_price_rule_untaxed/readme/DESCRIPTION.rst
  delivery_price_rule_untaxed/static/description/icon.png
  delivery_price_rule_untaxed/static/description/index.html
  delivery_price_rule_untaxed/tests/__init__.py
  delivery_price_rule_untaxed/tests/test_delivery_price_rule_untaxed.py
  setup/delivery_price_rule_untaxed/odoo/addons/delivery_price_rule_untaxed
  setup/delivery_price_rule_untaxed/setup.py
Labels: approved, ready to merge, merged 🎉

#755 [16.0][MIG] delivery_purchase: Migration to version 16.0
  delivery_purchase/README.rst
  delivery_purchase/__init__.py
  delivery_purchase/__manifest__.py
  delivery_purchase/i18n/delivery_purchase.pot
  delivery_purchase/i18n/es.po
  delivery_purchase/models/__init__.py
  delivery_purchase/models/delivery_carrier.py
  delivery_purchase/models/purchase_order.py
  delivery_purchase/models/stock_picking.py
  delivery_purchase/readme/CONTRIBUTORS.rst
  delivery_purchase/readme/DESCRIPTION.rst
  delivery_purchase/readme/USAGE.rst
  delivery_purchase/static/description/icon.png
  delivery_purchase/static/description/index.html
  delivery_purchase/tests/__init__.py
  delivery_purchase/tests/test_delivery_purchase.py
  delivery_purchase/views/purchase_order_view.xml
  delivery_purchase/views/stock_picking_view.xml
  setup/delivery_purchase/odoo/addons/delivery_purchase
  setup/delivery_purchase/setup.py
  stock_picking_delivery_link/tests/test_delivery_link.py
Labels: approved, ready to merge, bot is merging ⏳

#713 [16.0][MIG] delivery_carrier_package_measure_required: Migration to 16.0
  delivery_carrier_package_measure_required/README.rst
  delivery_carrier_package_measure_required/__init__.py
  delivery_carrier_package_measure_required/__manifest__.py
  delivery_carrier_package_measure_required/i18n/delivery_carrier_package_measure_required.pot
  delivery_carrier_package_measure_required/i18n/es.po
  delivery_carrier_package_measure_required/models/__init__.py
  delivery_carrier_package_measure_required/models/stock_package_type.py
  delivery_carrier_package_measure_required/models/stock_picking.py
  delivery_carrier_package_measure_required/models/stock_quant_package.py
  delivery_carrier_package_measure_required/readme/CONTRIBUTORS.rst
  delivery_carrier_package_measure_required/readme/DESCRIPTION.rst
  delivery_carrier_package_measure_required/static/description/icon.png
  delivery_carrier_package_measure_required/static/description/index.html
  delivery_carrier_package_measure_required/tests/__init__.py
  delivery_carrier_package_measure_required/tests/test_delivery_carrier_package_measure_require.py
  delivery_carrier_package_measure_required/views/stock_package_type_views.xml
  delivery_carrier_package_measure_required/wizard/__init__.py
  delivery_carrier_package_measure_required/wizard/choose_delivery_package.py
  delivery_carrier_package_measure_required/wizard/choose_delivery_package.xml
  setup/delivery_carrier_package_measure_required/odoo/addons/delivery_carrier_package_measure_required
  setup/delivery_carrier_package_measure_required/setup.py
Labels: approved, ready to merge, bot is merging ⏳, no stale
