Repository OCA/delivery-carrier, pull requests merged in 2024-07, with the labels that each got.

#754 [16.0] [MIG] delivery_dropoff_site
  delivery_dropoff_site/README.rst
  delivery_dropoff_site/__init__.py
  delivery_dropoff_site/__manifest__.py
  delivery_dropoff_site/demo/delivery_carrier.xml
  delivery_dropoff_site/demo/dropoff_site.xml
  delivery_dropoff_site/demo/res_groups.xml
  delivery_dropoff_site/demo/resource_calendar.xml
  delivery_dropoff_site/i18n/delivery_dropoff_site.pot
  delivery_dropoff_site/i18n/fr.po
  delivery_dropoff_site/migrations/16.0.1.0.0/pre-migrate.py
  delivery_dropoff_site/models/__init__.py
  delivery_dropoff_site/models/delivery_carrier.py
  delivery_dropoff_site/models/dropoff_site.py
  delivery_dropoff_site/models/res_partner.py
  delivery_dropoff_site/models/sale_order.py
  delivery_dropoff_site/models/stock_move.py
  delivery_dropoff_site/models/stock_picking.py
  delivery_dropoff_site/models/stock_rule.py
  delivery_dropoff_site/readme/CONFIGURE.rst
  delivery_dropoff_site/readme/CONTRIBUTORS.rst
  delivery_dropoff_site/readme/CREDITS.rst
  delivery_dropoff_site/readme/DESCRIPTION.rst
  delivery_dropoff_site/readme/USAGE.rst
  delivery_dropoff_site/security/ir.model.access.csv
  delivery_dropoff_site/static/description/dropoff_site_form.png
  delivery_dropoff_site/static/description/dropoff_site_form_calendar.png
  delivery_dropoff_site/static/description/dropoff_site_tree.png
  delivery_dropoff_site/static/description/icon.png
  delivery_dropoff_site/static/description/index.html
  delivery_dropoff_site/static/description/sale_order_form.png
  delivery_dropoff_site/views/view_delivery_carrier.xml
  delivery_dropoff_site/views/view_dropoff_site.xml
  delivery_dropoff_site/views/view_sale_order.xml
  delivery_dropoff_site/views/view_stock_picking.xml
  setup/delivery_dropoff_site/odoo/addons/delivery_dropoff_site
  setup/delivery_dropoff_site/setup.py
Labels: needs review, approved, migration, bot is merging ⏳, stale

#845 [14.0][FIX]delivery_state: stock.picking delivery_state field invalid option
  delivery_state/models/stock_picking.py
  delivery_state/views/stock_picking_views.xml
Labels: approved, bot is merging ⏳

#847 [FIX] stock_picking_delivery_link: Don't override context value if no ship carrier
  stock_picking_delivery_link/models/stock_picking.py
  stock_picking_delivery_link/tests/test_delivery_link.py
Labels: enhancement, approved, bot is merging ⏳

#844 [14.0][IMP] delivery_state: set carrier with no updatable states
  delivery_state/README.rst
  delivery_state/__manifest__.py
  delivery_state/models/delivery_carrier.py
  delivery_state/readme/CONFIGURE.rst
  delivery_state/readme/CONTRIBUTORS.rst
  delivery_state/static/description/index.html
  delivery_state/tests/test_delivery_state.py
  delivery_state/views/delivery_carrier_views.xml
Labels: enhancement, needs review, approved, ready to merge, bot is merging ⏳

#820 delivery_roulier: fix call to dead code
  delivery_roulier/models/delivery_carrier.py
Labels: bot is merging ⏳

#842 [14.0][FIX] delivery_purchase : fix module install on demo data
  delivery_purchase/models/delivery_carrier.py
  delivery_purchase/models/purchase_order.py
  delivery_purchase/models/stock_picking.py
  delivery_purchase/readme/CONTRIBUTORS.rst
  delivery_purchase/tests/test_delivery_purchase.py
Labels: approved, bot is merging ⏳

#837 [16.0] [MIG] delivery_roulier_option
  delivery_roulier_option/README.rst
  delivery_roulier_option/__init__.py
  delivery_roulier_option/__manifest__.py
  delivery_roulier_option/data/delivery.xml
  delivery_roulier_option/i18n/delivery_roulier_option.pot
  delivery_roulier_option/i18n/es.po
  delivery_roulier_option/models/__init__.py
  delivery_roulier_option/models/delivery_option.py
  delivery_roulier_option/models/stock_picking.py
  delivery_roulier_option/models/stock_quant_package.py
  delivery_roulier_option/readme/CONTRIBUTORS.rst
  delivery_roulier_option/readme/DESCRIPTION.rst
  delivery_roulier_option/static/description/icon.png
  delivery_roulier_option/static/description/index.html
  setup/delivery_roulier_option/odoo/addons/delivery_roulier_option
  setup/delivery_roulier_option/setup.py
Labels: approved, bot is merging ⏳

#857 [16.0][FIX] partner_delivery_schedule: add the same class style as in the base report
  partner_delivery_schedule/views/report_shipping.xml
Labels: bot is merging ⏳

#858 [16.0][FIX] partner_delivery_zone: add the same class style as in the base report
  partner_delivery_zone/views/report_deliveryslip.xml
Labels: bot is merging ⏳

#859 [16.0][FIX] stock_picking_report_delivery_cost: add the same class style as in the base report
  stock_picking_report_delivery_cost/report/report_deliveryslip.xml
Labels: bot is merging ⏳

#826 [17.0][MIG] delivery_roulier: Migration to 17.0
  delivery_roulier/README.rst
  delivery_roulier/__init__.py
  delivery_roulier/__manifest__.py
  delivery_roulier/decorator.py
  delivery_roulier/demo/product.xml
  delivery_roulier/i18n/delivery_roulier.pot
  delivery_roulier/i18n/es.po
  delivery_roulier/i18n/it.po
  delivery_roulier/models/__init__.py
  delivery_roulier/models/delivery_carrier.py
  delivery_roulier/models/stock_move_line.py
  delivery_roulier/models/stock_picking.py
  delivery_roulier/models/stock_quant_package.py
  delivery_roulier/pyproject.toml
  delivery_roulier/readme/CONFIGURE.md
  delivery_roulier/readme/CONTRIBUTORS.md
  delivery_roulier/readme/DESCRIPTION.md
  delivery_roulier/readme/USAGE.md
  delivery_roulier/static/description/icon.png
  delivery_roulier/static/description/index.html
  delivery_roulier/tests/__init__.py
  delivery_roulier/tests/models.py
  delivery_roulier/tests/test_delivery_roulier.py
  requirements.txt
  test-requirements.txt
Labels: approved, bot is merging ⏳

#829 [17.0][MIG] delivery_roulier_option: Migration to 17.0
  delivery_roulier_option/README.rst
  delivery_roulier_option/__init__.py
  delivery_roulier_option/__manifest__.py
  delivery_roulier_option/data/delivery.xml
  delivery_roulier_option/i18n/delivery_roulier_option.pot
  delivery_roulier_option/i18n/es.po
  delivery_roulier_option/models/__init__.py
  delivery_roulier_option/models/delivery_option.py
  delivery_roulier_option/models/stock_picking.py
  delivery_roulier_option/models/stock_quant_package.py
  delivery_roulier_option/pyproject.toml
  delivery_roulier_option/readme/CONTRIBUTORS.md
  delivery_roulier_option/readme/DESCRIPTION.md
  delivery_roulier_option/static/description/icon.png
  delivery_roulier_option/static/description/index.html
Labels: approved, bot is merging ⏳

#861 [FIX] base_delibery_carrier_label test helper
  base_delivery_carrier_label/tests/carrier_label_case.py
Labels: approved, bot is merging ⏳

#860 [14.0][IMP] delivery_purchase: Add Original picking (delivery) (delivery_picking_orig_id) field to purchase order lines
  delivery_purchase/i18n/delivery_purchase.pot
  delivery_purchase/i18n/es.po
  delivery_purchase/models/purchase_order.py
  delivery_purchase/models/stock_picking.py
  delivery_purchase/tests/test_delivery_purchase.py
  delivery_purchase/views/purchase_order_view.xml
Labels: bot is merging ⏳

#866 [15.0][IMP] delivery_purchase: Add Original picking (delivery) (delivery_picking_orig_id) field to purchase order lines
  delivery_purchase/i18n/delivery_purchase.pot
  delivery_purchase/i18n/es.po
  delivery_purchase/models/purchase_order.py
  delivery_purchase/models/stock_picking.py
  delivery_purchase/tests/test_delivery_purchase.py
  delivery_purchase/views/purchase_order_view.xml
Labels: approved, bot is merging ⏳

#867 [16.0][IMP] delivery_purchase: Add Original picking (delivery) (delivery_picking_orig_id) field to purchase order lines
  delivery_purchase/i18n/delivery_purchase.pot
  delivery_purchase/i18n/es.po
  delivery_purchase/models/purchase_order.py
  delivery_purchase/models/stock_picking.py
  delivery_purchase/tests/test_delivery_purchase.py
  delivery_purchase/views/purchase_order_view.xml
Labels: approved, bot is merging ⏳

#840 [17.0][MIG] delivery_state
  delivery_state/README.rst
  delivery_state/__init__.py
  delivery_state/__manifest__.py
  delivery_state/data/ir_cron_data.xml
  delivery_state/data/mail_template.xml
  delivery_state/i18n/delivery_state.pot
  delivery_state/i18n/es.po
  delivery_state/i18n/fr.po
  delivery_state/i18n/it.po
  delivery_state/models/__init__.py
  delivery_state/models/delivery_carrier.py
  delivery_state/models/res_company.py
  delivery_state/models/res_config_settings.py
  delivery_state/models/stock_picking.py
  delivery_state/pyproject.toml
  delivery_state/readme/CONFIGURE.md
  delivery_state/readme/CONTRIBUTORS.md
  delivery_state/readme/DESCRIPTION.md
  delivery_state/readme/USAGE.md
  delivery_state/static/description/icon.png
  delivery_state/static/description/index.html
  delivery_state/tests/__init__.py
  delivery_state/tests/test_delivery_state.py
  delivery_state/views/res_config_settings_view.xml
  delivery_state/views/stock_picking_views.xml
Labels: approved, bot is merging ⏳

#684 [16.0][ADD] sale_order_warehouse_from_delivery_carrier
  sale_order_warehouse_from_delivery_carrier/README.rst
  sale_order_warehouse_from_delivery_carrier/__init__.py
  sale_order_warehouse_from_delivery_carrier/__manifest__.py
  sale_order_warehouse_from_delivery_carrier/models/__init__.py
  sale_order_warehouse_from_delivery_carrier/models/delivery_carrier.py
  sale_order_warehouse_from_delivery_carrier/models/sale_order.py
  sale_order_warehouse_from_delivery_carrier/readme/CONFIGURE.rst
  sale_order_warehouse_from_delivery_carrier/readme/CONTRIBUTORS.rst
  sale_order_warehouse_from_delivery_carrier/readme/DESCRIPTION.rst
  sale_order_warehouse_from_delivery_carrier/readme/USAGE.rst
  sale_order_warehouse_from_delivery_carrier/static/description/index.html
  sale_order_warehouse_from_delivery_carrier/tests/__init__.py
  sale_order_warehouse_from_delivery_carrier/tests/test_module_flow.py
  sale_order_warehouse_from_delivery_carrier/views/delivery_carrier_views.xml
  setup/sale_order_warehouse_from_delivery_carrier/odoo/addons/sale_order_warehouse_from_delivery_carrier
  setup/sale_order_warehouse_from_delivery_carrier/setup.py
Labels: work in progress, approved, ready to merge, bot is merging ⏳
