Repository OCA/delivery-carrier, pull requests merged in 2024-09, with the labels that each got.

#761 [FIX] delivery_package_type_number_parcels: make number of parcels computed
  delivery_package_type_number_parcels/models/stock_quant_package.py
  delivery_package_type_number_parcels/tests/test_package_type_number_parcels.py
Labels: help wanted, needs fixing, approved, ready to merge, bot is merging ⏳, stale

#875 [17.0][MIG] sale_order_warehouse_from_delivery_carrier: Migration to 17.0
  sale_order_warehouse_from_delivery_carrier/README.rst
  sale_order_warehouse_from_delivery_carrier/__init__.py
  sale_order_warehouse_from_delivery_carrier/__manifest__.py
  sale_order_warehouse_from_delivery_carrier/i18n/it.po
  sale_order_warehouse_from_delivery_carrier/i18n/nl.po
  sale_order_warehouse_from_delivery_carrier/i18n/sale_order_warehouse_from_delivery_carrier.pot
  sale_order_warehouse_from_delivery_carrier/models/__init__.py
  sale_order_warehouse_from_delivery_carrier/models/delivery_carrier.py
  sale_order_warehouse_from_delivery_carrier/models/sale_order.py
  sale_order_warehouse_from_delivery_carrier/pyproject.toml
  sale_order_warehouse_from_delivery_carrier/readme/CONFIGURE.md
  sale_order_warehouse_from_delivery_carrier/readme/CONTRIBUTORS.md
  sale_order_warehouse_from_delivery_carrier/readme/DESCRIPTION.md
  sale_order_warehouse_from_delivery_carrier/readme/USAGE.md
  sale_order_warehouse_from_delivery_carrier/static/description/icon.png
  sale_order_warehouse_from_delivery_carrier/static/description/index.html
  sale_order_warehouse_from_delivery_carrier/tests/__init__.py
  sale_order_warehouse_from_delivery_carrier/tests/test_module_flow.py
  sale_order_warehouse_from_delivery_carrier/views/delivery_carrier_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#674 [16.0][IMP] delivery_postlogistics: shipping labels and returns
  delivery_postlogistics/__init__.py
  delivery_postlogistics/models/delivery_carrier.py
  delivery_postlogistics/models/stock_picking.py
  delivery_postlogistics/views/stock.xml
  delivery_postlogistics/wizard/__init__.py
  delivery_postlogistics/wizard/stock_picking_return.py
Labels: approved, bot is merging ⏳, no stale

#878 [16.0][FIX] delivery_postlogistics: Change limit to 25 chars
  delivery_postlogistics/postlogistics/web_service.py
Labels: approved, bot is merging ⏳

#880 [14.0][FIX] delivery_price_method: fix crash in send_shipping()
  delivery_price_method/models/delivery_carrier.py
Labels: enhancement, needs review, approved, ready to merge, bot is merging ⏳

#881 [14.0][IMP] delivery_carrier_deposit: improve tree/form/search view of deposit.slip
  delivery_carrier_deposit/views/deposit_slip_view.xml
Labels: enhancement, needs review, approved, ready to merge, bot is merging ⏳

#876 [17.0][MIG] delivery_carrier_partner: Migration to 17.0
  delivery_carrier_partner/README.rst
  delivery_carrier_partner/__init__.py
  delivery_carrier_partner/__manifest__.py
  delivery_carrier_partner/i18n/delivery_carrier_partner.pot
  delivery_carrier_partner/i18n/es.po
  delivery_carrier_partner/i18n/fr.po
  delivery_carrier_partner/i18n/it.po
  delivery_carrier_partner/models/__init__.py
  delivery_carrier_partner/models/delivery_carrier.py
  delivery_carrier_partner/pyproject.toml
  delivery_carrier_partner/readme/CONTRIBUTORS.md
  delivery_carrier_partner/readme/DESCRIPTION.md
  delivery_carrier_partner/static/description/icon.png
  delivery_carrier_partner/static/description/index.html
  delivery_carrier_partner/views/delivery_carrier_views.xml
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#853 [16.0][BC] base_delivery_carrier_label: remove _set_a_default_package
  base_delivery_carrier_label/models/stock_picking.py
  base_delivery_carrier_label/readme/CONTRIBUTORS.rst
  delivery_roulier/__manifest__.py
  delivery_roulier/models/stock_quant_package.py
  delivery_roulier/tests/test_delivery_roulier.py
Labels: enhancement, approved, bot is merging ⏳

#884 [14.0][FIX] delivery_roulier_laposte_fr: fix crash when error must be displayed to non-admin user
  delivery_roulier_laposte_fr/models/stock_quant_package.py
Labels: approved, bot is merging ⏳

#803 [16.0][FIX] delivery_deliverea: Generate a deliverea return when sending to shipper
  delivery_deliverea/i18n/es.po
  delivery_deliverea/models/deliverea_request.py
  delivery_deliverea/models/delivery_carrier.py
  delivery_deliverea/models/stock_picking.py
  delivery_deliverea/tests/test_delivery_deliverea.py
  delivery_deliverea/views/stock_picking_views.xml
Labels: bot is merging ⏳, stale

#632 [16.0][MIG] delivery_schenker
  delivery_schenker/README.rst
  delivery_schenker/__init__.py
  delivery_schenker/__manifest__.py
  delivery_schenker/api/fat_bookingWebServiceV1_1.wsdl
  delivery_schenker/api/fat_trackingWebServiceV2.wsdl
  delivery_schenker/api/prod_bookingWebServiceV1_1.wsdl
  delivery_schenker/api/prod_trackingWebServiceV2.wsdl
  delivery_schenker/data/delivery_schenker_data.xml
  delivery_schenker/i18n/delivery_schenker.pot
  delivery_schenker/i18n/es.po
  delivery_schenker/migrations/16.0.1.0.0/post-migration.py
  delivery_schenker/models/__init__.py
  delivery_schenker/models/delivery_carrier.py
  delivery_schenker/models/schenker_request.py
  delivery_schenker/models/stock_package_type.py
  delivery_schenker/models/stock_picking.py
  delivery_schenker/readme/CONFIGURE.rst
  delivery_schenker/readme/CONTRIBUTORS.rst
  delivery_schenker/readme/DESCRIPTION.rst
  delivery_schenker/readme/INSTALL.rst
  delivery_schenker/readme/ROADMAP.rst
  delivery_schenker/readme/USAGE.rst
  delivery_schenker/static/description/icon.png
  delivery_schenker/static/description/icon.svg
  delivery_schenker/static/description/index.html
  delivery_schenker/tests/__init__.py
  delivery_schenker/views/delivery_schenker_view.xml
  delivery_schenker/views/stock_picking_views.xml
  requirements.txt
  setup/delivery_schenker/odoo/addons/delivery_schenker
  setup/delivery_schenker/setup.py
Labels: help wanted, needs fixing, approved, bot is merging ⏳, stale
