Repository OCA/delivery-carrier, pull requests merged in 2024-12, with the labels that each got.

#911 [15.0][IMP] partner_delivery_zone: Show delivery zone
  partner_delivery_zone/views/report_shipping.xml
Labels: approved, bot is merging ⏳

#913 [16.0][IMP] partner_delivery_zone: Show delivery zone
  partner_delivery_zone/views/report_shipping.xml
Labels: approved, bot is merging ⏳

#914 [FIX] [16.0] delivery_auto_refresh: Allow override carrier from wizard when changing partner
  delivery_auto_refresh/models/sale_order.py
Labels: needs review, approved, bot is merging ⏳

#758 [16.0][ADD] delivery_carrier_manual_price
  delivery_carrier_manual_price/README.rst
  delivery_carrier_manual_price/__init__.py
  delivery_carrier_manual_price/__manifest__.py
  delivery_carrier_manual_price/models/__init__.py
  delivery_carrier_manual_price/models/delivery_carrier.py
  delivery_carrier_manual_price/models/sale_order.py
  delivery_carrier_manual_price/readme/CONTRIBUTORS.rst
  delivery_carrier_manual_price/readme/DESCRIPTION.rst
  delivery_carrier_manual_price/readme/USAGE.rst
  delivery_carrier_manual_price/static/description/icon.png
  delivery_carrier_manual_price/static/description/index.html
  delivery_carrier_manual_price/tests/__init__.py
  delivery_carrier_manual_price/tests/test_delivery_carrier_manual_price.py
  delivery_carrier_manual_price/views/delivery_view.xml
  delivery_carrier_manual_price/wizard/__init__.py
  delivery_carrier_manual_price/wizard/choose_delivery_carrier.py
  delivery_carrier_manual_price/wizard/choose_delivery_carrier_views.xml
  setup/delivery_carrier_manual_price/odoo/addons/delivery_carrier_manual_price
  setup/delivery_carrier_manual_price/setup.py
Labels: help wanted, needs fixing, approved, ready to merge, bot is merging ⏳

#916 [17.0][MIG] delivery_carrier_manual_price
  delivery_carrier_manual_price/README.rst
  delivery_carrier_manual_price/__init__.py
  delivery_carrier_manual_price/__manifest__.py
  delivery_carrier_manual_price/i18n/delivery_carrier_manual_price.pot
  delivery_carrier_manual_price/models/__init__.py
  delivery_carrier_manual_price/models/delivery_carrier.py
  delivery_carrier_manual_price/models/sale_order.py
  delivery_carrier_manual_price/pyproject.toml
  delivery_carrier_manual_price/readme/CONTRIBUTORS.md
  delivery_carrier_manual_price/readme/DESCRIPTION.md
  delivery_carrier_manual_price/readme/USAGE.md
  delivery_carrier_manual_price/static/description/icon.png
  delivery_carrier_manual_price/static/description/index.html
  delivery_carrier_manual_price/tests/__init__.py
  delivery_carrier_manual_price/tests/test_delivery_carrier_manual_price.py
  delivery_carrier_manual_price/views/delivery_view.xml
  delivery_carrier_manual_price/wizard/__init__.py
  delivery_carrier_manual_price/wizard/choose_delivery_carrier.py
  delivery_carrier_manual_price/wizard/choose_delivery_carrier_views.xml
Labels: approved, bot is merging ⏳

#893 [18.0] [MIG] delivery_carrier_partner
  delivery_carrier_partner/README.rst
  delivery_carrier_partner/__init__.py
  delivery_carrier_partner/__manifest__.py
  delivery_carrier_partner/i18n/delivery_carrier_partner.pot
  delivery_carrier_partner/i18n/es.po
  delivery_carrier_partner/i18n/fr.po
  delivery_carrier_partner/i18n/it.po
  delivery_carrier_partner/models/__init__.py
  delivery_carrier_partner/models/delivery_carrier.py
  delivery_carrier_partner/pyproject.toml
  delivery_carrier_partner/readme/CONTRIBUTORS.md
  delivery_carrier_partner/readme/DESCRIPTION.md
  delivery_carrier_partner/static/description/icon.png
  delivery_carrier_partner/static/description/index.html
  delivery_carrier_partner/tests/__init__.py
  delivery_carrier_partner/tests/test_delivery_carrier_partner.py
  delivery_carrier_partner/views/delivery_carrier_views.xml
Labels: approved, migration, ready to merge, bot is merging ⏳

#921 [18.0][MIG] delivery_package_fee: Migration to 18.0
  delivery_package_fee/README.rst
  delivery_package_fee/__init__.py
  delivery_package_fee/__manifest__.py
  delivery_package_fee/i18n/delivery_package_fee.pot
  delivery_package_fee/i18n/es.po
  delivery_package_fee/i18n/fr.po
  delivery_package_fee/i18n/it.po
  delivery_package_fee/models/__init__.py
  delivery_package_fee/models/delivery_carrier.py
  delivery_package_fee/models/delivery_package_fee.py
  delivery_package_fee/models/sale_order.py
  delivery_package_fee/models/sale_order_line.py
  delivery_package_fee/models/stock_picking.py
  delivery_package_fee/pyproject.toml
  delivery_package_fee/readme/CONFIGURE.md
  delivery_package_fee/readme/CONTRIBUTORS.md
  delivery_package_fee/readme/CREDITS.md
  delivery_package_fee/readme/DESCRIPTION.md
  delivery_package_fee/security/ir.model.access.csv
  delivery_package_fee/static/description/icon.png
  delivery_package_fee/static/description/index.html
  delivery_package_fee/tests/__init__.py
  delivery_package_fee/tests/test_package_fee.py
  delivery_package_fee/views/delivery_carrier_views.xml
Labels: approved, bot is merging ⏳

#920 [18.0][MIG] delivery_carrier_pricelist: Migration to 18.0
  delivery_carrier_pricelist/README.rst
  delivery_carrier_pricelist/__init__.py
  delivery_carrier_pricelist/__manifest__.py
  delivery_carrier_pricelist/i18n/delivery_carrier_pricelist.pot
  delivery_carrier_pricelist/i18n/es.po
  delivery_carrier_pricelist/models/__init__.py
  delivery_carrier_pricelist/models/delivery_carrier.py
  delivery_carrier_pricelist/models/stock_picking.py
  delivery_carrier_pricelist/pyproject.toml
  delivery_carrier_pricelist/readme/CONTRIBUTORS.md
  delivery_carrier_pricelist/readme/CREDITS.md
  delivery_carrier_pricelist/readme/DESCRIPTION.md
  delivery_carrier_pricelist/security/ir.model.access.csv
  delivery_carrier_pricelist/static/description/icon.png
  delivery_carrier_pricelist/static/description/index.html
  delivery_carrier_pricelist/tests/__init__.py
  delivery_carrier_pricelist/tests/test_delivery_pricelist.py
  delivery_carrier_pricelist/wizards/__init__.py
  delivery_carrier_pricelist/wizards/choose_delivery_carrier.py
Labels: approved, bot is merging ⏳
