Repository OCA/delivery-carrier, pull requests merged in 2024-04, with the labels that each got.

#766 [16.0][MIG] delivery_multi_destination: Migration to version 16.0
  delivery_multi_destination/README.rst
  delivery_multi_destination/__init__.py
  delivery_multi_destination/__manifest__.py
  delivery_multi_destination/demo/delivery_carrier_demo.xml
  delivery_multi_destination/i18n/cs_CZ.po
  delivery_multi_destination/i18n/de.po
  delivery_multi_destination/i18n/delivery_multi_destination.pot
  delivery_multi_destination/i18n/es.po
  delivery_multi_destination/i18n/fr.po
  delivery_multi_destination/i18n/it.po
  delivery_multi_destination/i18n/nl.po
  delivery_multi_destination/i18n/nl_NL.po
  delivery_multi_destination/i18n/pt_BR.po
  delivery_multi_destination/i18n/sl.po
  delivery_multi_destination/i18n/zh_CN.po
  delivery_multi_destination/models/__init__.py
  delivery_multi_destination/models/delivery_carrier.py
  delivery_multi_destination/readme/CONFIGURE.rst
  delivery_multi_destination/readme/CONTRIBUTORS.rst
  delivery_multi_destination/readme/DESCRIPTION.rst
  delivery_multi_destination/readme/ROADMAP.rst
  delivery_multi_destination/readme/USAGE.rst
  delivery_multi_destination/static/description/icon.png
  delivery_multi_destination/static/description/index.html
  delivery_multi_destination/tests/__init__.py
  delivery_multi_destination/tests/test_delivery_multi_destination.py
  delivery_multi_destination/views/delivery_carrier_view.xml
  setup/delivery_multi_destination/odoo/addons/delivery_multi_destination
  setup/delivery_multi_destination/setup.py
Labels: needs review, migration, bot is merging ⏳

#790 [14.0] [FIX] delivery_auto_refresh: dynamic carrier line
  delivery_auto_refresh/README.rst
  delivery_auto_refresh/__manifest__.py
  delivery_auto_refresh/models/sale_order.py
  delivery_auto_refresh/static/description/index.html
  delivery_auto_refresh/tests/test_delivery_auto_refresh.py
Labels: approved, bot is merging ⏳

#789 [16.0][FIX] stock_picking_delivery_link: Error on _set_delivery_packge_type override
  stock_picking_delivery_link/models/stock_picking.py
Labels: enhancement, needs review, approved, bot is merging ⏳
