Repository OCA/delivery-carrier, pull requests merged in 2024-03, with the labels that each got.

#774 [16.0][IMP] delivery_driver: Flag driver in partner
  delivery_driver/README.rst
  delivery_driver/__manifest__.py
  delivery_driver/i18n/delivery_driver.pot
  delivery_driver/i18n/es.po
  delivery_driver/migrations/16.0.1.0.1/post-migration.py
  delivery_driver/models/__init__.py
  delivery_driver/models/delivery_carrier.py
  delivery_driver/models/res_partner.py
  delivery_driver/models/stock_move_line.py
  delivery_driver/models/stock_picking.py
  delivery_driver/readme/USAGE.md
  delivery_driver/static/description/index.html
  delivery_driver/tests/test_delivery_driver.py
  delivery_driver/views/res_partner.xml
  delivery_driver/views/stock_move_line.xml
  delivery_driver/views/stock_picking.xml
Labels: approved, ready to merge, bot is merging ⏳

#783 [FIX] delivery_driver: wrong model name
  delivery_driver/migrations/16.0.1.0.1/post-migration.py
Labels: enhancement, needs review, bot is merging ⏳

#775 [IMP] delivery_driver_stock_picking_batch: Show only name in drivers
  delivery_driver_stock_picking_batch/views/stock_picking_batch.xml
Labels: needs review, approved, ready to merge, bot is merging ⏳

#772 [14.0][FIX] delivery_price_product_domain: fix shipping without rule
  delivery_price_product_domain/models/delivery_carrier.py
  delivery_price_product_domain/tests/test_delivery_price_product_domain.py
Labels: enhancement, needs review, approved, ready to merge, bot is merging ⏳

#723 [14.0][IMP] delivery_schenker : submit booking
  delivery_schenker/models/delivery_carrier.py
  delivery_schenker/models/schenker_request.py
  delivery_schenker/tests/common.py
  delivery_schenker/views/delivery_schenker_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#777 [15.0][IMP] delivery_package_number: Ask only once for the number of packages in wizard.
  delivery_package_number/README.rst
  delivery_package_number/__manifest__.py
  delivery_package_number/models/stock_picking.py
  delivery_package_number/readme/CONTRIBUTORS.rst
  delivery_package_number/static/description/index.html
  delivery_package_number/tests/test_delivery_package_number.py
  delivery_package_number/wizard/__init__.py
  delivery_package_number/wizard/stock_backorder_confirmation.py
  delivery_package_number/wizard/stock_backorder_confirmation_views.xml
  delivery_package_number/wizard/stock_immediate_transfer_views.xml
  delivery_package_number/wizard/stock_inmediate_transfer.py
  delivery_package_number/wizard/stock_number_package_mixin.py
  delivery_package_number/wizard/stock_number_package_validate_wiz.py
Labels: approved, bot is merging ⏳

#791 [14.0] [FIX] delivery_auto_refresh: manually delete delivery line
  delivery_auto_refresh/models/sale_order.py
  delivery_auto_refresh/tests/test_delivery_auto_refresh.py
Labels: approved, bot is merging ⏳
