Repository OCA/delivery-carrier, pull requests merged in 2024-11, with the labels that each got.

#898 [FIX] delivery_postlogistics: raise exception when no token received
  delivery_postlogistics/postlogistics/web_service.py
  delivery_postlogistics/tests/fixtures/cassettes/test_token_error.yaml
  delivery_postlogistics/tests/test_postlogistics.py
Labels: approved, bot is merging ⏳

#905 [16.0][FW] delivery_postlogistics: multiple ports from 14.0
  .oca/oca-port/blacklist/delivery_postlogistics.json
  delivery_postlogistics/models/stock_picking.py
  delivery_postlogistics/postlogistics/web_service.py
  delivery_postlogistics/tests/test_sanitize_values.py
  delivery_postlogistics/views/delivery.xml
Labels: approved, ready to merge, bot is merging ⏳

#839 [17.0][MIG] delivery_package_number: Migration to 17.0
  delivery_package_number/README.rst
  delivery_package_number/__init__.py
  delivery_package_number/__manifest__.py
  delivery_package_number/data/paperformat_data.xml
  delivery_package_number/i18n/delivery_package_number.pot
  delivery_package_number/i18n/es.po
  delivery_package_number/i18n/sl.po
  delivery_package_number/models/__init__.py
  delivery_package_number/models/stock_picking.py
  delivery_package_number/models/stock_picking_type.py
  delivery_package_number/pyproject.toml
  delivery_package_number/readme/CONTRIBUTORS.md
  delivery_package_number/readme/DESCRIPTION.md
  delivery_package_number/readme/USAGE.md
  delivery_package_number/reports/report_package_number.xml
  delivery_package_number/security/ir.model.access.csv
  delivery_package_number/static/description/icon.png
  delivery_package_number/static/description/index.html
  delivery_package_number/tests/__init__.py
  delivery_package_number/tests/test_delivery_package_number.py
  delivery_package_number/views/stock_picking_type_views.xml
  delivery_package_number/views/stock_picking_views.xml
  delivery_package_number/wizard/__init__.py
  delivery_package_number/wizard/stock_backorder_confirmation.py
  delivery_package_number/wizard/stock_number_package_validate_wiz.py
  delivery_package_number/wizard/stock_number_package_validate_wiz_view.xml
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳
