Repository OCA/delivery-carrier, pull requests merged in 2024-06, with the labels that each got.

#799 [16.0][IMP-FIX] delivery_auto_refresh - performance & compatibility & cleanup
  delivery_auto_refresh/__manifest__.py
  delivery_auto_refresh/migrations/16.0.2.0.0/post-migration.py
  delivery_auto_refresh/models/__init__.py
  delivery_auto_refresh/models/res_company.py
  delivery_auto_refresh/models/res_config_settings.py
  delivery_auto_refresh/models/sale_order.py
  delivery_auto_refresh/models/stock_picking.py
  delivery_auto_refresh/readme/CONFIGURE.rst
  delivery_auto_refresh/readme/CONTRIBUTORS.rst
  delivery_auto_refresh/readme/ROADMAP.rst
  delivery_auto_refresh/tests/__init__.py
  delivery_auto_refresh/tests/test_delivery_auto_refresh.py
  delivery_auto_refresh/tests/test_sale_order_carrier_auto_assign.py
  delivery_auto_refresh/views/res_config_settings_views.xml
Labels: bot is merging ⏳

#827 [17.0][MIG] delivery_carrier_account: Migration to 17.0
  delivery_carrier_account/README.rst
  delivery_carrier_account/__init__.py
  delivery_carrier_account/__manifest__.py
  delivery_carrier_account/i18n/delivery_carrier_account.pot
  delivery_carrier_account/i18n/es.po
  delivery_carrier_account/i18n/it.po
  delivery_carrier_account/models/__init__.py
  delivery_carrier_account/models/carrier_account.py
  delivery_carrier_account/models/delivery_carrier.py
  delivery_carrier_account/models/stock_picking.py
  delivery_carrier_account/pyproject.toml
  delivery_carrier_account/readme/CONTRIBUTORS.md
  delivery_carrier_account/readme/DESCRIPTION.md
  delivery_carrier_account/security/carrier_security.xml
  delivery_carrier_account/security/ir.model.access.csv
  delivery_carrier_account/static/description/icon.png
  delivery_carrier_account/static/description/index.html
  delivery_carrier_account/tests/__init__.py
  delivery_carrier_account/tests/test_carrier_account.py
  delivery_carrier_account/views/carrier_account.xml
  delivery_carrier_account/views/delivery_carrier.xml
Labels: needs review, approved, migration, bot is merging ⏳

#728 [16.0][FIX] postlogistics: use parent name on customer if not set
  delivery_postlogistics/postlogistics/web_service.py
Labels: approved, ready to merge, bot is merging ⏳, stale

#813 [16.0][MIG] delivery_correos_express: Migration to 16.0
  delivery_correos_express/README.rst
  delivery_correos_express/__init__.py
  delivery_correos_express/__manifest__.py
  delivery_correos_express/doc/GrabacionEnvios/DC_SP_ apiRestSeguimientoEnviosk8s_v01.00.pdf
  delivery_correos_express/doc/GrabacionEnvios/DC_SP_WS_GrabacionEnviosRest_v03.07.pdf
  delivery_correos_express/doc/GrabacionEnvios/DC_SP_WS_ListEnviosRest_v01.01.pdf
  delivery_correos_express/doc/GrabacionEnvios/DC_SP_WS_apiRestEtiquetaTransporte_v01.01.pdf
  delivery_correos_express/doc/GrabacionRecogidas/DC_SP_Seguimiento_Recogidak8s_v01.00.pdf
  delivery_correos_express/doc/GrabacionRecogidas/DC_SP_WS_GrabacionRecogidaRest_v1.4.pdf
  delivery_correos_express/i18n/delivery_correos_express.pot
  delivery_correos_express/i18n/es.po
  delivery_correos_express/models/__init__.py
  delivery_correos_express/models/correos_express_request.py
  delivery_correos_express/models/delivery_carrier.py
  delivery_correos_express/models/stock_picking.py
  delivery_correos_express/readme/CONFIGURE.rst
  delivery_correos_express/readme/CONTRIBUTORS.rst
  delivery_correos_express/readme/DESCRIPTION.rst
  delivery_correos_express/readme/INSTALL.rst
  delivery_correos_express/readme/ROADMAP.rst
  delivery_correos_express/readme/USAGE.rst
  delivery_correos_express/static/description/icon.png
  delivery_correos_express/static/description/index.html
  delivery_correos_express/tests/__init__.py
  delivery_correos_express/tests/test_delivery_correos_express.py
  delivery_correos_express/views/delivery_carrier_view.xml
  delivery_correos_express/views/stock_picking_views.xml
  setup/delivery_correos_express/odoo/addons/delivery_correos_express
  setup/delivery_correos_express/setup.py
Labels: approved, bot is merging ⏳

#832 [14.0][FIX] delivery_ups_oca: update delivery state
  delivery_ups_oca/models/ups_request.py
Labels: approved, ready to merge, bot is merging ⏳

#822 [15.0][IMP] partner_delivery_zone: zone info in stock move
  partner_delivery_zone/models/stock_move.py
Labels: approved, ready to merge, bot is merging ⏳
