Repository OCA/delivery-carrier, pull requests merged in 2025-03, with the labels that each got.

#990 [17.0][MIG] delivery_carrier_multi_zip: Migration to 17.0
  delivery_carrier_multi_zip/README.rst
  delivery_carrier_multi_zip/__init__.py
  delivery_carrier_multi_zip/__manifest__.py
  delivery_carrier_multi_zip/i18n/de.po
  delivery_carrier_multi_zip/i18n/delivery_carrier_multi_zip.pot
  delivery_carrier_multi_zip/i18n/es.po
  delivery_carrier_multi_zip/models/__init__.py
  delivery_carrier_multi_zip/models/delivery_carrier.py
  delivery_carrier_multi_zip/pyproject.toml
  delivery_carrier_multi_zip/readme/CONFIGURE.md
  delivery_carrier_multi_zip/readme/CONTRIBUTORS.md
  delivery_carrier_multi_zip/readme/DESCRIPTION.md
  delivery_carrier_multi_zip/security/ir.model.access.csv
  delivery_carrier_multi_zip/static/description/icon.png
  delivery_carrier_multi_zip/static/description/index.html
  delivery_carrier_multi_zip/tests/__init__.py
  delivery_carrier_multi_zip/tests/test_delivery_carrier_multi_zip.py
  delivery_carrier_multi_zip/views/delivery_carrier_view.xml
Labels: needs review, migration, bot is merging ⏳

#863 [14.0][ADD] delivery_purchase_label
  delivery_purchase_label/__init__.py
  delivery_purchase_label/__manifest__.py
  delivery_purchase_label/data/stock_picking_type.xml
  delivery_purchase_label/models/__init__.py
  delivery_purchase_label/models/delivery_carrier.py
  delivery_purchase_label/models/mail_compose_message.py
  delivery_purchase_label/models/purchase_order.py
  delivery_purchase_label/models/stock_picking.py
  delivery_purchase_label/readme/CONFIGURE.rst
  delivery_purchase_label/readme/CONTRIBUTORS.rst
  delivery_purchase_label/readme/DESCRIPTION.rst
  delivery_purchase_label/tests/__init__.py
  delivery_purchase_label/tests/test_delivery_purchase_label.py
  delivery_purchase_label/views/delivery_carrier.xml
  delivery_purchase_label/views/purchase_order_views.xml
  setup/delivery_purchase_label/odoo/addons/delivery_purchase_label
  setup/delivery_purchase_label/setup.py
Labels: approved, bot is merging ⏳, stale

#992 [17.0][FIX] delivery_roulier: calls to is_roulier()
  delivery_roulier/models/delivery_carrier.py
Labels: bot is merging ⏳

#897 [16][MIG] delivery_roulier_dpd_fr
  delivery_roulier_dpd_fr/README.rst
  delivery_roulier_dpd_fr/__init__.py
  delivery_roulier_dpd_fr/__manifest__.py
  delivery_roulier_dpd_fr/data/delivery_carrier.xml
  delivery_roulier_dpd_fr/data/product.product.xml
  delivery_roulier_dpd_fr/demo/carrier_account.xml
  delivery_roulier_dpd_fr/models/__init__.py
  delivery_roulier_dpd_fr/models/carrier_account.py
  delivery_roulier_dpd_fr/models/delivery_carrier.py
  delivery_roulier_dpd_fr/models/stock_picking.py
  delivery_roulier_dpd_fr/models/stock_quant_package.py
  delivery_roulier_dpd_fr/readme/CONFIGURE.rst
  delivery_roulier_dpd_fr/readme/CONTRIBUTORS.rst
  delivery_roulier_dpd_fr/readme/DESCRIPTION.rst
  delivery_roulier_dpd_fr/static/description/icon.png
  delivery_roulier_dpd_fr/static/description/index.html
  delivery_roulier_dpd_fr/views/carrier_account_views.xml
  requirements.txt
  setup/delivery_roulier_dpd_fr/odoo/addons/delivery_roulier_dpd_fr
  setup/delivery_roulier_dpd_fr/setup.py
Labels: approved, bot is merging ⏳

#899 [16][ADD] delivery_roulier_geodis_fr
  delivery_package_fee/tests/test_package_fee.py
  delivery_roulier_geodis_fr/README.rst
  delivery_roulier_geodis_fr/__init__.py
  delivery_roulier_geodis_fr/__manifest__.py
  delivery_roulier_geodis_fr/data/delivery.xml
  delivery_roulier_geodis_fr/data/product.xml
  delivery_roulier_geodis_fr/data/sequence_geodis.xml
  delivery_roulier_geodis_fr/models/__init__.py
  delivery_roulier_geodis_fr/models/carrier_account.py
  delivery_roulier_geodis_fr/models/delivery_carrier.py
  delivery_roulier_geodis_fr/models/delivery_carrier_agency.py
  delivery_roulier_geodis_fr/models/deposit.py
  delivery_roulier_geodis_fr/models/stock_picking.py
  delivery_roulier_geodis_fr/models/stock_quant_package.py
  delivery_roulier_geodis_fr/static/src/img/icon.png
  delivery_roulier_geodis_fr/static/src/img/logo.jpg
  delivery_roulier_geodis_fr/tests/__init__.py
  delivery_roulier_geodis_fr/tests/cassettes/GeodisFrLabelCase.test_addresses.yaml
  delivery_roulier_geodis_fr/tests/cassettes/GeodisFrLabelCase.test_labels.yaml
  delivery_roulier_geodis_fr/tests/test_geodis_labels.py
  delivery_roulier_geodis_fr/views/carrier_account_views.xml
  delivery_roulier_geodis_fr/views/delivery_carrier_agency_views.xml
  setup/delivery_roulier_geodis_fr/odoo/addons/delivery_roulier_geodis_fr
  setup/delivery_roulier_geodis_fr/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#985 [18.0] delivery_carrier_label_default: Migration to 18.0
  delivery_carrier_label_default/README.rst
  delivery_carrier_label_default/__init__.py
  delivery_carrier_label_default/__manifest__.py
  delivery_carrier_label_default/i18n/delivery_carrier_label_default.pot
  delivery_carrier_label_default/models/__init__.py
  delivery_carrier_label_default/models/stock_picking.py
  delivery_carrier_label_default/pyproject.toml
  delivery_carrier_label_default/readme/CONTRIBUTORS.md
  delivery_carrier_label_default/readme/CREDITS.md
  delivery_carrier_label_default/readme/DESCRIPTION.md
  delivery_carrier_label_default/readme/ROADMAP.md
  delivery_carrier_label_default/static/description/icon.svg
  delivery_carrier_label_default/static/description/index.html
  delivery_carrier_label_default/tests/__init__.py
  delivery_carrier_label_default/tests/common.py
  delivery_carrier_label_default/tests/test_print_label.py
  delivery_carrier_label_default/views/report_default_label.xml
  delivery_carrier_label_default/views/reports.xml
Labels: needs review, approved, migration, ready to merge

#1000 [16.0][FIX] delivery_purchase: expected singleton
  delivery_purchase/models/purchase_order.py
Labels: enhancement, needs review, approved, bot is merging ⏳

#962 [18.0][MIG] delivery_carrier_manual_weight: Migration to 18.0
  delivery_carrier_manual_weight/README.rst
  delivery_carrier_manual_weight/__init__.py
  delivery_carrier_manual_weight/__manifest__.py
  delivery_carrier_manual_weight/i18n/delivery_carrier_manual_weight.pot
  delivery_carrier_manual_weight/i18n/it.po
  delivery_carrier_manual_weight/models/__init__.py
  delivery_carrier_manual_weight/models/delivery_carrier.py
  delivery_carrier_manual_weight/models/stock_picking.py
  delivery_carrier_manual_weight/pyproject.toml
  delivery_carrier_manual_weight/readme/CONTRIBUTORS.md
  delivery_carrier_manual_weight/readme/DESCRIPTION.md
  delivery_carrier_manual_weight/readme/USAGE.md
  delivery_carrier_manual_weight/static/description/icon.png
  delivery_carrier_manual_weight/static/description/index.html
  delivery_carrier_manual_weight/tests/__init__.py
  delivery_carrier_manual_weight/tests/test_delivery_carrier_manual_weight.py
  delivery_carrier_manual_weight/views/delivery_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#932 [18.0][MIG] delivery_package_number: Migration to 18.0
  delivery_package_number/README.rst
  delivery_package_number/__init__.py
  delivery_package_number/__manifest__.py
  delivery_package_number/data/paperformat_data.xml
  delivery_package_number/i18n/delivery_package_number.pot
  delivery_package_number/i18n/es.po
  delivery_package_number/i18n/it.po
  delivery_package_number/i18n/sl.po
  delivery_package_number/models/__init__.py
  delivery_package_number/models/stock_picking.py
  delivery_package_number/models/stock_picking_type.py
  delivery_package_number/pyproject.toml
  delivery_package_number/readme/CONTRIBUTORS.md
  delivery_package_number/readme/DESCRIPTION.md
  delivery_package_number/readme/USAGE.md
  delivery_package_number/reports/report_package_number.xml
  delivery_package_number/security/ir.model.access.csv
  delivery_package_number/static/description/icon.png
  delivery_package_number/static/description/index.html
  delivery_package_number/tests/__init__.py
  delivery_package_number/tests/test_delivery_package_number.py
  delivery_package_number/views/stock_picking_type_views.xml
  delivery_package_number/views/stock_picking_views.xml
  delivery_package_number/wizard/__init__.py
  delivery_package_number/wizard/stock_backorder_confirmation.py
  delivery_package_number/wizard/stock_number_package_validate_wiz.py
  delivery_package_number/wizard/stock_number_package_validate_wiz_view.xml
Labels: needs review, approved, migration, bot is merging ⏳

#1004 [18.0][FIX] pre-commit
  stock_picking_delivery_link/README.rst
  stock_picking_delivery_link/readme/CONTRIBUTORS.md
  stock_picking_delivery_link/readme/CONTRIBUTORS.rst
  stock_picking_delivery_link/readme/DESCRIPTION.md
  stock_picking_delivery_link/readme/DESCRIPTION.rst
  stock_picking_delivery_link/static/description/index.html
Labels: approved, bot is merging ⏳

#906 [17.0][MIG] delivery_correos_express: Migration to 17.0
  delivery_correos_express/README.rst
  delivery_correos_express/__init__.py
  delivery_correos_express/__manifest__.py
  delivery_correos_express/doc/GrabacionEnvios/DC_SP_ apiRestSeguimientoEnviosk8s_v01.03.pdf
  delivery_correos_express/doc/GrabacionEnvios/DC_SP_WS_GrabacionEnviosRest_v03.12.pdf
  delivery_correos_express/doc/GrabacionEnvios/DC_SP_WS_ListEnviosRest_v01.01.pdf
  delivery_correos_express/doc/GrabacionEnvios/DC_SP_WS_apiRestEtiquetaTransporte_v01.01.pdf
  delivery_correos_express/doc/GrabacionRecogidas/DC_SP_Seguimiento_Recogidak8s_v01.00.pdf
  delivery_correos_express/doc/GrabacionRecogidas/DC_SP_WS_GrabacionRecogidaRest_v1.08.pdf
  delivery_correos_express/i18n/delivery_correos_express.pot
  delivery_correos_express/i18n/es.po
  delivery_correos_express/i18n/it.po
  delivery_correos_express/models/__init__.py
  delivery_correos_express/models/correos_express_request.py
  delivery_correos_express/models/delivery_carrier.py
  delivery_correos_express/models/stock_picking.py
  delivery_correos_express/pyproject.toml
  delivery_correos_express/readme/CONFIGURE.md
  delivery_correos_express/readme/CONTRIBUTORS.md
  delivery_correos_express/readme/DESCRIPTION.md
  delivery_correos_express/readme/INSTALL.md
  delivery_correos_express/readme/ROADMAP.md
  delivery_correos_express/readme/USAGE.md
  delivery_correos_express/static/description/icon.png
  delivery_correos_express/static/description/index.html
  delivery_correos_express/tests/__init__.py
  delivery_correos_express/tests/test_correos_express_request.py
  delivery_correos_express/tests/test_delivery_correos_express.py
  delivery_correos_express/views/delivery_carrier_view.xml
  delivery_correos_express/views/stock_picking_views.xml
  requirements.txt
Labels: approved, ready to merge, bot is merging ⏳

#1003 [18][MIG] delivery_roulier
  delivery_roulier/README.rst
  delivery_roulier/__init__.py
  delivery_roulier/__manifest__.py
  delivery_roulier/decorator.py
  delivery_roulier/demo/product.xml
  delivery_roulier/i18n/delivery_roulier.pot
  delivery_roulier/i18n/es.po
  delivery_roulier/i18n/it.po
  delivery_roulier/models/__init__.py
  delivery_roulier/models/delivery_carrier.py
  delivery_roulier/models/stock_move_line.py
  delivery_roulier/models/stock_picking.py
  delivery_roulier/models/stock_quant_package.py
  delivery_roulier/pyproject.toml
  delivery_roulier/readme/CONFIGURE.md
  delivery_roulier/readme/CONTRIBUTORS.md
  delivery_roulier/readme/DESCRIPTION.md
  delivery_roulier/readme/USAGE.md
  delivery_roulier/static/description/icon.png
  delivery_roulier/static/description/index.html
  delivery_roulier/tests/__init__.py
  delivery_roulier/tests/models.py
  delivery_roulier/tests/test_delivery_roulier.py
  delivery_roulier/views/stock_quant_package.xml
  requirements.txt
Labels: needs review, approved, migration, bot is merging ⏳
