Repository OCA/delivery-carrier, pull requests merged in 2025-07, with the labels that each got.

#1022 [18.0] [MIG] delivery_package_type_shipping_weight: Migration to 18.0
  delivery_package_type_shipping_weight/README.rst
  delivery_package_type_shipping_weight/__init__.py
  delivery_package_type_shipping_weight/__manifest__.py
  delivery_package_type_shipping_weight/i18n/delivery_package_default_shipping_weight.pot
  delivery_package_type_shipping_weight/i18n/it.po
  delivery_package_type_shipping_weight/i18n/tr.po
  delivery_package_type_shipping_weight/models/__init__.py
  delivery_package_type_shipping_weight/models/delivery_carrier.py
  delivery_package_type_shipping_weight/models/sale_order.py
  delivery_package_type_shipping_weight/models/stock_package_type.py
  delivery_package_type_shipping_weight/models/stock_picking.py
  delivery_package_type_shipping_weight/models/stock_quant_package.py
  delivery_package_type_shipping_weight/pyproject.toml
  delivery_package_type_shipping_weight/readme/CONTRIBUTORS.md
  delivery_package_type_shipping_weight/readme/CREDITS.md
  delivery_package_type_shipping_weight/readme/DESCRIPTION.md
  delivery_package_type_shipping_weight/static/description/icon.png
  delivery_package_type_shipping_weight/static/description/index.html
  delivery_package_type_shipping_weight/tests/__init__.py
  delivery_package_type_shipping_weight/tests/test_delivery_package_type_shipping_weight.py
  delivery_package_type_shipping_weight/views/stock_package_type_views.xml
  delivery_package_type_shipping_weight/wizard/__init__.py
  delivery_package_type_shipping_weight/wizard/choose_delivery_package.py
Labels: bot is merging ⏳

#1021 [ADD][18.0] delivery_carrier_picking_valid
  delivery_carrier_picking_valid/README.rst
  delivery_carrier_picking_valid/__init__.py
  delivery_carrier_picking_valid/__manifest__.py
  delivery_carrier_picking_valid/models/__init__.py
  delivery_carrier_picking_valid/models/delivery_carrier.py
  delivery_carrier_picking_valid/pyproject.toml
  delivery_carrier_picking_valid/readme/CONTRIBUTORS.md
  delivery_carrier_picking_valid/readme/DESCRIPTION.md
  delivery_carrier_picking_valid/static/description/index.html
  delivery_carrier_picking_valid/tests/__init__.py
  delivery_carrier_picking_valid/tests/common.py
  delivery_carrier_picking_valid/tests/test_picking_valid.py
Labels: approved, ready to merge, bot is merging ⏳

#1005 [17.0][ADD] delivery_cbl: CBL carrier integration
  delivery_cbl/README.rst
  delivery_cbl/__init__.py
  delivery_cbl/__manifest__.py
  delivery_cbl/data/ir_cron.xml
  delivery_cbl/i18n/ca.po
  delivery_cbl/i18n/es.po
  delivery_cbl/models/__init__.py
  delivery_cbl/models/cbl_request.py
  delivery_cbl/models/delivery_carrier.py
  delivery_cbl/models/stock_picking.py
  delivery_cbl/pyproject.toml
  delivery_cbl/readme/CONFIGURE.md
  delivery_cbl/readme/CONTRIBUTORS.md
  delivery_cbl/readme/DESCRIPTION.md
  delivery_cbl/readme/ROADMAP.md
  delivery_cbl/readme/USAGE.md
  delivery_cbl/report/cbl_manifest.xml
  delivery_cbl/security/ir.model.access.csv
  delivery_cbl/static/description/icon.png
  delivery_cbl/static/description/index.html
  delivery_cbl/tests/__init__.py
  delivery_cbl/tests/test_delivery_cbl.py
  delivery_cbl/views/delivery_carrier_view.xml
  delivery_cbl/views/stock_picking_views.xml
  delivery_cbl/wizard/__init__.py
  delivery_cbl/wizard/manifest_wizard.py
  delivery_cbl/wizard/wizard_confirm_cbl_pickings.py
  delivery_cbl/wizard/wizard_confirm_cbl_pickings_view.xml
Labels: approved, bot is merging ⏳

#1015 [17.0] [ADD] delivery_carrier_global_manifest
  delivery_carrier_global_manifest/README.rst
  delivery_carrier_global_manifest/__init__.py
  delivery_carrier_global_manifest/__manifest__.py
  delivery_carrier_global_manifest/i18n/es.po
  delivery_carrier_global_manifest/models/__init__.py
  delivery_carrier_global_manifest/models/delivery_carrier.py
  delivery_carrier_global_manifest/pyproject.toml
  delivery_carrier_global_manifest/readme/CONFIGURE.md
  delivery_carrier_global_manifest/readme/CONTRIBUTORS.md
  delivery_carrier_global_manifest/readme/DESCRIPTION.md
  delivery_carrier_global_manifest/readme/USAGE.md
  delivery_carrier_global_manifest/report/manifest_wizard_view.xml
  delivery_carrier_global_manifest/static/description/icon.png
  delivery_carrier_global_manifest/static/description/icon.svg
  delivery_carrier_global_manifest/static/description/index.html
  delivery_carrier_global_manifest/tests/__init__.py
  delivery_carrier_global_manifest/tests/test_delivery_carrier_global_manifest.py
  delivery_carrier_global_manifest/views/delivery_carrier_view.xml
  delivery_carrier_global_manifest/wizards/__init__.py
  delivery_carrier_global_manifest/wizards/manifest_wizard.py
  delivery_carrier_global_manifest/wizards/manifest_wizard_view.xml
Labels: approved, ready to merge, bot is merging ⏳
