Repository OCA/delivery-carrier, pull requests merged in 2025-01, with the labels that each got.

#926 [16.0][FIX] delivery_price_method: the price rules field in the carrier when a supplier is selected
  delivery_price_method/views/delivery_carrier_views.xml
Labels: bot is merging ⏳

#924 [16.0] [ADD] delivery_state_manual
  delivery_state_manual/README.rst
  delivery_state_manual/__init__.py
  delivery_state_manual/__manifest__.py
  delivery_state_manual/models/__init__.py
  delivery_state_manual/models/delivery_carrier.py
  delivery_state_manual/models/stock_picking.py
  delivery_state_manual/readme/CONFIGURE.md
  delivery_state_manual/readme/CONTRIBUTORS.md
  delivery_state_manual/readme/DESCRIPTION.md
  delivery_state_manual/readme/USAGE.md
  delivery_state_manual/static/description/icon.png
  delivery_state_manual/static/description/icon.svg
  delivery_state_manual/static/description/index.html
  delivery_state_manual/tests/__init__.py
  delivery_state_manual/tests/test_delivery_state_manual.py
  delivery_state_manual/views/delivery_carrier_views.xml
  delivery_state_manual/views/stock_picking_views.xml
  setup/delivery_state_manual/odoo/addons/delivery_state_manual
  setup/delivery_state_manual/setup.py
Labels: needs review, approved, ready to merge, bot is merging ⏳

#934 [15.0][MIG] delivery_correos_express: Migration to 15.0
  delivery_correos_express/README.rst
  delivery_correos_express/__init__.py
  delivery_correos_express/__manifest__.py
  delivery_correos_express/doc/GrabacionEnvios/DC_SP_ apiRestSeguimientoEnviosk8s_v01.00.pdf
  delivery_correos_express/doc/GrabacionEnvios/DC_SP_WS_GrabacionEnviosRest_v03.07.pdf
  delivery_correos_express/doc/GrabacionEnvios/DC_SP_WS_ListEnviosRest_v01.01.pdf
  delivery_correos_express/doc/GrabacionEnvios/DC_SP_WS_apiRestEtiquetaTransporte_v01.01.pdf
  delivery_correos_express/doc/GrabacionRecogidas/DC_SP_Seguimiento_Recogidak8s_v01.00.pdf
  delivery_correos_express/doc/GrabacionRecogidas/DC_SP_WS_GrabacionRecogidaRest_v1.4.pdf
  delivery_correos_express/i18n/delivery_correos_express.pot
  delivery_correos_express/i18n/es.po
  delivery_correos_express/i18n/it.po
  delivery_correos_express/models/__init__.py
  delivery_correos_express/models/correos_express_request.py
  delivery_correos_express/models/delivery_carrier.py
  delivery_correos_express/models/stock_picking.py
  delivery_correos_express/readme/CONFIGURE.rst
  delivery_correos_express/readme/CONTRIBUTORS.rst
  delivery_correos_express/readme/DESCRIPTION.rst
  delivery_correos_express/readme/INSTALL.rst
  delivery_correos_express/readme/ROADMAP.rst
  delivery_correos_express/readme/USAGE.rst
  delivery_correos_express/static/description/icon.png
  delivery_correos_express/static/description/index.html
  delivery_correos_express/tests/__init__.py
  delivery_correos_express/tests/test_delivery_correos_express.py
  delivery_correos_express/views/delivery_carrier_view.xml
  delivery_correos_express/views/stock_picking_views.xml
  requirements.txt
  setup/delivery_correos_express/odoo/addons/delivery_correos_express
  setup/delivery_correos_express/setup.py
Labels: approved, bot is merging ⏳

#931 [17.0][MIG] delivery_free_fee_removal: Migration to 17.0
  delivery_free_fee_removal/README.rst
  delivery_free_fee_removal/__init__.py
  delivery_free_fee_removal/__manifest__.py
  delivery_free_fee_removal/i18n/delivery_free_fee_removal.pot
  delivery_free_fee_removal/i18n/es.po
  delivery_free_fee_removal/models/__init__.py
  delivery_free_fee_removal/models/sale_order_line.py
  delivery_free_fee_removal/pyproject.toml
  delivery_free_fee_removal/readme/CONTRIBUTORS.md
  delivery_free_fee_removal/readme/CREDITS.md
  delivery_free_fee_removal/readme/DESCRIPTION.md
  delivery_free_fee_removal/reports/sale_report_templates.xml
  delivery_free_fee_removal/static/description/icon.png
  delivery_free_fee_removal/static/description/index.html
  delivery_free_fee_removal/tests/__init__.py
  delivery_free_fee_removal/tests/test_delivery_free_fee_removal.py
  delivery_free_fee_removal/views/sale_order_views.xml
Labels: needs review, approved, migration, bot is merging ⏳

#937 [17.0][MIG] delivery_carrier_manual_weight: migration to 17.0
  delivery_carrier_manual_weight/README.rst
  delivery_carrier_manual_weight/__init__.py
  delivery_carrier_manual_weight/__manifest__.py
  delivery_carrier_manual_weight/i18n/delivery_carrier_manual_weight.pot
  delivery_carrier_manual_weight/i18n/it.po
  delivery_carrier_manual_weight/models/__init__.py
  delivery_carrier_manual_weight/models/delivery_carrier.py
  delivery_carrier_manual_weight/models/stock_picking.py
  delivery_carrier_manual_weight/pyproject.toml
  delivery_carrier_manual_weight/readme/CONTRIBUTORS.md
  delivery_carrier_manual_weight/readme/DESCRIPTION.md
  delivery_carrier_manual_weight/readme/USAGE.md
  delivery_carrier_manual_weight/static/description/icon.png
  delivery_carrier_manual_weight/static/description/index.html
  delivery_carrier_manual_weight/tests/__init__.py
  delivery_carrier_manual_weight/tests/test_delivery_carrier_manual_weight.py
  delivery_carrier_manual_weight/views/delivery_view.xml
Labels: approved, bot is merging ⏳

#928 [17.0][MIG] delivery_carrier_customer_info: Migration to 17.0 (renamed partner_delivery_info)
  partner_delivery_info/README.rst
  partner_delivery_info/__init__.py
  partner_delivery_info/__manifest__.py
  partner_delivery_info/i18n/es.po
  partner_delivery_info/i18n/partner_delivery_info.pot
  partner_delivery_info/models/__init__.py
  partner_delivery_info/models/res_partner.py
  partner_delivery_info/models/res_partner_delivery_info.py
  partner_delivery_info/pyproject.toml
  partner_delivery_info/readme/CONTRIBUTORS.md
  partner_delivery_info/readme/CREDITS.md
  partner_delivery_info/readme/DESCRIPTION.md
  partner_delivery_info/security/ir.model.access.csv
  partner_delivery_info/static/description/icon.png
  partner_delivery_info/static/description/index.html
  partner_delivery_info/views/menus.xml
  partner_delivery_info/views/res_partner.xml
  partner_delivery_info/views/res_partner_delivery_info.xml
Labels: approved, ready to merge, bot is merging ⏳
