Repository OCA/delivery-carrier, pull requests merged in 2025-02, with the labels that each got.

#710 [14.0][FIX] delivery_schenker: correct float_round return
  delivery_schenker/models/delivery_carrier.py
  delivery_schenker/tests/common.py
  delivery_schenker_quant_package_dimension/tests/test_delivery_schenker.py
Labels: approved, ready to merge, bot is merging ⏳

#942 [18.0][MIG] partner_delivery_schedule: Migration to 18.0
  partner_delivery_schedule/README.rst
  partner_delivery_schedule/__init__.py
  partner_delivery_schedule/__manifest__.py
  partner_delivery_schedule/i18n/es.po
  partner_delivery_schedule/i18n/it.po
  partner_delivery_schedule/i18n/nl.po
  partner_delivery_schedule/i18n/partner_delivery_schedule.pot
  partner_delivery_schedule/i18n/zh_CN.po
  partner_delivery_schedule/models/__init__.py
  partner_delivery_schedule/models/partner_delivery_schedule.py
  partner_delivery_schedule/models/res_partner.py
  partner_delivery_schedule/pyproject.toml
  partner_delivery_schedule/readme/CONTRIBUTORS.md
  partner_delivery_schedule/readme/DESCRIPTION.md
  partner_delivery_schedule/readme/USAGE.md
  partner_delivery_schedule/security/ir.model.access.csv
  partner_delivery_schedule/static/description/icon.png
  partner_delivery_schedule/static/description/index.html
  partner_delivery_schedule/tests/__init__.py
  partner_delivery_schedule/tests/test_partner_delivery_schedule.py
  partner_delivery_schedule/views/partner_delivery_schedule_view.xml
  partner_delivery_schedule/views/report_shipping.xml
  partner_delivery_schedule/views/res_partner_view.xml
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#947 [14.0][IMP] delivery_price_product_domain, delivery_price_collection_cost_product_domain: use context order_id for product domain application in price computation
  delivery_price_collection_cost_product_domain/models/delivery_carrier.py
  delivery_price_product_domain/models/delivery_carrier.py
Labels: approved, bot is merging ⏳

#945 [18.0] moving delivery_carrier_warehouse from wms to delivery-carrier repo
  delivery_carrier_warehouse/README.rst
  delivery_carrier_warehouse/__init__.py
  delivery_carrier_warehouse/__manifest__.py
  delivery_carrier_warehouse/i18n/delivery_carrier_warehouse.pot
  delivery_carrier_warehouse/i18n/es_AR.po
  delivery_carrier_warehouse/i18n/it.po
  delivery_carrier_warehouse/models/__init__.py
  delivery_carrier_warehouse/models/sale_order.py
  delivery_carrier_warehouse/models/stock_warehouse.py
  delivery_carrier_warehouse/pyproject.toml
  delivery_carrier_warehouse/readme/CONTRIBUTORS.md
  delivery_carrier_warehouse/readme/CREDITS.md
  delivery_carrier_warehouse/readme/DESCRIPTION.md
  delivery_carrier_warehouse/static/description/icon.png
  delivery_carrier_warehouse/static/description/index.html
  delivery_carrier_warehouse/tests/__init__.py
  delivery_carrier_warehouse/tests/test_delivery_carrier_warehouse.py
  delivery_carrier_warehouse/views/stock_warehouse.xml
Labels: approved, bot is merging ⏳

#782 [14.0][FIX] delivery_send_to_shipper_at_operation: Keep delivery_notification_sent set on backorder
  delivery_send_to_shipper_at_operation/models/stock_picking.py
  delivery_send_to_shipper_at_operation/readme/CONTRIBUTORS.rst
  delivery_send_to_shipper_at_operation/tests/test_send_to_shipper.py
Labels: enhancement, needs review, bot is merging ⏳, no stale

#922 [18.0][MIG] server_environment_delivery: Migration to 18.0
  server_environment_delivery/README.rst
  server_environment_delivery/__init__.py
  server_environment_delivery/__manifest__.py
  server_environment_delivery/i18n/es.po
  server_environment_delivery/i18n/it.po
  server_environment_delivery/i18n/server_environment_delivery.pot
  server_environment_delivery/models/__init__.py
  server_environment_delivery/models/delivery_carrier.py
  server_environment_delivery/pyproject.toml
  server_environment_delivery/readme/CONFIGURE.md
  server_environment_delivery/readme/CONTRIBUTORS.md
  server_environment_delivery/readme/CREDITS.md
  server_environment_delivery/readme/DESCRIPTION.md
  server_environment_delivery/static/description/icon.png
  server_environment_delivery/static/description/index.html
Labels: approved, ready to merge, bot is merging ⏳

#938 [18][ADD] delivery_carrier_shipping_label : extracted from base_delivery_carrier_label
  delivery_carrier_shipping_label/README.rst
  delivery_carrier_shipping_label/__init__.py
  delivery_carrier_shipping_label/__manifest__.py
  delivery_carrier_shipping_label/models/__init__.py
  delivery_carrier_shipping_label/models/delivery_carrier.py
  delivery_carrier_shipping_label/models/shipping_label.py
  delivery_carrier_shipping_label/models/stock_picking.py
  delivery_carrier_shipping_label/pyproject.toml
  delivery_carrier_shipping_label/readme/CONTRIBUTORS.md
  delivery_carrier_shipping_label/readme/DESCRIPTION.md
  delivery_carrier_shipping_label/readme/USAGE.md
  delivery_carrier_shipping_label/security/ir.model.access.csv
  delivery_carrier_shipping_label/static/description/index.html
  delivery_carrier_shipping_label/tests/__init__.py
  delivery_carrier_shipping_label/tests/test_shipping_label.py
  delivery_carrier_shipping_label/views/delivery_carrier.xml
  delivery_carrier_shipping_label/views/delivery_carrier_option.xml
  delivery_carrier_shipping_label/views/delivery_carrier_template_option.xml
  delivery_carrier_shipping_label/views/stock_picking.xml
Labels: approved, bot is merging ⏳

#944 [18.0][MIG] stock_picking_carrier_from_rule
  stock_picking_carrier_from_rule/README.rst
  stock_picking_carrier_from_rule/__init__.py
  stock_picking_carrier_from_rule/__manifest__.py
  stock_picking_carrier_from_rule/i18n/es.po
  stock_picking_carrier_from_rule/i18n/it.po
  stock_picking_carrier_from_rule/i18n/stock_picking_carrier_from_rule.pot
  stock_picking_carrier_from_rule/models/__init__.py
  stock_picking_carrier_from_rule/models/stock_move.py
  stock_picking_carrier_from_rule/pyproject.toml
  stock_picking_carrier_from_rule/readme/CONTRIBUTORS.md
  stock_picking_carrier_from_rule/readme/CREDITS.md
  stock_picking_carrier_from_rule/readme/DESCRIPTION.md
  stock_picking_carrier_from_rule/readme/ROADMAP.md
  stock_picking_carrier_from_rule/static/description/icon.png
  stock_picking_carrier_from_rule/static/description/index.html
  stock_picking_carrier_from_rule/tests/__init__.py
  stock_picking_carrier_from_rule/tests/test_stock_picking_carrier_from_rule.py
Labels: approved, bot is merging ⏳

#957 [18.0][MIG] delivery_carrier_account: Migration to 18.0
  delivery_carrier_account/README.rst
  delivery_carrier_account/__init__.py
  delivery_carrier_account/__manifest__.py
  delivery_carrier_account/i18n/delivery_carrier_account.pot
  delivery_carrier_account/i18n/es.po
  delivery_carrier_account/i18n/it.po
  delivery_carrier_account/models/__init__.py
  delivery_carrier_account/models/carrier_account.py
  delivery_carrier_account/models/delivery_carrier.py
  delivery_carrier_account/models/stock_picking.py
  delivery_carrier_account/pyproject.toml
  delivery_carrier_account/readme/CONTRIBUTORS.md
  delivery_carrier_account/readme/DESCRIPTION.md
  delivery_carrier_account/security/carrier_security.xml
  delivery_carrier_account/security/ir.model.access.csv
  delivery_carrier_account/static/description/icon.png
  delivery_carrier_account/static/description/index.html
  delivery_carrier_account/tests/__init__.py
  delivery_carrier_account/tests/test_carrier_account.py
  delivery_carrier_account/views/carrier_account.xml
  delivery_carrier_account/views/delivery_carrier.xml
Labels: approved, ready to merge, bot is merging ⏳

#939 [16][IMP] delivery_package_number: changes on delivery_package_number_document
  delivery_package_number/reports/report_package_number.xml
Labels: enhancement, needs review, approved, ready to merge, bot is merging ⏳

#936 [18.0][MIG] delivery_carrier_info: Migration to 18.0
  delivery_carrier_info/README.rst
  delivery_carrier_info/__init__.py
  delivery_carrier_info/__manifest__.py
  delivery_carrier_info/i18n/delivery_carrier_info.pot
  delivery_carrier_info/i18n/es.po
  delivery_carrier_info/i18n/it.po
  delivery_carrier_info/models/__init__.py
  delivery_carrier_info/models/delivery_carrier.py
  delivery_carrier_info/pyproject.toml
  delivery_carrier_info/readme/CONTRIBUTORS.md
  delivery_carrier_info/readme/DESCRIPTION.md
  delivery_carrier_info/readme/USAGE.md
  delivery_carrier_info/static/description/icon.png
  delivery_carrier_info/static/description/index.html
  delivery_carrier_info/views/delivery_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#979 [18.0][FIX] partner_delivery_schedule: Incorrect module dependency
  partner_delivery_schedule/__manifest__.py
Labels: approved, bot is merging ⏳

#981 [17.0][MIG] delivery_price_method: Migration to 17.0
  delivery_price_method/README.rst
  delivery_price_method/__init__.py
  delivery_price_method/__manifest__.py
  delivery_price_method/i18n/delivery_price_method.pot
  delivery_price_method/i18n/es.po
  delivery_price_method/i18n/es_CL.po
  delivery_price_method/i18n/es_VE.po
  delivery_price_method/i18n/fr.po
  delivery_price_method/i18n/it.po
  delivery_price_method/i18n/pt.po
  delivery_price_method/models/__init__.py
  delivery_price_method/models/delivery_carrier.py
  delivery_price_method/pyproject.toml
  delivery_price_method/readme/CONTRIBUTORS.md
  delivery_price_method/readme/DESCRIPTION.md
  delivery_price_method/readme/USAGE.md
  delivery_price_method/static/description/icon.png
  delivery_price_method/static/description/index.html
  delivery_price_method/tests/__init__.py
  delivery_price_method/tests/test_delivery_price_method.py
  delivery_price_method/views/delivery_carrier_views.xml
Labels: bot is merging ⏳

#978 [17.0][MIG] partner_delivery_schedule: Migration to 17.0
  partner_delivery_schedule/README.rst
  partner_delivery_schedule/__init__.py
  partner_delivery_schedule/__manifest__.py
  partner_delivery_schedule/i18n/es.po
  partner_delivery_schedule/i18n/it.po
  partner_delivery_schedule/i18n/nl.po
  partner_delivery_schedule/i18n/partner_delivery_schedule.pot
  partner_delivery_schedule/i18n/zh_CN.po
  partner_delivery_schedule/models/__init__.py
  partner_delivery_schedule/models/partner_delivery_schedule.py
  partner_delivery_schedule/models/res_partner.py
  partner_delivery_schedule/pyproject.toml
  partner_delivery_schedule/readme/CONTRIBUTORS.md
  partner_delivery_schedule/readme/DESCRIPTION.md
  partner_delivery_schedule/readme/USAGE.md
  partner_delivery_schedule/security/ir.model.access.csv
  partner_delivery_schedule/static/description/icon.png
  partner_delivery_schedule/static/description/index.html
  partner_delivery_schedule/tests/__init__.py
  partner_delivery_schedule/tests/test_partner_delivery_schedule.py
  partner_delivery_schedule/views/partner_delivery_schedule_view.xml
  partner_delivery_schedule/views/report_shipping.xml
  partner_delivery_schedule/views/res_partner_view.xml
Labels: needs review, approved, migration, bot is merging ⏳

#900 [18][ADD/MIG] delivery_carrier_option (extracted from base_delivery_carrier_label module)
  delivery_carrier_option/README.rst
  delivery_carrier_option/__init__.py
  delivery_carrier_option/__manifest__.py
  delivery_carrier_option/models/__init__.py
  delivery_carrier_option/models/delivery_carrier.py
  delivery_carrier_option/models/delivery_carrier_option.py
  delivery_carrier_option/models/delivery_carrier_template_option.py
  delivery_carrier_option/models/stock_picking.py
  delivery_carrier_option/pyproject.toml
  delivery_carrier_option/readme/CONTRIBUTORS.md
  delivery_carrier_option/readme/DESCRIPTION.md
  delivery_carrier_option/security/ir.model.access.csv
  delivery_carrier_option/static/description/icon.png
  delivery_carrier_option/static/description/index.html
  delivery_carrier_option/tests/__init__.py
  delivery_carrier_option/tests/test_options.py
  delivery_carrier_option/views/delivery_carrier.xml
  delivery_carrier_option/views/delivery_carrier_option.xml
  delivery_carrier_option/views/delivery_carrier_template_option.xml
  delivery_carrier_option/views/stock_picking.xml
Labels: approved, ready to merge, bot is merging ⏳

#988 [17.0][MIG] delivery_multi_destination: Migration to 17.0
  delivery_multi_destination/README.rst
  delivery_multi_destination/__init__.py
  delivery_multi_destination/__manifest__.py
  delivery_multi_destination/demo/delivery_carrier_demo.xml
  delivery_multi_destination/i18n/cs_CZ.po
  delivery_multi_destination/i18n/de.po
  delivery_multi_destination/i18n/delivery_multi_destination.pot
  delivery_multi_destination/i18n/es.po
  delivery_multi_destination/i18n/fr.po
  delivery_multi_destination/i18n/it.po
  delivery_multi_destination/i18n/nl.po
  delivery_multi_destination/i18n/nl_NL.po
  delivery_multi_destination/i18n/pt_BR.po
  delivery_multi_destination/i18n/sl.po
  delivery_multi_destination/i18n/zh_CN.po
  delivery_multi_destination/models/__init__.py
  delivery_multi_destination/models/delivery_carrier.py
  delivery_multi_destination/pyproject.toml
  delivery_multi_destination/readme/CONFIGURE.md
  delivery_multi_destination/readme/CONTRIBUTORS.md
  delivery_multi_destination/readme/DESCRIPTION.md
  delivery_multi_destination/readme/ROADMAP.md
  delivery_multi_destination/readme/USAGE.md
  delivery_multi_destination/static/description/icon.png
  delivery_multi_destination/static/description/index.html
  delivery_multi_destination/tests/__init__.py
  delivery_multi_destination/tests/test_delivery_multi_destination.py
  delivery_multi_destination/views/delivery_carrier_view.xml
Labels: approved, bot is merging ⏳

#993 [16.0][FIX] delivery_auto_refresh: don't try to create lines over a new id
  delivery_auto_refresh/models/sale_order.py
Labels: approved, bot is merging ⏳

#994 [16.0][FIX] delivery_auto_refresh: Fallback to load CoA
  delivery_auto_refresh/tests/test_delivery_auto_refresh.py
Labels: bot is merging ⏳

#987 [18.0][MIG] stock_picking_delivery_link
  stock_picking_delivery_link/README.rst
  stock_picking_delivery_link/__init__.py
  stock_picking_delivery_link/__manifest__.py
  stock_picking_delivery_link/i18n/es.po
  stock_picking_delivery_link/i18n/fr.po
  stock_picking_delivery_link/i18n/it.po
  stock_picking_delivery_link/i18n/stock_picking_delivery_link.pot
  stock_picking_delivery_link/i18n/tr.po
  stock_picking_delivery_link/models/__init__.py
  stock_picking_delivery_link/models/stock_picking.py
  stock_picking_delivery_link/models/stock_picking_type.py
  stock_picking_delivery_link/pyproject.toml
  stock_picking_delivery_link/readme/CONTRIBUTORS.rst
  stock_picking_delivery_link/readme/DESCRIPTION.rst
  stock_picking_delivery_link/static/description/icon.png
  stock_picking_delivery_link/static/description/index.html
  stock_picking_delivery_link/tests/__init__.py
  stock_picking_delivery_link/tests/common.py
  stock_picking_delivery_link/tests/models/delivery_carrier.py
  stock_picking_delivery_link/tests/test_delivery_link.py
  stock_picking_delivery_link/views/stock_picking.xml
  stock_picking_delivery_link/views/stock_picking_type.xml
  test-requirements.txt
Labels: approved, migration, bot is merging ⏳

#929 [18.0][MIG] partner_delivery_info: Migration to 18.0
  partner_delivery_info/README.rst
  partner_delivery_info/__init__.py
  partner_delivery_info/__manifest__.py
  partner_delivery_info/i18n/es.po
  partner_delivery_info/i18n/partner_delivery_info.pot
  partner_delivery_info/models/__init__.py
  partner_delivery_info/models/res_partner.py
  partner_delivery_info/models/res_partner_delivery_info.py
  partner_delivery_info/pyproject.toml
  partner_delivery_info/readme/CONTRIBUTORS.md
  partner_delivery_info/readme/CREDITS.md
  partner_delivery_info/readme/DESCRIPTION.md
  partner_delivery_info/security/ir.model.access.csv
  partner_delivery_info/static/description/icon.png
  partner_delivery_info/static/description/index.html
  partner_delivery_info/views/menus.xml
  partner_delivery_info/views/res_partner.xml
  partner_delivery_info/views/res_partner_delivery_info.xml
Labels: approved, ready to merge, bot is merging ⏳

#995 [17.0][MIG] partner_delivery_zone: Migration to 17.0
  partner_delivery_zone/README.rst
  partner_delivery_zone/__init__.py
  partner_delivery_zone/__manifest__.py
  partner_delivery_zone/i18n/de.po
  partner_delivery_zone/i18n/es.po
  partner_delivery_zone/i18n/fr_FR.po
  partner_delivery_zone/i18n/it.po
  partner_delivery_zone/i18n/partner_delivery_zone.pot
  partner_delivery_zone/i18n/zh_CN.po
  partner_delivery_zone/models/__init__.py
  partner_delivery_zone/models/partner_delivery_zone.py
  partner_delivery_zone/models/res_partner.py
  partner_delivery_zone/models/sale_order.py
  partner_delivery_zone/models/stock_move.py
  partner_delivery_zone/models/stock_picking.py
  partner_delivery_zone/pyproject.toml
  partner_delivery_zone/readme/CONFIGURATION.rst
  partner_delivery_zone/readme/CONFIGURE.md
  partner_delivery_zone/readme/CONTRIBUTORS.md
  partner_delivery_zone/readme/DESCRIPTION.md
  partner_delivery_zone/readme/ROADMAP.md
  partner_delivery_zone/readme/USAGE.md
  partner_delivery_zone/security/ir.model.access.csv
  partner_delivery_zone/static/description/icon.png
  partner_delivery_zone/static/description/index.html
  partner_delivery_zone/tests/__init__.py
  partner_delivery_zone/tests/test_partner_delivery_zone.py
  partner_delivery_zone/views/partner_delivery_zone_view.xml
  partner_delivery_zone/views/report_deliveryslip.xml
  partner_delivery_zone/views/report_shipping.xml
  partner_delivery_zone/views/res_partner_view.xml
  partner_delivery_zone/views/sale_order_view.xml
  partner_delivery_zone/views/stock_picking_view.xml
Labels: approved, bot is merging ⏳
