Repository OCA/delivery-carrier, pull requests merged in 2025-05, with the labels that each got.

#1002 [17.0][MIG] delivery_auto_refresh: Migration to 17.0
  delivery_auto_refresh/README.rst
  delivery_auto_refresh/__init__.py
  delivery_auto_refresh/__manifest__.py
  delivery_auto_refresh/i18n/ca.po
  delivery_auto_refresh/i18n/cs_CZ.po
  delivery_auto_refresh/i18n/de.po
  delivery_auto_refresh/i18n/delivery_auto_refresh.pot
  delivery_auto_refresh/i18n/el_GR.po
  delivery_auto_refresh/i18n/es.po
  delivery_auto_refresh/i18n/es_ES.po
  delivery_auto_refresh/i18n/es_VE.po
  delivery_auto_refresh/i18n/fi.po
  delivery_auto_refresh/i18n/fr.po
  delivery_auto_refresh/i18n/gl.po
  delivery_auto_refresh/i18n/hr.po
  delivery_auto_refresh/i18n/hr_HR.po
  delivery_auto_refresh/i18n/hu.po
  delivery_auto_refresh/i18n/it.po
  delivery_auto_refresh/i18n/nl.po
  delivery_auto_refresh/i18n/nl_NL.po
  delivery_auto_refresh/i18n/pt.po
  delivery_auto_refresh/i18n/pt_BR.po
  delivery_auto_refresh/i18n/ro.po
  delivery_auto_refresh/i18n/sl.po
  delivery_auto_refresh/i18n/tr.po
  delivery_auto_refresh/i18n/tr_TR.po
  delivery_auto_refresh/i18n/vi_VN.po
  delivery_auto_refresh/i18n/zh_CN.po
  delivery_auto_refresh/migrations/17.0.1.0.0/pre-migration.py
  delivery_auto_refresh/models/__init__.py
  delivery_auto_refresh/models/res_company.py
  delivery_auto_refresh/models/res_config_settings.py
  delivery_auto_refresh/models/sale_order.py
  delivery_auto_refresh/models/stock_picking.py
  delivery_auto_refresh/pyproject.toml
  delivery_auto_refresh/readme/CONFIGURE.md
  delivery_auto_refresh/readme/CONTRIBUTORS.md
  delivery_auto_refresh/readme/DESCRIPTION.md
  delivery_auto_refresh/readme/ROADMAP.md
  delivery_auto_refresh/static/description/icon.png
  delivery_auto_refresh/static/description/index.html
  delivery_auto_refresh/tests/__init__.py
  delivery_auto_refresh/tests/test_delivery_auto_refresh.py
  delivery_auto_refresh/views/res_config_settings_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#972 [18.0][MIG] delivery_postlogistics_server_env: Migration to 18.0
  delivery_postlogistics_server_env/README.rst
  delivery_postlogistics_server_env/__init__.py
  delivery_postlogistics_server_env/__manifest__.py
  delivery_postlogistics_server_env/i18n/delivery_postlogistics_server_env.pot
  delivery_postlogistics_server_env/i18n/es.po
  delivery_postlogistics_server_env/i18n/it.po
  delivery_postlogistics_server_env/i18n/pt_BR.po
  delivery_postlogistics_server_env/models/__init__.py
  delivery_postlogistics_server_env/models/delivery_carrier.py
  delivery_postlogistics_server_env/pyproject.toml
  delivery_postlogistics_server_env/readme/CONTRIBUTORS.md
  delivery_postlogistics_server_env/readme/CREDITS.md
  delivery_postlogistics_server_env/readme/DESCRIPTION.md
  delivery_postlogistics_server_env/static/description/icon.png
  delivery_postlogistics_server_env/static/description/index.html
  delivery_postlogistics_server_env/tests/__init__.py
  delivery_postlogistics_server_env/tests/test_delivery_postlogistics_server_env.py
Labels: approved, bot is merging ⏳

#941 [18.0] [MIG] delivery_postlogistics_dangerous_goods: Migration to 18.0
  delivery_postlogistics_dangerous_goods/README.rst
  delivery_postlogistics_dangerous_goods/__init__.py
  delivery_postlogistics_dangerous_goods/__manifest__.py
  delivery_postlogistics_dangerous_goods/i18n/delivery_postlogistics_dangerous_goods.pot
  delivery_postlogistics_dangerous_goods/i18n/es.po
  delivery_postlogistics_dangerous_goods/i18n/it.po
  delivery_postlogistics_dangerous_goods/models/__init__.py
  delivery_postlogistics_dangerous_goods/models/stock_picking.py
  delivery_postlogistics_dangerous_goods/pyproject.toml
  delivery_postlogistics_dangerous_goods/readme/CONTRIBUTORS.md
  delivery_postlogistics_dangerous_goods/readme/DESCRIPTION.md
  delivery_postlogistics_dangerous_goods/static/description/icon.png
  delivery_postlogistics_dangerous_goods/static/description/index.html
  delivery_postlogistics_dangerous_goods/tests/__init__.py
  delivery_postlogistics_dangerous_goods/tests/test_postlogistics_dangerous_goods.py
Labels: needs review, migration, bot is merging ⏳

#1012 [18.0][MIG] delivery_price_method: Migration to 18.0
  delivery_price_method/README.rst
  delivery_price_method/__init__.py
  delivery_price_method/__manifest__.py
  delivery_price_method/i18n/delivery_price_method.pot
  delivery_price_method/i18n/es.po
  delivery_price_method/i18n/es_CL.po
  delivery_price_method/i18n/es_VE.po
  delivery_price_method/i18n/fr.po
  delivery_price_method/i18n/it.po
  delivery_price_method/i18n/pt.po
  delivery_price_method/models/__init__.py
  delivery_price_method/models/delivery_carrier.py
  delivery_price_method/pyproject.toml
  delivery_price_method/readme/CONTRIBUTORS.md
  delivery_price_method/readme/DESCRIPTION.md
  delivery_price_method/readme/USAGE.md
  delivery_price_method/static/description/icon.png
  delivery_price_method/static/description/index.html
  delivery_price_method/tests/__init__.py
  delivery_price_method/tests/common.py
  delivery_price_method/tests/test_delivery_price_method.py
  delivery_price_method/views/delivery_carrier_views.xml
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#1013 [17.0] [IMP] base_delivery_carrier_label: add setting to not set default packages in shipper send
  base_delivery_carrier_label/README.rst
  base_delivery_carrier_label/models/__init__.py
  base_delivery_carrier_label/models/res_company.py
  base_delivery_carrier_label/models/res_config_settings.py
  base_delivery_carrier_label/models/stock_picking.py
  base_delivery_carrier_label/readme/CONFIGURE.md
  base_delivery_carrier_label/static/description/index.html
  base_delivery_carrier_label/views/res_config.xml
Labels: approved, ready to merge, bot is merging ⏳

#980 [18.0][MIG] delivery_state: Migration to 18.0
  delivery_state/README.rst
  delivery_state/__init__.py
  delivery_state/__manifest__.py
  delivery_state/data/ir_cron_data.xml
  delivery_state/data/mail_template.xml
  delivery_state/i18n/delivery_state.pot
  delivery_state/i18n/es.po
  delivery_state/i18n/fr.po
  delivery_state/i18n/it.po
  delivery_state/models/__init__.py
  delivery_state/models/delivery_carrier.py
  delivery_state/models/res_company.py
  delivery_state/models/res_config_settings.py
  delivery_state/models/stock_picking.py
  delivery_state/pyproject.toml
  delivery_state/readme/CONFIGURE.md
  delivery_state/readme/CONTRIBUTORS.md
  delivery_state/readme/DESCRIPTION.md
  delivery_state/readme/USAGE.md
  delivery_state/static/description/icon.png
  delivery_state/static/description/index.html
  delivery_state/tests/__init__.py
  delivery_state/tests/test_delivery_state.py
  delivery_state/views/res_config_settings_view.xml
  delivery_state/views/stock_picking_views.xml
Labels: needs review, approved, migration, bot is merging ⏳
